### ISSUE TITLE
Errors when importing `fastai.dataset`

### ISSUE THREAD

**Issue by zc-alexfan** [fastai/fastai#1134]
I am trying to setup an ML model using fastai and have to do the following imports: 

    import fastai.models
    import fastai.nlp
    import fastai.dataset

However, it gives me the following error by the `fastai` imports. 

    Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
    [GCC 7.3.0] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import fastai.nlp
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/fastai/nlp.py", line 172
        if os.path.isdir(path): paths=glob(f'{path}/*.*')
                                                       ^
    SyntaxError: invalid syntax

Apparently, the character `f` in `glob(f'{path}/*.*')` is causing the error. I fixed the error by removing `f`, but it seems that there are lots of these errors in the `fastai` library. 

My current thought is that I am using an incorrect python version. Could anyone give me some pointer?

**Comment by devforfu** [comment]
I think that the problem is a too old version of Python. As I can see from your shell's output, you're using Python 2.7 but strings interpolation (strings starting with `f` symbol) were introduced in Python 3.5 only. You need to update your interpreter.

**Comment by zc-alexfan** [comment]
Thanks for the response.  I installed fastai on python 3.6.6 as well. It allows me to do `import fastai` but doesn't allow me to `import fastai.dataset`. It says the package `dataset` does not exist. However, I do need the module `dataset`.

**Comment by devforfu** [comment]
Probably you're using an old version of `fastai` package? As soon as I know, `fastai.nlp` was renamed into `fastai.text` in `v1`.
