### ISSUE TITLE
Error sampling a batch from an object detection dataset

### ISSUE THREAD

**Issue by nhonth** [fastai/fastai#1177]
**Describe the bug**

When sampling a batch from an object detection dataset, I got an error `TypeError: can't assign a memoryview to a torch.LongTensor`

**To Reproduce**

Using code similar to the example on the documentation page (https://docs.fast.ai/data_block.html)

```
print(torch.__version__)
print(fastai.__version__)
coco = untar_data(URLs.COCO_TINY)
images, lbl_bbox = get_annotations(coco/'train.json')
img2bbox = dict(zip(images, lbl_bbox))
get_y_func= lambda o: img2bbox[o.name]
data = (ObjectItemList.from_folder(coco)
        #Where are the images? -> in coco
        .random_split_by_pct()                          
        #How to split in train/valid? -> randomly with the default 20% in valid
        .label_from_func(get_y_func)
        #How to find the labels? -> use get_y_func
        .transform(get_transforms(), tfm_y=True)
        #Data augmentation? -> Standard transforms with tfm_y=True
        .databunch(bs=16, collate_fn=bb_pad_collate)
       )
xb, yb = next(iter(data.dl()))
```

produces the following output
```
1.0.0.dev20181114
1.0.25.dev0
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-685fb2c6b5ba> in <module>()
     15         .databunch(bs=16, collate_fn=bb_pad_collate)
     16        )
---> 17 xb, yb = next(iter(data.dl()))

~/vmr_arl/code/fastai/fastai/basic_data.py in __iter__(self)
     45     def __iter__(self):
     46         "Process and returns items from `DataLoader`."
---> 47         for b in self.dl:
     48             y = b[1][0] if is_listy(b[1]) else b[1]
     49             if not self.skip_size1 or y.size(0) != 1:

~/anaconda3/envs/aerialvideo/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    635                 self.reorder_dict[idx] = batch
    636                 continue
--> 637             return self._process_next_batch(batch)
    638 
    639     next = __next__  # Python 2 compatibility

~/anaconda3/envs/aerialvideo/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    656         self._put_indices()
    657         if isinstance(batch, ExceptionWrapper):
--> 658             raise batch.exc_type(batch.exc_msg)
    659         return batch
    660 

TypeError: Traceback (most recent call last):
  File "/home/local/SRI/e27278/anaconda3/envs/aerialvideo/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/local/SRI/e27278/vmr_arl/code/fastai/fastai/vision/data.py", line 51, in bb_pad_collate
    labels[i,-len(lbls):] = lbls
TypeError: can't assign a memoryview to a torch.LongTensor
```

**Expected behavior**

A sample batch.

**Screenshots**

**Additional context**

I think the problem is with the function `ImageBBox.data`:

```
@property
    def data(self)->Union[FloatTensor, Tuple[FloatTensor,LongTensor]]:
        bboxes,lbls = self._compute_boxes()
        return bboxes if lbls is None else (bboxes, lbls.data)
```
Note that `lbls` is of type `numpy.array`. Here's a fix I propose:

```
@property
def data(self)->Union[FloatTensor, Tuple[FloatTensor,LongTensor]]:
    bboxes,lbls = self._compute_boxes()
    lbls = tensor([o.data for o in lbls])
    return bboxes if lbls is None else (bboxes, lbls)
```

**Comment by nhonth** [comment]
Just made one #1183 .

**Comment by sgugger** [comment]
Closing since it was merged.
