### ISSUE TITLE
RecursionError while processing adult dataset tabular data

### ISSUE THREAD

**Issue by moronito** [fastai/fastai#1197]
**Describe the bug**
A `RecursionError` occurs when processing tabular data with fastai 1.0.26

**To Reproduce**
Follow the tutorial [https://docs.fast.ai/tabular.html#Preprocessing-tabular-data](here). When executing the code `(cat_x,cont_x),y = next(iter(data.train_dl))` the following error occurs:
```
Traceback (most recent call last):
  File "C:\Users\Tommaso\Miniconda3\envs\ai\lib\site-packages\fastai\data_block.py", line 376, in __getattr__
    res = getattr(self.x, k, None)
  File "C:\Users\Tommaso\Miniconda3\envs\ai\lib\site-packages\fastai\data_block.py", line 376, in __getattr__
    res = getattr(self.x, k, None)
  File "C:\Users\Tommaso\Miniconda3\envs\ai\lib\site-packages\fastai\data_block.py", line 376, in __getattr__
    res = getattr(self.x, k, None)
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by sgugger** [comment]
Just ran the notebook without any problem. Please use the [forum](https://forums.fast.ai/) and add a little more information about your hardware and if you made any changes to the code. Thanks!
