### ISSUE TITLE
TypeError from torch when doing model.fit in lesson4-imdb

### ISSUE THREAD

**Issue by NirantK** [fastai/fastai#121]
I am trying to reproduce the code in lesson4-imdb notebook. I ran `conda env update` and the issue still exsits. 

I am running the following cell: 
```python
m3.freeze_to(-1)
m3.fit(lrs/2, 1, metrics=[accuracy])
m3.unfreeze()
m3.fit(lrs, 1, metrics=[accuracy], cycle_len=1)
```

to get the TypeError as mentioned below: 

```javascript
TypeError                                 Traceback (most recent call last)
<ipython-input-58-450637379222> in <module>()
      1 m3.freeze_to(-1)
----> 2 m3.fit(lrs/2, 1, metrics=[accuracy])
      3 m3.unfreeze()
      4 m3.fit(lrs, 1, metrics=[accuracy], cycle_len=1)

~/gandalf/fastai/courses/dl1/fastai/learner.py in fit(self, lrs, n_cycle, wds, **kwargs)
    207         self.sched = None
    208         layer_opt = self.get_layer_opt(lrs, wds)
--> 209         return self.fit_gen(self.model, self.data, layer_opt, n_cycle, **kwargs)
    210 
    211     def warm_up(self, lr, wds=None):

~/gandalf/fastai/courses/dl1/fastai/learner.py in fit_gen(self, model, data, layer_opt, n_cycle, cycle_len, cycle_mult, cycle_save_name, use_clr, metrics, callbacks, use_wd_sched, norm_wds, wds_sched_mult, **kwargs)
    154         n_epoch = sum_geom(cycle_len if cycle_len else 1, cycle_mult, n_cycle)
    155         return fit(model, data, n_epoch, layer_opt.opt, self.crit,
--> 156             metrics=metrics, callbacks=callbacks, reg_fn=self.reg_fn, clip=self.clip, **kwargs)
    157 
    158     def get_layer_groups(self): return self.models.get_layer_groups()

~/gandalf/fastai/courses/dl1/fastai/model.py in fit(model, data, epochs, opt, crit, metrics, callbacks, **kwargs)
    104             i += 1
    105 
--> 106         vals = validate(stepper, data.val_dl, metrics)
    107         if epoch == 0: print(layout.format(*names))
    108         print_stats(epoch, [debias_loss] + vals)

~/gandalf/fastai/courses/dl1/fastai/model.py in validate(stepper, dl, metrics)
    126         preds,l = stepper.evaluate(VV(x), VV(y))
    127         loss.append(to_np(l))
--> 128         res.append([f(preds.data,y) for f in metrics])
    129     return [np.mean(loss)] + list(np.mean(np.stack(res),0))
    130 

~/gandalf/fastai/courses/dl1/fastai/model.py in <listcomp>(.0)
    126         preds,l = stepper.evaluate(VV(x), VV(y))
    127         loss.append(to_np(l))
--> 128         res.append([f(preds.data,y) for f in metrics])
    129     return [np.mean(loss)] + list(np.mean(np.stack(res),0))
    130 

~/gandalf/fastai/courses/dl1/fastai/metrics.py in accuracy(preds, targs)
      8 def accuracy(preds, targs):
      9     preds = torch.max(preds, dim=1)[1]
---> 10     return (preds==targs).float().mean()
     11 
     12 def accuracy_thresh(thresh):

~/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/tensor.py in __eq__(self, other)
    346 
    347     def __eq__(self, other):
--> 348         return self.eq(other)
    349 
    350     def __ne__(self, other):

TypeError: eq received an invalid combination of arguments - got (Variable), but expected one of:
 * (int value)
      didn't match because some of the arguments have invalid types: (Variable)
 * (torch.cuda.LongTensor other)
      didn't match because some of the arguments have invalid types: (Variable)
```

The additional warning before the above error is as follows: 

```javascript
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/nirant/miniconda3/envs/fastai/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/nirant/miniconda3/envs/fastai/lib/python3.6/site-packages/tqdm/_tqdm.py", line 144, in run
    for instance in self.tqdm_cls._instances:
  File "/home/nirant/miniconda3/envs/fastai/lib/python3.6/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

I have insufficient understanding of deep learning to fix this. Is the problem in line 128 of `fastai/models.py`? 

Any assistance or guidance is really appreciated.

**Comment by jph00** [comment]
Fixed now. Thanks for the report
