### ISSUE TITLE
TypeError: an integer is required (got type NoneType) at the end of one cycle

### ISSUE THREAD

**Issue by steffenix** [fastai/fastai#1273]
**Describe the bug**

At the end of one cycle an error is raised.
```
TypeError: an integer is required (got type NoneType)
```

fastai-1.0.31
pytorch 1.0.0.dev20181021

**To Reproduce**

I am trying to enter the whales competition on kaggle. https://www.kaggle.com/c/humpback-whale-identification

This is my really simple notebook so far.

```python
%reload_ext autoreload
%autoreload 2
%matplotlib inline

from fastai import *
from fastai.vision import *
```

```python
bs = 16
```

```python
path = "data/whales"
```

## Data Augmentation

```python
tfms = get_transforms(max_rotate=20, max_zoom=1.3, max_lighting=0.4, max_warp=0.4,
                      p_affine=1., p_lighting=1.)
```

```python
data = ImageDataBunch.from_csv(path=path, folder="train", csv_labels="train.csv", ds_tfms=tfms, size=224, bs=bs)
```

```python
data.show_batch(rows=3, figsize=(10,10))
```

![output_6_0](https://user-images.githubusercontent.com/2143646/49334952-858e9a80-f61d-11e8-8b45-24b646e0503a.png)

```python
len(data.classes),data.c
```

    (4538, 4538)

```python
learn = create_cnn(data, models.resnet34, metrics=error_rate)
```

```python
learn.fit_one_cycle(1)
```

```
 ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-4dfb24161c57> in <module>
----> 1 learn.fit_one_cycle(1)

/opt/anaconda3/lib/python3.6/site-packages/fastai/train.py in fit_one_cycle(learn, cyc_len, max_lr, moms, div_factor, pct_start, wd, callbacks, **kwargs)
     19     callbacks.append(OneCycleScheduler(learn, max_lr, moms=moms, div_factor=div_factor,
     20                                         pct_start=pct_start, **kwargs))
---> 21     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
     22 
     23 def lr_find(learn:Learner, start_lr:Floats=1e-7, end_lr:Floats=10, num_it:int=100, stop_div:bool=True, **kwargs:Any):

/opt/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in fit(self, epochs, lr, wd, callbacks)
    161         callbacks = [cb(self) for cb in self.callback_fns] + listify(callbacks)
    162         fit(epochs, self.model, self.loss_func, opt=self.opt, data=self.data, metrics=self.metrics,
--> 163             callbacks=self.callbacks+callbacks)
    164 
    165     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

/opt/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     92     except Exception as e:
     93         exception = e
---> 94         raise e
     95     finally: cb_handler.on_train_end(exception)
     96 

/opt/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     87             if hasattr(data,'valid_dl') and data.valid_dl is not None and data.valid_ds is not None:
     88                 val_loss = validate(model, data.valid_dl, loss_func=loss_func,
---> 89                                        cb_handler=cb_handler, pbar=pbar)
     90             else: val_loss=None
     91             if cb_handler.on_epoch_end(val_loss): break

/opt/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in validate(model, dl, loss_func, cb_handler, pbar, average, n_batch)
     47     with torch.no_grad():
     48         val_losses,nums = [],[]
---> 49         for xb,yb in progress_bar(dl, parent=pbar, leave=(pbar is not None)):
     50             if cb_handler: xb, yb = cb_handler.on_batch_begin(xb, yb, train=False)
     51             val_losses.append(loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler))

/opt/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in __iter__(self)
     63         self.update(0)
     64         try:
---> 65             for i,o in enumerate(self._gen):
     66                 yield o
     67                 if self.auto_update: self.update(i+1)

/opt/anaconda3/lib/python3.6/site-packages/fastai/basic_data.py in __iter__(self)
     66         "Process and returns items from `DataLoader`."
     67         assert not self.skip_size1 or self.batch_size > 1, "Batch size cannot be one if skip_size1 is set to True"
---> 68         for b in self.dl:
     69             y = b[1][0] if is_listy(b[1]) else b[1]
     70             if not self.skip_size1 or y.size(0) != 1: yield self.proc_batch(b)

/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    635                 self.reorder_dict[idx] = batch
    636                 continue
--> 637             return self._process_next_batch(batch)
    638 
    639     next = __next__  # Python 2 compatibility

/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    656         self._put_indices()
    657         if isinstance(batch, ExceptionWrapper):
--> 658             raise batch.exc_type(batch.exc_msg)
    659         return batch
    660 

TypeError: Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/anaconda3/lib/python3.6/site-packages/fastai/torch_core.py", line 99, in data_collate
    return torch.utils.data.dataloader.default_collate(to_data(batch))
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 223, in default_collate
    return torch.LongTensor(batch)
TypeError: an integer is required (got type NoneType)
```

**Comment by mfruhner** [comment]
Hi,
I got a similar issue with the 'House Price' Kaggle Competition. I posted it on the forums [here](https://forums.fast.ai/t/kernel-interrupt-on-learn-fit/31665), but no one answered yet. 
Weird thing is, that the error varies. Sometimes it will raise 
`TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'NoneType>.`
and sometimes it will show the error mentioned by you. 

Looking forward to a solution!
Greetings,
Maik

**Comment by JTunis** [comment]
Looking at the data it appears that many of the categories only have one or two images. My guess would be that when the data is split for training and validation, all of the images for a respective category may be in the validation set and that may be causing issues.

**Comment by mearex** [comment]
I am also working with exact data set but i am getting IndexError instead of TypeError after one cycle fit. I guess JTunis's guess could be true. This data set have one example for most classes. Here is error: 

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-18-be1ab4476b35> in <module>
----> 1 learn.fit_one_cycle(5, slice(lr))

/opt/anaconda3/lib/python3.6/site-packages/fastai/train.py in fit_one_cycle(learn, cyc_len, max_lr, moms, div_factor, pct_start, wd, callbacks, **kwargs)
     19     callbacks.append(OneCycleScheduler(learn, max_lr, moms=moms, div_factor=div_factor,
     20                                         pct_start=pct_start, **kwargs))
---> 21     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
     22 
     23 def lr_find(learn:Learner, start_lr:Floats=1e-7, end_lr:Floats=10, num_it:int=100, stop_div:bool=True, **kwargs:Any):

/opt/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in fit(self, epochs, lr, wd, callbacks)
    164         callbacks = [cb(self) for cb in self.callback_fns] + listify(callbacks)
    165         fit(epochs, self.model, self.loss_func, opt=self.opt, data=self.data, metrics=self.metrics,
--> 166             callbacks=self.callbacks+callbacks)
    167 
    168     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

/opt/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     92     except Exception as e:
     93         exception = e
---> 94         raise e
     95     finally: cb_handler.on_train_end(exception)
     96 

/opt/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     87             if hasattr(data,'valid_dl') and data.valid_dl is not None and data.valid_ds is not None:
     88                 val_loss = validate(model, data.valid_dl, loss_func=loss_func,
---> 89                                        cb_handler=cb_handler, pbar=pbar)
     90             else: val_loss=None
     91             if cb_handler.on_epoch_end(val_loss): break

/opt/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in validate(model, dl, loss_func, cb_handler, pbar, average, n_batch)
     47     with torch.no_grad():
     48         val_losses,nums = [],[]
---> 49         for xb,yb in progress_bar(dl, parent=pbar, leave=(pbar is not None)):
     50             if cb_handler: xb, yb = cb_handler.on_batch_begin(xb, yb, train=False)
     51             val_losses.append(loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler))

/opt/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in __iter__(self)
     63         self.update(0)
     64         try:
---> 65             for i,o in enumerate(self._gen):
     66                 yield o
     67                 if self.auto_update: self.update(i+1)

/opt/anaconda3/lib/python3.6/site-packages/fastai/basic_data.py in __iter__(self)
     66         "Process and returns items from `DataLoader`."
     67         assert not self.skip_size1 or self.batch_size > 1, "Batch size cannot be one if skip_size1 is set to True"
---> 68         for b in self.dl:
     69             y = b[1][0] if is_listy(b[1]) else b[1]
     70             if not self.skip_size1 or y.size(0) != 1: yield self.proc_batch(b)

/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    635                 self.reorder_dict[idx] = batch
    636                 continue
--> 637             return self._process_next_batch(batch)
    638 
    639     next = __next__  # Python 2 compatibility

/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    656         self._put_indices()
    657         if isinstance(batch, ExceptionWrapper):
--> 658             raise batch.exc_type(batch.exc_msg)
    659         return batch
    660 

IndexError: Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/anaconda3/lib/python3.6/site-packages/fastai/data_block.py", line 480, in __getitem__
    if self.item is None: x,y = self.x[idxs],self.y[idxs]
  File "/opt/anaconda3/lib/python3.6/site-packages/fastai/data_block.py", line 92, in __getitem__
    if isinstance(try_int(idxs), int): return self.get(idxs)
  File "/opt/anaconda3/lib/python3.6/site-packages/fastai/data_block.py", line 329, in get
    return MultiCategory(one_hot(o, self.c), [self.classes[p] for p in o], o)
  File "/opt/anaconda3/lib/python3.6/site-packages/fastai/core.py", line 210, in one_hot
    res[x] = 1.
IndexError: arrays used as indices must be of integer (or boolean) type

```

**Comment by sgugger** [comment]
This issue doesn't really come from fastai AFAICT but more from the way you structure your data: you have labels in your validation set that aren't present in your training set. You shouldn't use a random split for your validation set when dealing with a very unbalanced dataset (like the whale competition), but create your validation set carefully.
I've changed the code so that the error is raised at the creation of the data with a clear message.

**Comment by sariabod** [comment]
I ran into the same issue. Even when I created the train/validation set carefully (I created them at the label level) and it I did not solve the error. Oddly enough, when I tried the same exact thing with from_folder instead of from_csv it worked fine. I am reusing code from other competitions that have worked fine with the csv option (I create the csv file from the folder structure) since from_folder caused me other issues in the past with OOM. Just adding this note in case there is something else to look into.

**Comment by sgugger** [comment]
If you had a minimal repro of the bug in a gist, that would help us fix it!

**Comment by Nilanshrajput** [comment]
I am getting this erroe=while predicting on ds_type=DatasetType.Test, prediction on train and validation set is working fine.

**Comment by dan771** [comment]
i get this error my pygame project:
```
Traceback (most recent call last):
  File "C:\Users\danny_000\OneDrive\Documents\programming\python\pygame\projects\air madness\mainLoop.py", line 30, in <module>
    images.plane(x,y,size)
  File "C:\Users\danny_000\OneDrive\Documents\programming\python\pygame\projects\air madness\images.py", line 24, in plane
    gameDisplay.blit(pygame.transform.scale(plainIMG, (size, size)), (x,y))
TypeError: an integer is required (got type NoneType)
```
my code still works fine though
