### ISSUE TITLE
"fit_one_cycle" was break down

### ISSUE THREAD

**Issue by Bonsen** [fastai/fastai#1347]
Traceback (most recent call last):
  File "resnext.py", line 513, in <module>
    learn.fit_one_cycle(12, max_lr=lrs) 
  File "/home/z/.local/lib/python3.6/site-packages/fastai/train.py", line 20, in fit_one_cycle
    learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
  File "/home/z/.local/lib/python3.6/site-packages/fastai/basic_train.py", line 162, in fit
    callbacks=self.callbacks+callbacks)
  File "/home/z/.local/lib/python3.6/site-packages/fastai/basic_train.py", line 95, in fit
    finally: cb_handler.on_train_end(exception)
  File "/home/z/.local/lib/python3.6/site-packages/fastai/callback.py", line 256, in on_train_end
    self('train_end', exception=exception)
  File "/home/z/.local/lib/python3.6/site-packages/fastai/callback.py", line 187, in __call__
    return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]
  File "/home/z/.local/lib/python3.6/site-packages/fastai/callback.py", line 187, in <listcomp>
    return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]
  File "resnext.py", line 343, in on_train_end
    if self.every=="improvement": learn.load(f'{self.name}')
  File "/home/z/.local/lib/python3.6/site-packages/fastai/basic_train.py", line 204, in load
    self.model.load_state_dict(torch.load(self.path/self.model_dir/f'{name}.pth', map_location=device))
  File "/home/z/anaconda36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Unexpected key(s) in state_dict: "module.0.0.conv2.weight",................

After I ran some epochs, it will break down... (learn.fit_one_cycle(12, max_lr=lrs) )

**Comment by sgugger** [comment]
We can't help without seeing your code. To help to debug your code, please use [the forum](https://forums.fast.ai/). If you're sure it's fastai bug, please include a minimal example of reproduction when you open a new issue.
