### ISSUE TITLE
DataSet requires an `new` method now?

### ISSUE THREAD

**Issue by bosmart** [fastai/fastai#1353]
**Describe the bug**

```
Traceback (most recent call last):
  File "/Users/user/Dropbox/Projects/Python/just_scripts/test.py", line 31, in <module>
    data = ImageDataBunch.create(tr_dataset, val_dataset)
  File "/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py", line 114, in create
    datasets = cls._init_ds(train_ds, valid_ds, test_ds)
  File "/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py", line 104, in _init_ds
    fix_ds = valid_ds.new(train_ds.x, train_ds.y) # train_ds, but without training tfms
AttributeError: 'CustomDataset' object has no attribute 'new'
```

**To Reproduce**
```
from fastai import *
from fastai.vision import *

class CustomDataset(Dataset):
    def __init__(self, data_list): self.data = copy(data_list)

    def __len__(self): return len(self.data)

    def __getitem__(self, idx):
        x1, x2, x3 = self.data[idx]
        return x1, np.array(x2), np.array(x3)

tr_dataset = CustomDataset([1, 2, 3])
val_dataset = CustomDataset([4, 5, 6])
data = ImageDataBunch.create(tr_dataset, val_dataset)
```

**Additional context**
Updated to fastai-nightly today.

**Comment by stas00** [comment]
This has been fixed a few hours ago. `git pull` should take care of this.

**Comment by bosmart** [comment]
Not quite:

```
Traceback (most recent call last):
  File "/tmp/pycharm_project_189/test.py", line 31, in <module>
    data = ImageDataBunch.create(tr_dataset, val_dataset)
  File "../fastai/fastai/basic_data.py", line 117, in create
    return cls(*dls, path=path, device=device, tfms=tfms, collate_fn=collate_fn, no_check=no_check)
TypeError: __init__() missing 1 required positional argument: 'fix_dl'
```

**Comment by fromLittleAcorns** [comment]
I ran into the same problem - the original problem has been solved but it has not moved to the class initiation as above.

**Comment by sgugger** [comment]
Fixed by [this commit](https://github.com/fastai/fastai/commit/834c04c53edc0c6d90a21afe79d71e27ad6e0325).

**Comment by bosmart** [comment]
Nope :(

```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    data = ImageDataBunch.create(tr_dataset, val_dataset)
  File "~/repos/fastai/fastai/basic_data.py", line 117, in create
    return cls(*dls, path=path, device=device, tfms=tfms, collate_fn=collate_fn, no_check=no_check)
  File "~/repos/fastai/fastai/basic_data.py", line 90, in __init__
    if fix_dl is None: fix_dl = train_dl.new(shuffle=False, drop_last=False)
  File "~/repos/fastai/fastai/basic_data.py", line 20, in DataLoader___getattr__
    def DataLoader___getattr__(dl, k:str)->Any: return getattr(dl.dataset, k)
AttributeError: 'CustomDataset' object has no attribute 'new'
```

**Comment by sgugger** [comment]
Sorry, should be fixed now.

**Comment by sgugger** [comment]
It's another one but I pushed a fix. I've documented [here](https://docs.fast.ai/basic_data.html#Using-a-custom-Dataset-in-fastai) what you should expect to work or not work with a pytorch Dataset and what attributes you can implement to help.

**Comment by fromLittleAcorns** [comment]
Thanks thats very helpful.  In several talks Jeremy talks about using pytorch datasets, but after looking into things more I can see that this is only true in some cases and it seems that most require additions, in particular the use of the ItemList.  I was struggling to see how to do all of this and your article helps
