### ISSUE TITLE
check for nulls with TextLMDataBunch

### ISSUE THREAD

**Issue by MichoelSnow** [fastai/fastai#1372]
**Describe the bug**
If any rows in the `text` column are null, TextLMDataBunch throws the following error:
AttributeError: 'float' object has no attribute 'replace'

Obviously the solution would be to not have any null values in the `text` column, but if you do and you don't realize it, this error does not make it clear what the problem with your data is. 

**To Reproduce**

```
train_df = pd.DataFrame({'classes':[1,2,3], 'text':['test1', np.NAN, 'test2']})
valid_df = pd.DataFrame({'classes':[1,2,3], 'text':['test3', 'test4', 'test5']})
data_lm_tmp = TextLMDataBunch.from_df(PATH, train_df=train_df, valid_df=valid_df)
```

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/msnow/miniconda3/envs/cord_comp/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/data/msnow/miniconda3/envs/cord_comp/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/data/msnow/miniconda3/envs/cord_comp/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/data/msnow/miniconda3/envs/cord_comp/lib/python3.6/site-packages/fastai/text/transform.py", line 110, in _process_all_1
    return [self.process_text(t, tok) for t in texts]
  File "/data/msnow/miniconda3/envs/cord_comp/lib/python3.6/site-packages/fastai/text/transform.py", line 110, in <listcomp>
    return [self.process_text(t, tok) for t in texts]
  File "/data/msnow/miniconda3/envs/cord_comp/lib/python3.6/site-packages/fastai/text/transform.py", line 101, in process_text
    for rule in self.pre_rules: t = rule(t)
  File "/data/msnow/miniconda3/envs/cord_comp/lib/python3.6/site-packages/fastai/text/transform.py", line 58, in fix_html
    x = x.replace('#39;', "'").replace('amp;', '&').replace('#146;', "'").replace(
AttributeError: 'float' object has no attribute 'replace'
"""

**Expected behavior**
TextLMDataBunch (or the underlying process) should first check whether there exists any null values and throw an appropriate and informative exception to that effect

**Comment by sgugger** [comment]
This [commit](https://github.com/fastai/fastai/commits/master) should fix it.
