### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by HuShaohanAI** [fastai/fastai#1377]
Traceback (most recent call last):                                                                   
  File "main.py", line 198, in <module>
    learn.fit_one_cycle(1, max_lr=slice(lr))  # sz 256
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/train.py", line 20, in fit_one_cycle
    learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_train.py", line 162, in fit
    callbacks=self.callbacks+callbacks)
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_train.py", line 94, in fit
    raise e
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_train.py", line 82, in fit
    for xb,yb in progress_bar(data.train_dl, parent=pbar):
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 67, in __iter__
    if self.auto_update: self.update(i+1)
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 85, in update
    self.update_bar(val)
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 97, in update_bar
    else: self.on_update(val, f'{100 * val/self.total:.2f}% [{val}/{self.total} {elapsed_t}<{remaining_t}{end}]')
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 256, in on_update
    if printing(): WRITER_FN(to_write, end = '\r')
UnicodeEncodeError: 'ascii' codec can't encode character '\u2588' in position 14: ordinal not in range(128)

What's the problem?How to fix it?

**Comment by sgugger** [comment]
This has been referenced as an issue [here](https://github.com/fastai/fastprogress/issues/21) with a possible fix. It's compeltely linked to fastprogress and not fastai in any case, so please comment on that topic if the fix doesn't work for you (and tell us what your setup is).
