### ISSUE TITLE
apply_tfms() got an unexpected keyword argument 'do_crop'

### ISSUE THREAD

**Issue by mattkrick** [fastai/fastai#1398]
**Describe the bug**
`LabelList.__getitem__` is calling  `Image.apply_tfms` with `do_crop`.
Just for fun, if i add a `**kwargs` params to `apply_tfms`, Then i get a new error about `_crop_pad() missing 1 required positional argument: 'size'`. I don't wanna go changing the API, so I made an issue instead of a PR. 

**To Reproduce**
```
learn = create_cnn(data, models.resnet34, metrics=error_rate)
DatasetFormatter().from_similars(learn, ds_type=DatasetType.Valid)
```

**Expected behavior**
No error

**Env**
python: v3.6.6
pytorch: v1.0.0
fastai: master (62d0401b52873e12d332f6657b0b7be9eb993ce1)

**Stack trace**
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-8a8d23411355> in <module>()
----> 1 ds, idxs = DatasetFormatter().from_similars(learn, ds_type=DatasetType.Valid)

~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/widgets/image_cleaner.py in from_similars(cls, learn, layer_ls, **kwargs)
     35     def from_similars(cls, learn, layer_ls:list=[0, 7, 2], **kwargs):
     36         "Gets the indices for the most similar images in training and validation datasets"
---> 37         train_ds, train_idxs = cls.get_similars_idxs(learn, layer_ls, **kwargs)
     38         return train_ds, train_idxs
     39 

~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/widgets/image_cleaner.py in get_similars_idxs(cls, learn, layer_ls, **kwargs)
     44         dl = learn.data.fix_dl
     45 
---> 46         ds_actns = cls.get_actns(learn, hook=hook, dl=dl, **kwargs)
     47         similarities = cls.comb_similarity(ds_actns, ds_actns, **kwargs)
     48         idxs = cls.sort_idxs(similarities)

~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/widgets/image_cleaner.py in get_actns(learn, hook, dl, pool, pool_dim, **kwargs)
     58         learn.model.eval()
     59         with torch.no_grad():
---> 60             for (xb,yb) in progress_bar(dl):
     61                 learn.model(xb)
     62                 actns.append((hook.stored).cpu())

~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastprogress/fastprogress.py in __iter__(self)
     63         self.update(0)
     64         try:
---> 65             for i,o in enumerate(self._gen):
     66                 yield o
     67                 if self.auto_update: self.update(i+1)

~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_data.py in __iter__(self)
     68     def __iter__(self):
     69         "Process and returns items from `DataLoader`."
---> 70         for b in self.dl:
     71             #y = b[1][0] if is_listy(b[1]) else b[1] # XXX: Why is this line here?
     72             yield self.proc_batch(b)

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    635                 self.reorder_dict[idx] = batch
    636                 continue
--> 637             return self._process_next_batch(batch)
    638 
    639     next = __next__  # Python 2 compatibility

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    656         self._put_indices()
    657         if isinstance(batch, ExceptionWrapper):
--> 658             raise batch.exc_type(batch.exc_msg)
    659         return batch
    660 

TypeError: Traceback (most recent call last):
  File "/home/matt/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/matt/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/matt/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/data_block.py", line 526, in __getitem__
    x = x.apply_tfms(self.tfms, **self.tfmargs)
TypeError: apply_tfms() got an unexpected keyword argument 'do_crop'
```

**Comment by sgugger** [comment]
Thanks for flagging!
