### ISSUE TITLE
Issue when running TextLMDataBunch.from_csv

### ISSUE THREAD

**Issue by raymonduui** [fastai/fastai#1411]
**Describe the bug**
I was following the Quick Start: Training an IMDb sentiment model with ULMFiT from https://docs.fast.ai/text.html

I can run all the commands before

Language model data
data_lm = TextLMDataBunch.from_csv(path, ‘texts.csv’)

**My code**
```
from fastai.text import *
import pandas as pd
from IPython.display import display

path='data/'
filename='news_cleantext.csv'
myfile=path+filename
df = pd.read_csv(path+filename)
display(df.head())



# Language model data
data_lm = TextLMDataBunch.from_csv(path, filename)
# Classifier model data
data_clas = TextClasDataBunch.from_csv(path, filename, vocab=data_lm.train_ds.vocab, bs=32)
data_lm.save()
data_clas.save()
```

**Error Snippet**
```
Traceback (most recent call last):
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\pandas\core\ops.py", line 1012, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\pandas\core\computation\expressions.py", line 205, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\pandas\core\computation\expressions.py", line 120, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\pandas\core\computation\expressions.py", line 65, in _evaluate_standard
    return op(a, b)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\pandas\core\ops.py", line 113, in radd
    return right + left
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U6') dtype('<U6') dtype('<U6')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    data_lm = TextLMDataBunch.from_csv(path, filename)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\fastai\text\data.py", line 182, in from_csv
    label_cols, label_delim, **kwargs)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\fastai\text\data.py", line 167, in from_df
    src = src.label_for_lm() if cls==TextLMDataBunch else src.label_from_df(cols=label_cols, classes=classes, sep=label_delim)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\fastai\data_block.py", line 393, in _inner
    self.process()
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\fastai\data_block.py", line 440, in process
    for i,ds in enumerate(self.lists): ds.process(xp, yp, filter_missing_y=i==0)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\fastai\data_block.py", line 569, in process
    self.x.process(xp)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\fastai\data_block.py", line 68, in process
    for p in self.processor: p.process(self)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\fastai\text\data.py", line 239, in process
    ds.items = _join_texts(ds.items, self.mark_fields)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\fastai\text\data.py", line 326, in _join_texts
    text_col = f'{BOS} {FLD} {1} ' + df[0] if mark_fields else  f'{BOS} ' + df[0]
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\pandas\core\ops.py", line 1069, in wrapper
    result = safe_na_op(lvalues, rvalues)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\pandas\core\ops.py", line 1033, in safe_na_op
    return na_op(lvalues, rvalues)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\pandas\core\ops.py", line 1023, in na_op
    result[mask] = op(x[mask], y)
  File "C:\Users\raymo\Anaconda3\envs\XMLProcessor\lib\site-packages\pandas\core\ops.py", line 113, in radd
    return right + left
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U6') dtype('<U6') dtype('<U6') 
```

**Comment by sgugger** [comment]
This usually happens when the texts aren't properly loaded. Are you sure you have labels in column 0 and texts in column 1 (default)? Otherwise you can pass yours with `text_cols` and `label_cols`.

**Comment by raymonduui** [comment]
@sgugger Thank you for your help! I didn't have my data in correct format. Anywhere can I look at the documentation about text_cols and lable_cols?

**Comment by sgugger** [comment]
On the [doc website](https://docs.fast.ai/text.data.html).

**Comment by rnyak** [comment]
@sgugger In the doc website you shared, it reads as "If there are several label_cols, the labels will be assumed to be one-hot encoded and classes will default to label_cols (you can ignore that argument for a language model).". I have multi-labels, and I one-hot encoded them. In that case, I have multi-columns for labels. I assume, the argument "Are you sure you have labels in column 0 and texts in column 1 (default)?" would not be valid in that case, right?
