### ISSUE TITLE
BrokenProcessPool error when using TextLMDataBunch.from_df

### ISSUE THREAD

**Issue by agarnitin86** [fastai/fastai#1440]
I am trying to run the code given here https://docs.fast.ai/text.html

```
import fastai
from fastai import *
from fastai.text import * 
import pandas as pd
import numpy as np
from functools import partial
import io
import os

path = untar_data(URLs.IMDB_SAMPLE)
# Language model data
data_lm = TextLMDataBunch.from_csv(path, 'texts.csv')
```

I am getting error at last line, i.e.,
```
data_lm = TextLMDataBunch.from_csv(path, 'texts.csv')
```

Traceback (most recent call last):

  File "<ipython-input-11-da609eb33612>", line 13, in <module>
    data_lm = TextLMDataBunch.from_csv(path, 'texts.csv')

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\text\data.py", line 182, in from_csv
    label_cols, label_delim, **kwargs)

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\text\data.py", line 167, in from_df
    src = src.label_for_lm() if cls==TextLMDataBunch else src.label_from_df(cols=label_cols, classes=classes, sep=label_delim)

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\data_block.py", line 393, in _inner
    self.process()

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\data_block.py", line 440, in process
    for i,ds in enumerate(self.lists): ds.process(xp, yp, filter_missing_y=i==0)

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\data_block.py", line 569, in process
    self.x.process(xp)

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\data_block.py", line 68, in process
    for p in self.processor: p.process(self)

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\text\data.py", line 242, in process
    tokens += self.tokenizer.process_all(ds.items[i:i+self.chunksize])

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\text\transform.py", line 116, in process_all
    return sum(e.map(self._process_all_1, partition_by_cores(texts, self.n_cpus)), [])

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\process.py", line 476, in _chain_from_iterable_of_lists
    for element in iterable:

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\_base.py", line 586, in result_iterator
    yield fs.pop().result()

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()

  File "C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
**Installation details**

```
from fastai.utils.show_install import *
show_install()
```
```text
=== Software === 
python       : 3.7.0
fastai       : 1.0.38
fastprogress : 0.1.18
torch        : 1.0.0
torch cuda   : 9.0 / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Windows-7-6.1.7601-SP1
conda env    : Unknown
python       : C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\pythonw.exe
sys.path     : 
C:\Users\nitin.agarwal
C:\Users\nitin.agarwal\Documents\PythonWorkspace\ULMFIT_TextClassification
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\python37.zip
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\DLLs
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\win32
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\win32\lib
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\Pythonwin
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\extensions
C:\Users\nitin.agarwal\.ipython
no supported gpus found on this system
```

**Comment by sgugger** [comment]
Closing since no answer in a while, please reopen to follow-up.
