### ISSUE TITLE
COCO data loading example fails

### ISSUE THREAD

**Issue by benjaminjack** [fastai/fastai#1452]
**COCO data loading example fails**
I'm having issues using ObjectItemList and DataBunch to load images with bounding boxes. The DataLoader object appears to load 0-d tensors at some point and then errors out.

**Provide your installation details**
```text
=== Software === 
python        : 3.7.2
fastai        : 1.0.39
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 410.48
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 12192MB | TITAN X (Pascal)

=== Environment === 
platform      : Linux-4.4.0-141-generic-x86_64-with-debian-stretch-sid
distro        : #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018
conda env     : yolo
python        : /home/ben/miniconda3/envs/yolo/bin/python
sys.path      : /home/ben/yolo/data/pascal/VOCdevkit/VOC2007/JPEGImages
/home/ben/miniconda3/envs/yolo/lib/python37.zip
/home/ben/miniconda3/envs/yolo/lib/python3.7
/home/ben/miniconda3/envs/yolo/lib/python3.7/lib-dynload

/home/ben/miniconda3/envs/yolo/lib/python3.7/site-packages
/home/ben/miniconda3/envs/yolo/lib/python3.7/site-packages/IPython/extensions
/home/ben/.ipython
```

**To Reproduce**
```
from fastai.vision import *

coco = untar_data(URLs.COCO_TINY)
images, lbl_bbox = get_annotations(coco/'train.json')
img2bbox = dict(zip(images, lbl_bbox))
get_y_func = lambda o:img2bbox[o.name]

data = (ObjectItemList.from_folder(coco)
        #Where are the images? -> in coco
        .random_split_by_pct()                          
        #How to split in train/valid? -> randomly with the default 20% in valid
        .label_from_func(get_y_func)
        #How to find the labels? -> use get_y_func
        .transform(get_transforms(), tfm_y=True)
        #Data augmentation? -> Standard transforms with tfm_y=True
        .databunch(bs=16, collate_fn=bb_pad_collate))   
        #Finally we convert to a DataBunch and we use bb_pad_collate

data.sanity_check()

data.show_batch()
```

Then I get this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-08d0dd5c9f7c> in <module>
----> 1 data.show_batch()

~/miniconda3/envs/yolo/lib/python3.7/site-packages/fastai/basic_data.py in show_batch(self, rows, ds_type, **kwargs)
    156     def show_batch(self, rows:int=5, ds_type:DatasetType=DatasetType.Train, **kwargs)->None:
    157         "Show a batch of data in `ds_type` on a few `rows`."
--> 158         x,y = self.one_batch(ds_type, True, True)
    159         if self.train_ds.x._square_show: rows = rows ** 2
    160         xs = [self.train_ds.x.reconstruct(grab_idx(x, i)) for i in range(rows)]

~/miniconda3/envs/yolo/lib/python3.7/site-packages/fastai/basic_data.py in one_batch(self, ds_type, detach, denorm, cpu)
    139         w = self.num_workers
    140         self.num_workers = 0
--> 141         try:     x,y = next(iter(dl))
    142         finally: self.num_workers = w
    143         if detach: x,y = to_detach(x,cpu=cpu),to_detach(y,cpu=cpu)

~/miniconda3/envs/yolo/lib/python3.7/site-packages/fastai/basic_data.py in __iter__(self)
     68     def __iter__(self):
     69         "Process and returns items from `DataLoader`."
---> 70         for b in self.dl: yield self.proc_batch(b)
     71 
     72     @classmethod

~/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    635                 self.reorder_dict[idx] = batch
    636                 continue
--> 637             return self._process_next_batch(batch)
    638 
    639     next = __next__  # Python 2 compatibility

~/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    656         self._put_indices()
    657         if isinstance(batch, ExceptionWrapper):
--> 658             raise batch.exc_type(batch.exc_msg)
    659         return batch
    660 

TypeError: Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ben/miniconda3/envs/yolo/lib/python3.7/site-packages/fastai/vision/data.py", line 42, in bb_pad_collate
    max_len = max([len(s[1].data[1]) for s in samples])
  File "/home/ben/miniconda3/envs/yolo/lib/python3.7/site-packages/fastai/vision/data.py", line 42, in <listcomp>
    max_len = max([len(s[1].data[1]) for s in samples])
  File "/home/ben/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/tensor.py", line 411, in __len__
    raise TypeError("len() of a 0-d tensor")
TypeError: len() of a 0-d tensor
```
**Expected behavior**
Display a batch of COCO images with bounding boxes.

**Additional context**
I've had this also happen with the PASCAL data set. Sometimes several batches will load just fine, but eventually they'll fail giving errors about 0-d tensors.

**Comment by sgugger** [comment]
I just pushed a fix but I'm not too sure it will work since I don't have the bug and your code snippet doesn't reproduce it for me. Thinking it comes from pytorch that doesn't want to give a length to tensors with only a scalar, so I put labels as numpy arrays.

**Comment by benjaminjack** [comment]
Thanks for looking into this!

It just occurred to me now this error might being caused by random augmentations affecting bounding boxes and then padding. I’ll try to do some testing with a fixed random seed to reproduce the error and then see if your fix resolves it.
