### ISSUE TITLE
ImageItemList path is distorted when calling fit_one_cycle()/lr_find() etc

### ISSUE THREAD

**Issue by jiata** [fastai/fastai#1530]
**Describe the bug**
I want to create an `DataBunch` using the `ImageItemList` and the `from_df()` function.

As you can see, it seems to work as i am able to `show_batch()`:
![image](https://user-images.githubusercontent.com/16616215/51829767-3fbc1e80-22bc-11e9-9f1d-c6f08ac0829f.png)

I also run `data.sanity_check()` to make sure that the underlying data can be properly loaded when learning, and no errors are thrown. I also run `data.path`, which for me equals `PosixPath('/mnt/data/met/etching')`

However, when i get to trying to fit my model using `fit_one_cycle()`, it is unable to load the data because the path to the data is slightly distorted. I get an error when i run the following (taken from planet notebook of course v3):
```python
arch = models.resnet50
acc_02 = partial(accuracy_thresh, thresh=0.2)
f_score = partial(fbeta, thresh=0.2)
learn = create_cnn(data, arch, metrics=[acc_02, f_score])
learn.fit_one_cycle(1) # this line throws the error below
```

Error:
```
OSError: Traceback (most recent call last):
  File "/home/jiata/anaconda3/envs/xxx/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jiata/anaconda3/envs/xxx/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jiata/anaconda3/envs/xxx/lib/python3.7/site-packages/fastai/data_block.py", line 564, in __getitem__
    if self.item is None: x,y = self.x[idxs],self.y[idxs]
  File "/home/jiata/anaconda3/envs/xxx/lib/python3.7/site-packages/fastai/data_block.py", line 94, in __getitem__
    if isinstance(idxs, numbers.Integral): return self.get(idxs)
  File "/home/jiata/anaconda3/envs/xxx/lib/python3.7/site-packages/fastai/vision/data.py", line 273, in get
    res = self.open(fn)
  File "/home/jiata/anaconda3/envs/xxx/lib/python3.7/site-packages/fastai/vision/data.py", line 269, in open
    return open_image(fn, convert_mode=self.convert_mode)
  File "/home/jiata/anaconda3/envs/xxx/lib/python3.7/site-packages/fastai/vision/image.py", line 383, in open_image
    x = PIL.Image.open(fn).convert(convert_mode)
  File "/home/jiata/anaconda3/envs/xxx/lib/python3.7/site-packages/PIL/Image.py", line 2687, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/mnt/data/met/etching/./736898.jpg'
```

Essentially, it breaks because it adds a `/./` between the data path and the string written in the dataframe.  Either an error should be thrown when creating the dataset or running `fit_one_cycle()` should not add the `/./` in the path.

I personally think it should just join the data.path with the string it finds in the dataframe...

**Provide your installation details**
```
=== Software ===
python        : 3.7.1
fastai        : 1.0.42
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 410.73
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Hardware ===
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 16130MB | Tesla V100-PCIE-16GB

=== Environment ===
platform      : Linux-4.15.0-1036-azure-x86_64-with-debian-buster-sid
distro        : #38-Ubuntu SMP Fri Dec 7 02:47:47 UTC 2018
conda env     : cvbp
python        : /home/jiata/anaconda3/envs/cvbp/bin/python
sys.path      : /home/jiata/learn/fastai/course-v3/nbs/dl1
/home/jiata/anaconda3/envs/cvbp/lib/python37.zip
/home/jiata/anaconda3/envs/cvbp/lib/python3.7
/home/jiata/anaconda3/envs/cvbp/lib/python3.7/lib-dynload
/home/jiata/.local/lib/python3.7/site-packages
/home/jiata/anaconda3/envs/cvbp/lib/python3.7/site-packages
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Fixed, but I think your bug may lay elsewhere, as I never had a problem with those additional dots.
