### ISSUE TITLE
.get_preds() on TabularList gives AttributeError: 'TabularList' object has no attribute 'codes'

### ISSUE THREAD

**Issue by JoshVarty** [fastai/fastai#1623]
**Describe the bug**
Using `.get_preds()` on tabular data results in:
```
AttributeError: Traceback (most recent call last):
  File "/home/josh/anaconda3/envs/nlpenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/josh/anaconda3/envs/nlpenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/josh/anaconda3/envs/nlpenv/lib/python3.7/site-packages/fastai/data_block.py", line 593, in __getitem__
    if self.item is None: x,y = self.x[idxs],self.y[idxs]
  File "/home/josh/anaconda3/envs/nlpenv/lib/python3.7/site-packages/fastai/data_block.py", line 103, in __getitem__
    if isinstance(idxs, Integral): return self.get(idxs)
  File "/home/josh/anaconda3/envs/nlpenv/lib/python3.7/site-packages/fastai/tabular/data.py", line 125, in get
    codes = [] if self.codes is None else self.codes[o]
AttributeError: 'TabularList' object has no attribute 'codes'
```

**Provide your installation details**

```text
=== Software === 
python        : 3.7.2
fastai        : 1.0.43
fastprogress  : 0.1.19
torch         : 1.0.0
nvidia driver : 410.93
torch cuda    : 10.0.130 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 12194MB | TITAN Xp

=== Environment === 
platform      : Linux-4.15.0-45-generic-x86_64-with-debian-buster-sid
distro        : #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
conda env     : Unknown
python        : /home/josh/anaconda3/envs/nlpenv/bin/python3
sys.path      : /home/josh/git/fastai/docs_src
/home/josh/anaconda3/envs/nlpenv/lib/python37.zip
/home/josh/anaconda3/envs/nlpenv/lib/python3.7
/home/josh/anaconda3/envs/nlpenv/lib/python3.7/lib-dynload

/home/josh/anaconda3/envs/nlpenv/lib/python3.7/site-packages
/home/josh/anaconda3/envs/nlpenv/lib/python3.7/site-packages/IPython/extensions
/home/josh/.ipython
```

**To Reproduce**
Running the inference steps of [`Inference Learner: Tabular`](https://docs.fast.ai/tutorial.inference.html#Tabular) but using `.get_preds()` instead of predicting on a single row with `.predict()`.

```Python
from fastai.tabular import *

adult = untar_data(URLs.ADULT_SAMPLE)
df = pd.read_csv(adult/'adult.csv')
dep_var = 'salary'
cat_names = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']
cont_names = ['education-num', 'hours-per-week', 'age', 'capital-loss', 'fnlwgt', 'capital-gain']
procs = [FillMissing, Categorify, Normalize]

data = (TabularList.from_df(df, path=adult, cat_names=cat_names, cont_names=cont_names, procs=procs)
                           .split_by_idx(valid_idx=range(800,1000))
                           .label_from_df(cols=dep_var)
                           .databunch())

learn = tabular_learner(data, layers=[200,100], metrics=accuracy)
learn.fit(1, 1e-2)
learn.save('mini_train')
learn.export()

#Now try to use this model to predict on the entire adults.csv file

tabList = TabularList(df, cat_names=cat_names, cont_names=cont_names, procs=procs)
learner = load_learner(adult, test=tabList)

#Works
learner.predict(df.iloc[0])
#Fails
learner.get_preds(ds_type=DatasetType.Test)
```

**Expected behavior**
I expect `.get_preds()` to return the output tensors for the entire model as it does for the **Vision** portion of the tutorial.

**Comment by sgugger** [comment]
This is subtle but the bug is in your code: you need to create your test `ItemList` with the factory method `from_df` (since you're using a `DataFrame`). Do
```
tabList = TabularList.from_df(df, cat_names=cat_names, cont_names=cont_names, procs=procs)
```
and it will work.
