### ISSUE TITLE
text_classifier_learner out of memory on small IMBD sample dataset

### ISSUE THREAD

**Issue by sivakhno** [fastai/fastai#1752]
**Describe the bug**
I get an unexpected error when running fastai example dataset on Amazon p2.xlarge instance - all the information below. Any suggestions would be appreciated! 
path = untar_data(URLs.IMDB_SAMPLE)
data = TextClasDataBunch.from_csv(path, 'texts.csv')
learn = text_classifier_learner(data, AWD_LSTM, drop_mult=0.5,pretrained=True)

```text
>>> learn.fit(1)
epoch     train_loss  valid_loss  accuracy  time    
Traceback (most recent call last):                                                                                                                                                     
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py", line 182, in fit
    callbacks=self.callbacks+callbacks)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fastai/utils/mem.py", line 86, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py", line 92, in fit
    loss = loss_batch(model, xb, yb, loss_func, opt, cb_handler)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py", line 24, in loss_batch
    out = model(*xb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fastai/text/learner.py", line 234, in forward
    r, o = self.module(input[:,i: min(i+self.bptt, sl)])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fastai/text/models/awd_lstm.py", line 113, in forward
    raw_output, new_h = rnn(raw_output, self.hidden[l])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fastai/text/models/awd_lstm.py", line 49, in forward
    return self.module.forward(*args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 179, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 98.38 MiB (GPU 0; 11.17 GiB total capacity; 10.59 GiB already allocated; 90.56 MiB free; 169.94 MiB cached)
```

**Provide your installation details**
```text
=== Software === 
python        : 3.6.8
fastai        : 1.0.46
fastprogress  : 0.1.20
torch         : 1.0.0
nvidia driver : 396.26
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.4.0-1075-aws-x86_64-with-debian-stretch-sid
distro        : #85-Ubuntu SMP Thu Jan 17 17:15:12 UTC 2019
conda env     : Unknown
python        : /usr/bin/python
sys.path      : 
/home/ubuntu/anaconda3/lib/python36.zip
/home/ubuntu/anaconda3/lib/python3.6
/home/ubuntu/anaconda3/lib/python3.6/lib-dynload
/home/ubuntu/anaconda3/lib/python3.6/site-packages
/home/ubuntu/anaconda3/lib/python3.6/site-packages/IPython/extensions
```

**To Reproduce**
path = untar_data(URLs.IMDB_SAMPLE)
data = TextClasDataBunch.from_csv(path, 'texts.csv')
learn = text_classifier_learner(data, AWD_LSTM, drop_mult=0.5,pretrained=True)

**Expected behavior**
As dataset is tiny (800 records) we should not expect memory error

**Comment by sgugger** [comment]
It's not a problem of general RAM but GPU RAM. This has nothing to do with your dataset, you should reduce your batch size by passing bs=... in the call to `TextClasDataBunch`

**Comment by aeamaea** [comment]
I was getting this error in the quick_start notebook in the paperspace/fastai container in the TextDataLoaders.from_folder with the IMDB dataset with a 1070ti card (8GB). I changed the batchsize (bs=16) and it doesn't run out of memory, though it's a bit slow.

TextDataLoaders.from_folder(<all the other, previous args>, bs=16)
