### ISSUE TITLE
resize_method=ResizeMethod.PAD throws error

### ISSUE THREAD

**Issue by odysseus0** [fastai/fastai#1765]
**Describe the bug**
Running `transform(size=n, resize_method=ResizeMethod.Pad)` will throw tensor dimension mismatch error.

**Provide your installation details**
```text
=== Software === 
python        : 3.7.1
fastai        : 1.0.46
fastprogress  : 0.1.20
torch         : 1.0.1.post2
nvidia driver : 410.72
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 16130MB | Tesla V100-SXM2-16GB

=== Environment === 
platform      : Linux-4.9.0-8-amd64-x86_64-with-debian-9.8
distro        : #1 SMP Debian 4.9.130-2 (2018-10-27)
conda env     : base
python        : /opt/anaconda3/bin/python
sys.path      : /home/jupyter/MURA
/opt/anaconda3/lib/python37.zip
/opt/anaconda3/lib/python3.7
/opt/anaconda3/lib/python3.7/lib-dynload

/opt/anaconda3/lib/python3.7/site-packages
/opt/anaconda3/lib/python3.7/site-packages/IPython/extensions
/home/jupyter/.ipython
```

**To Reproduce**
Here is a [notebook](https://github.com/odysseus0/MURA/blob/master/MURA.ipynb). If you change the `resize_method=ResizeMethod.SQUISH` to `resize_method=ResizeMethod.PAD`, and then run through the remaining codes, you will get an error.

**Comment by sgugger** [comment]
As always, please give the full stack trace when filing an issue. I don't think this in fastai but probably in PyTorch's pad function: with the default padding mode of reflect, and the fact you have very narrow images, I think it breaks (it can't reflect more than once the image).
Test with `padding_mode = zeros` for instance.

**Comment by odysseus0** [comment]
Here we go.

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-56-ee99c62a182b> in <module>
----> 1 data.show_batch(rows=2)

/opt/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py in show_batch(self, rows, ds_type, **kwargs)
    179     def show_batch(self, rows:int=5, ds_type:DatasetType=DatasetType.Train, **kwargs)->None:
    180         "Show a batch of data in `ds_type` on a few `rows`."
--> 181         x,y = self.one_batch(ds_type, True, True)
    182         n_items = rows **2 if self.train_ds.x._square_show else rows
    183         if self.dl(ds_type).batch_size < n_items: n_items = self.dl(ds_type).batch_size

/opt/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py in one_batch(self, ds_type, detach, denorm, cpu)
    162         w = self.num_workers
    163         self.num_workers = 0
--> 164         try:     x,y = next(iter(dl))
    165         finally: self.num_workers = w
    166         if detach: x,y = to_detach(x,cpu=cpu),to_detach(y,cpu=cpu)

/opt/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py in __iter__(self)
     73     def __iter__(self):
     74         "Process and returns items from `DataLoader`."
---> 75         for b in self.dl: yield self.proc_batch(b)
     76 
     77     @classmethod

/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    635                 self.reorder_dict[idx] = batch
    636                 continue
--> 637             return self._process_next_batch(batch)
    638 
    639     next = __next__  # Python 2 compatibility

/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    656         self._put_indices()
    657         if isinstance(batch, ExceptionWrapper):
--> 658             raise batch.exc_type(batch.exc_msg)
    659         return batch
    660 

RuntimeError: Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/anaconda3/lib/python3.7/site-packages/fastai/data_block.py", line 607, in __getitem__
    x = x.apply_tfms(self.tfms, **self.tfmargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/fastai/vision/image.py", line 122, in apply_tfms
    x = tfm(x, size=_get_crop_target(size,mult=mult), padding_mode=padding_mode)
  File "/opt/anaconda3/lib/python3.7/site-packages/fastai/vision/image.py", line 514, in __call__
    return self.tfm(x, *args, **{**self.resolved, **kwargs}) if self.do_run else x
  File "/opt/anaconda3/lib/python3.7/site-packages/fastai/vision/image.py", line 461, in __call__
    if args: return self.calc(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/fastai/vision/image.py", line 466, in calc
    if self._wrap: return getattr(x, self._wrap)(self.func, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/fastai/vision/image.py", line 172, in pixel
    self.px = func(self.px, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/fastai/vision/transform.py", line 191, in _crop_pad
    return f_crop_pad(x, size, padding_mode, row_pct, col_pct)
  File "/opt/anaconda3/lib/python3.7/site-packages/fastai/vision/transform.py", line 174, in _crop_pad_default
    x = F.pad(x[None], (col_pad,col_pad,row_pad,row_pad), mode=padding_mode)[0]
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2685, in pad
    ret = torch._C._nn.reflection_pad2d(input, pad)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (46, 46) at dimension 3 of input [1, 3, 128, 36]
```

**Comment by sgugger** [comment]
Yes, that's exactly the error I was thinking of. Issue is on PyTorch with reflection padding. Pass another `padding_mode`.

**Comment by odysseus0** [comment]
So maybe before PyTorch fixes this problem, we should set the default `padding_mode` to something other than reflection padding.

**Comment by sgugger** [comment]
No, that is the best default for vision problems as it gives better results consistently... but you shouldn't use it if you want to resize with padding and have very rectangular images.

**Comment by odysseus0** [comment]
Got it.  Many thanks.

**Comment by stas00** [comment]
Could you guys please document this here:
https://docs.fast.ai/vision.transform.html#resize
or here:
https://docs.fast.ai/vision.image.html#ResizeMethod
whichever is more applicable - and a link to the pytorch issue if there is such, so that we know when it gets fixed?

Thanks.

**Comment by odysseus0** [comment]
About the `padding_mode` argument:

There does not seem to be official API documentation about it. It is clearly explained in the general introduction, but maybe people would still have difficulties looking for it?
