### ISSUE TITLE
show_batch() function fails with 'NameError: name 'get_ipython' is not defined' error

### ISSUE THREAD

**Issue by jhoxray** [fastai/fastai#1864]
Environment output:

```text
=== Software ===
python        : 3.7.2
fastai        : 1.0.50.post1
fastprogress  : 0.1.20
torch         : 1.0.1
torch cuda    : 9.0 / is available
torch cudnn   : 7005 / is enabled

=== Hardware ===
torch devices : 1
  - gpu0      : Quadro M2000M

=== Environment ===
platform      : Windows-10-10.0.17134-SP0
conda env     : Unknown
python        : C:\Users\aantich\AppData\Local\Programs\Python\Python37\python.exe
sys.path      : C:\Users\aantich\ai\course-v3\nbs\dl1
C:\Users\aantich\AppData\Local\Programs\Python\Python37\python37.zip
C:\Users\aantich\AppData\Local\Programs\Python\Python37\DLLs
C:\Users\aantich\AppData\Local\Programs\Python\Python37\lib
C:\Users\aantich\AppData\Local\Programs\Python\Python37
C:\Users\aantich\AppData\Local\Programs\Python\Python37\lib\site-packages
no nvidia-smi is found
```

When I try to run tutorial.data notebook from the fastai tutorial, everything works fine until the line `data.show_batch()` which fails with the following error message in the jupyter server console:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\aantich\appdata\local\programs\python\python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\users\aantich\appdata\local\programs\python\python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "c:\users\aantich\appdata\local\programs\python\python37\lib\site-packages\fastai\vision\__init__.py", line 1, in <module>
    from .. import basics
  File "c:\users\aantich\appdata\local\programs\python\python37\lib\site-packages\fastai\basics.py", line 1, in <module>
    from .basic_train import *
  File "c:\users\aantich\appdata\local\programs\python\python37\lib\site-packages\fastai\basic_train.py", line 6, in <module>
    from .utils.ipython import gpu_mem_restore
  File "c:\users\aantich\appdata\local\programs\python\python37\lib\site-packages\fastai\utils\ipython.py", line 27, in <module>
    IS_IN_COLAB = is_in_colab()
  File "c:\users\aantich\appdata\local\programs\python\python37\lib\site-packages\fastai\utils\ipython.py", line 24, in is_in_colab
    if IS_IN_IPYTHON and ipython_is_colab(): return True
  File "c:\users\aantich\appdata\local\programs\python\python37\lib\site-packages\fastai\utils\ipython.py", line 22, in ipython_is_colab
    return get_ipython().__class__.__module__ == 'google.colab._shell'
NameError: name 'get_ipython' is not defined
```
I get the same issue with lesson1 notebook from the course.fast.ai series - everything runs fine, dataset loads, etc - but show_batch() fails with the same error message -- `get_ipython is not defined`

Any pointers on how to fix this? Thanks a lot!

**Comment by sgugger** [comment]
Yes this bug has been fixed, you should do an editable install before the next release.
