### ISSUE TITLE
Language model training fails when distributed on multiple GPUs

### ISSUE THREAD

**Issue by ctoth** [fastai/fastai#1866]
**Describe the bug**

When fitting a language model on a single GPU the library works fine. When I rent a server from vast.AI with 2 GPUs and do the steps outlined in distributed.md to distribute training the library fails with the following error:

## Error
```text
Traceback (most recent call last):
  File "pylearner.py", line 72, in <module>
    learner.fit_one_cycle(10, 1e-2, moms=(0.9, 0.8))
  File "/root/fastai/fastai/train.py", line 22, in fit_one_cycle
    learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
  File "/root/fastai/fastai/basic_train.py", line 196, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "/root/fastai/fastai/basic_train.py", line 105, in fit
    cb_handler=cb_handler, pbar=pbar)
  File "/root/fastai/fastai/basic_train.py", line 56, in validate
    for xb,yb in progress_bar(dl, parent=pbar, leave=(pbar is not None)):
  File "/opt/conda/lib/python3.7/site-packages/fastprogress/fastprogress.py", line 66, in __iter__
    for i,o in enumerate(self._gen):
  File "/root/fastai/fastai/basic_data.py", line 75, in __iter__
    for b in self.dl: yield self.proc_batch(b)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/root/fastai/fastai/text/data.py", line 77, in __getitem__
    self.ro[j],self.ri[j] = self.fill_row(not self.backwards, self.dataset.x.items, self.idx, self.batch[j],
  File "/root/fastai/fastai/text/data.py", line 40, in __getattr__
    def __getattr__(self,k:str)->Any: return getattr(self.dataset, k)
  File "/root/fastai/fastai/data_block.py", line 627, in __getattr__
    raise AttributeError(k)
AttributeError: batch
```

## Single GPU Code

```python

from io import StringIO
import os
import tokenize_py
from typing import *
from pathlib import Path
import subprocess
os.environ['FOR_DISABLE_CONSOLE_CTRL_HANDLER'] = 'T'

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--local_rank", type=int, default=0)
args = parser.parse_args()

import torch
#torch.cuda.set_device(args.local_rank)
torch.distributed.init_process_group(backend='nccl', init_method='env://')

from fastai.distributed import *
from fastai.text.transform import BaseTokenizer, Tokenizer
from fastai.text import *
from fastai.text import data
import numpy

BS=192
numpy.random.seed(2)
path = Path('lib')


class PythonTokenizer(BaseTokenizer):

    def tokenizer(self, t:str) -> List[str]:
        if (not os.path.exists(t)):
            f = StringIO()
            f.write(t)
            f.seek(0)
        else:
            f = io.open(t, 'rt')
        try:
            res = list(tokenize_py.tokenize_file(f))
        except Exception:
            res = ''
        return res

class Tokenizer(Tokenizer):

    def __init__(self, tok_func:Callable=PythonTokenizer, *args, **kwargs):
        kwargs['pre_rules'] = []
        kwargs['post_rules'] = []
        super().__init__(tok_func=tok_func, lang='py', *args, **kwargs)

def load_new():
  processors = data._get_processor(min_freq=1, max_vocab=100000, tokenizer=Tokenizer(), include_bos=False)
  loaded = (TextList.from_folder(
    path, extensions={'.py', '.pyw'}, recurse=False,
    processor = processors,
    )
    .split_by_rand_pct(0.1)
    .label_for_lm()
    .databunch(bs=BS)
  )
  loaded.save()
  return loaded

def load_cached():
  return load_data(path, 'python.data', bs=BS)

def create_learner(data):
  learner = language_model_learner(data, AWD_LSTM, drop_mult=0.6).to_fp16()
  # learner = learner.to_distributed(args.local_rank)
  return learner

if __name__ == '__main__':
  data = load_new()
  learner = create_learner(data)
  learner.fit_one_cycle(10, 1e-2, moms=(0.9, 0.8))
  learner.save('python1.model')
  learner.unfreeze()
  learner.fit_one_cycle(15, 1e-2)
  learner.save('python2.model')


```
## Multi-GPU Code

```python
from io import StringIO
import os
import tokenize_py
from typing import *
from pathlib import Path
import subprocess
os.environ['FOR_DISABLE_CONSOLE_CTRL_HANDLER'] = 'T'

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--local_rank", type=int, default=0)
args = parser.parse_args()

import torch
torch.cuda.set_device(args.local_rank)
torch.distributed.init_process_group(backend='nccl', init_method='env://')

from fastai.distributed import *
from fastai.text.transform import BaseTokenizer, Tokenizer
from fastai.text import *
from fastai.text import data
import numpy

BS=192
numpy.random.seed(2)
path = Path('lib')


class PythonTokenizer(BaseTokenizer):

    def tokenizer(self, t:str) -> List[str]:
        if (not os.path.exists(t)):
            f = StringIO()
            f.write(t)
            f.seek(0)
        else:
            f = io.open(t, 'rt')
        try:
            res = list(tokenize_py.tokenize_file(f))
        except Exception:
            res = ''
        return res

class Tokenizer(Tokenizer):

    def __init__(self, tok_func:Callable=PythonTokenizer, *args, **kwargs):
        kwargs['pre_rules'] = []
        kwargs['post_rules'] = []
        super().__init__(tok_func=tok_func, lang='py', *args, **kwargs)

def load_new():
  processors = data._get_processor(min_freq=1, max_vocab=100000, tokenizer=Tokenizer(), include_bos=False)
  loaded = (TextList.from_folder(
    path, extensions={'.py', '.pyw'}, recurse=False,
    processor = processors,
    )
    .split_by_rand_pct(0.1)
    .label_for_lm()
    .databunch(bs=BS)
  )
  loaded.save()
  return loaded

def load_cached():
  return load_data(path, 'python.data', bs=BS)

def create_learner(data):
  learner = language_model_learner(data, AWD_LSTM, drop_mult=0.6).to_fp16()
  learner = learner.to_distributed(args.local_rank)
  return learner

if __name__ == '__main__':
  data = load_new()
  learner = create_learner(data)
  learner.fit_one_cycle(10, 1e-2, moms=(0.9, 0.8))
  learner.save('python1.model')
  learner.unfreeze()
  learner.fit_one_cycle(15, 1e-2)
  learner.save('python2.model')



**Provide your installation details**



```text
=== Software === 
python        : 3.7.1
fastai        : 1.0.51.dev0
fastprogress  : 0.1.20
torch         : 1.0.1
nvidia driver : 415.27
torch cuda    : 10.0.130 / is available
torch cudnn   : 7301 / is enabled

=== Hardware === 
nvidia gpus   : 2
torch devices : 2
  - gpu0      : 11177MB | GeForce GTX 1080 Ti
  - gpu1      : 11178MB | GeForce GTX 1080 Ti

=== Environment === 
platform      : Linux-4.15.0-46-generic-x86_64-with-debian-stretch-sid
distro        : #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019
conda env     : Unknown
python        : /opt/conda/bin/python
sys.path      : /root
/opt/conda/lib/python37.zip
/opt/conda/lib/python3.7
/opt/conda/lib/python3.7/lib-dynload
/opt/conda/lib/python3.7/site-packages
/root/fastai
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Should be fixed in master now, thanks for flagging!
