### ISSUE TITLE
Inconsistent error message

### ISSUE THREAD

**Issue by andrew2hart** [fastai/fastai#1946]
fastai produces two error messages on same code
```
$ python train.py
epoch     train_loss  valid_loss  fbeta     time    
0         0.727754    0.474158    0.784632  00:05                                                                                        
1         0.550880    0.352218    0.855628  00:05                                                                                        
2         0.483986    0.356164    0.878644  00:05                                                                                        
Total time: 00:17
1 misclassified samples over 20 samples in the validation set.                                                         
Traceback (most recent call last):
  File "train.py", line 28, in <module>
    inter.plot_multi_top_losses(2)
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/fastai/vision/learner.py", line 192, in _cl_int_plot_multi_top_losses
    for clas in infolist[ordlosses_idxs[sampleN]][2]:
IndexError: list index out of range
```

```
$ python train.py
epoch     train_loss  valid_loss  fbeta     time    
0         0.735465    0.528597    0.765152  00:05                                                                                        
1         0.570213    0.325392    0.843507  00:05                                                                                        
2         0.471445    0.287134    0.854004  00:05                                                                                        
Total time: 00:17
1 misclassified samples over 20 samples in the validation set.                                                         
Traceback (most recent call last):
  File "train.py", line 28, in <module>
    inter.plot_multi_top_losses(2)
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/fastai/vision/learner.py", line 189, in _cl_int_plot_multi_top_losses
    mismatchescontainer.append(mismatches_ordered_byloss[ima][0])
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/fastai/data_block.py", line 636, in __getitem__
    if self.item is None: x,y = self.x[idxs],self.y[idxs]
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/fastai/data_block.py", line 109, in __getitem__
    if isinstance(idxs, Integral): return self.get(idxs)
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/fastai/vision/data.py", line 269, in get
    fn = super().get(i)
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/fastai/data_block.py", line 66, in get
    return self.items[i]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

```
from fastai.vision import *
from fastai import *
import matplotlib.pyplot as plt

data = ImageDataBunch.from_csv("./fastdata", ds_tfms=get_transforms(),padding_mode='border',size=112,bs=16,label_delim=" " )

learn = cnn_learner(data, models.resnet50, metrics=fbeta)

learn.fit_one_cycle(3, max_lr=1e-3 )

learn.save("initial")

inter=ClassificationInterpretation.from_learner(learn)
inter.plot_multi_top_losses()   #putting 1 here fixes issue
plt.show()
```

```text
=== Software === 
python       : 3.7.1
fastai       : 1.0.51
fastprogress : 0.1.20
torch        : 1.0.1.post2
torch cuda   : 10.0.130 / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Linux-4.18.0-17-generic-x86_64-with-debian-buster-sid
distro       : #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019
conda env    : base
python       : /home/andrew/anaconda3/bin/python
sys.path     : /home/andrew/gunthreat
/home/andrew/anaconda3/lib/python37.zip
/home/andrew/anaconda3/lib/python3.7
/home/andrew/anaconda3/lib/python3.7/lib-dynload
/home/andrew/.local/lib/python3.7/site-packages
/home/andrew/anaconda3/lib/python3.7/site-packages
no supported gpus found on this system
```

**Comment by sgugger** [comment]
It looks like you only have 1 mismatch, which is why the method fails when you ask for 3 of them (that's the default). This is also why it works when you pass (1). Will add a check about that number.
