### ISSUE TITLE
AssertionError: can only join a child process

### ISSUE THREAD

**Issue by 4everoptimistic** [fastai/fastai#1990]
**Describe the bug**
This happens intermittently (2 out of three times) and I believe it is related to multiprocessing.

Stepping through course-v3/nbs/dl1/lesson1-pets.ipynb notebook error stops the process when running  data.show_batch() and learn.fit_one_cycle(4)

I have installed the latest version of fastai

AssertionError: can only join a child process
[Errno 9] Bad file descriptor
```
xception ignored in: <function _DataLoaderIter.__del__ at 0x7f52a2e06158>
Traceback (most recent call last):
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f52a2e06158>
    self._shutdown_workers()
Traceback (most recent call last):
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
    w.join()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/process.py", line 138, in join
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
AssertionError: can only join a child process
Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f52a2e06158>
Traceback (most recent call last):
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f52a2e06158>
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
Traceback (most recent call last):
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    w.join()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
    self._shutdown_workers()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f52a2e06158>
Traceback (most recent call last):
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/process.py", line 138, in join
Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f52a2e06158>
Traceback (most recent call last):
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f52a2e06158>
Traceback (most recent call last):
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f52a2e06158>
Traceback (most recent call last):
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Exception ignored in: Traceback (most recent call last):
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
<function _DataLoaderIter.__del__ at 0x7f52a2e06158>
Traceback (most recent call last):
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
Traceback (most recent call last):
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/queues.py", line 232, in _feed
    close()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/connection.py", line 177, in close
    self._close()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/connection.py", line 361, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
    self._shutdown_workers()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 704, in _shutdown_workers
    self.worker_result_queue.close()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/queues.py", line 134, in close
    self._reader.close()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/connection.py", line 177, in close
    self._close()
  File "/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/multiprocessing/connection.py", line 361, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor'''

```
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-05989c41c533> in <module>
----> 1 data.show_batch(rows=2, figsize=(7,6))

~/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/fastai/basic_data.py in show_batch(self, rows, ds_type, reverse, **kwargs)
    183     def show_batch(self, rows:int=5, ds_type:DatasetType=DatasetType.Train, reverse:bool=False, **kwargs)->None:
    184         "Show a batch of data in `ds_type` on a few `rows`."
--> 185         x,y = self.one_batch(ds_type, True, True)
    186         if reverse: x,y = x.flip(0),y.flip(0)
    187         n_items = rows **2 if self.train_ds.x._square_show else rows

~/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/fastai/basic_data.py in one_batch(self, ds_type, detach, denorm, cpu)
    166         w = self.num_workers
    167         self.num_workers = 0
--> 168         try:     x,y = next(iter(dl))
    169         finally: self.num_workers = w
    170         if detach: x,y = to_detach(x,cpu=cpu),to_detach(y,cpu=cpu)

~/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/fastai/basic_data.py in __iter__(self)
     73     def __iter__(self):
     74         "Process and returns items from `DataLoader`."
---> 75         for b in self.dl: yield self.proc_batch(b)
     76 
     77     @classmethod

~/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    629         while True:
    630             assert (not self.shutdown and self.batches_outstanding > 0)
--> 631             idx, batch = self._get_batch()
    632             self.batches_outstanding -= 1
    633             if idx != self.rcvd_idx:

~/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _get_batch(self)
    599             while self.pin_memory_thread.is_alive():
    600                 try:
--> 601                     return self.data_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
    602                 except queue.Empty:
    603                     continue

~/anaconda3/envs/fastaiv1/lib/python3.7/queue.py in get(self, block, timeout)
    177                     if remaining <= 0.0:
    178                         raise Empty
--> 179                     self.not_empty.wait(remaining)
    180             item = self._get()
    181             self.not_full.notify()

~/anaconda3/envs/fastaiv1/lib/python3.7/threading.py in wait(self, timeout)
    298             else:
    299                 if timeout > 0:
--> 300                     gotit = waiter.acquire(True, timeout)
    301                 else:
    302                     gotit = waiter.acquire(False)

~/anaconda3/envs/fastaiv1/lib/python3.7/site-packages/torch/utils/data/dataloader.py in handler(signum, frame)
    272         # This following call uses `waitid` with WNOHANG from C side. Therefore,
    273         # Python can still get and update the process status successfully.
--> 274         _error_if_any_worker_fails()
    275         if previous_handler is not None:
    276             previous_handler(signum, frame)

RuntimeError: DataLoader worker (pid 3123) is killed by signal: Illegal instruction.
```

**Provide your installation details**
```text
=== Software === 
python        : 3.7.3
fastai        : 1.0.52.dev0
fastprogress  : 0.1.21
torch         : 1.0.1.post2
nvidia driver : 410.66
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 7951MB | GeForce RTX 2070

=== Environment === 
platform      : Linux-4.18.0-17-generic-x86_64-with-debian-buster-sid
distro        : Ubuntu 18.04 bionic
conda env     : fastaiv1
python        : /home/oos/anaconda3/envs/fastaiv1/bin/python
sys.path      : 
/home/oos/anaconda3/envs/fastaiv1/lib/python37.zip
/home/oos/anaconda3/envs/fastaiv1/lib/python3.7
/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/lib-dynload
/home/oos/anaconda3/envs/fastaiv1/lib/python3.7/site-packages

Thu Apr 18 18:47:41 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.66       Driver Version: 410.66       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   38C    P8    27W / 225W |    795MiB /  7951MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1248      G   /usr/lib/xorg/Xorg                           106MiB |
|    0      1534      G   /usr/bin/gnome-shell                          81MiB |
|    0      3089      C   .../oos/anaconda3/envs/fastaiv1/bin/python   603MiB |
+-----------------------------------------------------------------------------+

```

-->

**To Reproduce**
Stepping through course-v3/nbs/dl1/lesson1-pets.ipynb notebook this happens when running 
data.show_batch() and learn.fit_one_cycle(4)

**Comment by sgugger** [comment]
It's always hard to know exactly what's going on with multiprocessing. You can try to set `defaults.cpu` to a lower value and see if the bug persists?
Not sure this is linked to what's happening in fastai, I think it's a more generic python problem.

**Comment by 4everoptimistic** [comment]
I've reduced defaults.cpu all the way down to 1 and the error still occurs.

I found this error in the forum. Not sure if it is related.
[https://forums.fast.ai/t/exception-ignored-in-bound-method-dataloaderiter-del-of/34081/3](https://forums.fast.ai/t/exception-ignored-in-bound-method-dataloaderiter-del-of/34081/3)

**Comment by sgugger** [comment]
I forgot you have to pass `num_workers=1` when creating your `DataBunch` to remove the multiprocessing. The post you link to seems to say it's a bug in PyTorch, maybe open an issue there?

**Comment by 4everoptimistic** [comment]
num_workers=1 does not solve the issue. I will try and raise the issue with PyTorch.

**Comment by sgugger** [comment]
Thinking again, you said you had the issue with `data.show_batch()`. There is no multiprocessing there, we deactivate it in this function. You shouldn't have those errors there, are you sure your copy of the dataset isn't corrupted in some way?

**Comment by 4everoptimistic** [comment]
It might be corrupt data. I've run the dogs_cats example successfully. This would also explain why it is only working intermittently.

**Comment by Hagenov** [comment]
I am experiencing the same issue. I am able to create a custom ItemList, split, label, train and then create a databunch but whenever I try use `.one_batch()`  it threw the error 

> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 36 and 47 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:711

This led me to dive further into collating the batch where I tried to return it through

```
class MixedTabularDataBunch(DataBunch):
    @classmethod
    def create(cls, train_ds, valid_ds, test_ds=None, path:PathOrStr='.', bs=64, 
               pad_idx=1, pad_first=True, no_check:bool=False, **kwargs) -> DataBunch:
        
        # calls an above collate padding method 
        collate_fn = partial(mixed_tabular_pad_collate, pad_idx=pad_idx, pad_first=pad_first)

        return super().create(train_ds, valid_ds, test_ds, path=path, bs=bs, **kwargs).

```

Then, when I try to reconstruct the databunch I got the above `'AssertionError: can only join a child process' error mentioned`, and this:

> /usr/local/lib/python3.6/dist-packages/fastai/basic_data.py:269: UserWarning: It's not possible to collate samples of your dataset together in a batch.
  warn(message)

It will not let me input any of the super() arguments `num_workers=num_workers`,  `device=device`, `tfms=tfms` or `collate_fn=collate_fn` into my classmethod return, and without specifyingthe collate_fn it doesn't seem to do it manually

**Comment by RylanSchaeffer** [comment]
Did anyone ever find the cause of the problem?
