### ISSUE TITLE
learn.recorder.plot() fails in command line

### ISSUE THREAD

**Issue by teletautala** [fastai/fastai#2025]
**Describe the bug**
When I run learn.recorder.plot() from the command line I get the error: 
```text
Traceback (most recent call last):
  File "./tabular_fastai.py", line 193, in <module>
    learn.recorder.plot()
  File "/home/daniel/.local/lib/python3.6/site-packages/fastai/basic_train.py", line 540, in plot
    if not IN_NOTEBOOK: plot_sixel(fig)
  File "/home/daniel/.local/lib/python3.6/site-packages/fastai/sixel.py", line 16, in plot_sixel
    raise Exception('Error: `libsixel` is needed. See https://github.com/saitoha/libsixel')
Exception: Error: `libsixel` is needed. See https://github.com/saitoha/libsixel
```

**Provide your installation details**
```text
=== Software === 
python        : 3.6.7
fastai        : 1.0.51
fastprogress  : 0.1.21
torch         : 1.0.1.post2
nvidia driver : 390.116
torch cuda    : 9.0.176 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 2002MB | Quadro K2200M

=== Environment === 
platform      : Linux-4.18.0-17-generic-x86_64-with-Ubuntu-18.10-cosmic
distro        : Ubuntu 18.10 Cosmic Cuttlefish
conda env     : Unknown
python        : /usr/bin/python3
sys.path      : 
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/daniel/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
```

**To Reproduce**
I ran this from the command line.
```
from fastai.tabular import *

# This is where to get the data
path = untar_data(URLs.ADULT_SAMPLE)

# This will read the data into memory
df = pd.read_csv(path/'adult.csv')

# This is the dependant variable or the variable we are trying to predict
dep_var = 'salary'

# These are the desired category names in the dataset
cat_names = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race']

# These are the continuous variables or those that could be a decimal
cont_names = ['age', 'fnlwgt', 'education-num']

# These are the preprocessing functions that will be performed
procs = [FillMissing, Categorify, Normalize]

data = (TabularList.from_df(df, path=path, cat_names=cat_names, cont_names=cont_names, procs=procs)
                           .split_by_idx(list(range(800,1000)))
                           .label_from_df(cols=dep_var)
                           .add_test(test)
                           .databunch())

learn = tabular_learner(data, layers=[200,100], metrics=accuracy)
learn.fit(2, 1e-2)
learn.lr_find()
learn.recorder.plot()
```

**Expected behavior**
I expected a chart to show up like when I use matplotlib's
```
plt.show()
```
The above opens a standalone widget and displays the chart.

**Comment by sgugger** [comment]
As the error indicates, you need libsixel installed to display graphics in command line. See [here](https://github.com/saitoha/libsixel) to install.

**Comment by teletautala** [comment]
I installed libsixel1:
```
daniel@099dtaualii:SuccessMetrics$ sudo aptitude install libsixel1
The following NEW packages will be installed:
  libsixel1 
0 packages upgraded, 1 newly installed, 0 to remove and 127 not upgraded.
Need to get 0 B/93.0 kB of archives. After unpacking 431 kB will be used.
Selecting previously unselected package libsixel1:amd64.
(Reading database ... 366968 files and directories currently installed.)
Preparing to unpack .../libsixel1_1.8.2-1_amd64.deb ...
Unpacking libsixel1:amd64 (1.8.2-1) ...
Processing triggers for libc-bin (2.28-0ubuntu1) ...
Setting up libsixel1:amd64 (1.8.2-1) ...
Processing triggers for libc-bin (2.28-0ubuntu1) ...
```
Then ran my code again:
```                                         
daniel@099dtaualii:SuccessMetrics$ ./tabular_fastai.py 
epoch     train_loss  valid_loss  accuracy  time    
0         0.343621    0.335889    0.850000  00:03                                                                                                      
epoch     train_loss  valid_loss  accuracy  time    
0         1.646899    #na#        00:00                                                                                                              
LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.
Traceback (most recent call last):
  File "./tabular_fastai.py", line 64, in <module>
    learn.recorder.plot_lr()
  File "/home/daniel/.local/lib/python3.6/site-packages/fastai/basic_train.py", line 509, in plot_lr
    if not IN_NOTEBOOK: plot_sixel(fig)
  File "/home/daniel/.local/lib/python3.6/site-packages/fastai/sixel.py", line 16, in plot_sixel
    raise Exception('Error: `libsixel` is needed. See https://github.com/saitoha/libsixel')
Exception: Error: `libsixel` is needed. See https://github.com/saitoha/libsixel
```
and still get the error.  What do I do now?

**Comment by sgugger** [comment]
You get this error because `libsixel = try_import('libsixel')` returns None, so your fastai can't import it. I'd double check it's in your environment to make sure you have it there. If it's there and if you can't import libsixel after an install, it seems to me the problem lies in libsixel and you should file an issue toward them.

**Comment by teletautala** [comment]
I installed libsixel-python 
```
pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org libsixel-python
```
and it no longer gives me the error, but there is no plot.

**Comment by sgugger** [comment]
Ah progress! Your terminal must support sixel, so double-check if the one you're using does or not and maybe change the application you're using.
In any case, you can always get your figure with
```
fig = learn.recorder.plot(return_fig=True)
```
then save it somewhere.

**Comment by teletautala** [comment]
I have to install xterm and run
```xterm -ti vt340```
in order to see the graph.  This is great, and I hope more terminals support this in the near future. 
 Thanks for your help.

**Comment by sgugger** [comment]
Np, glad you have it working now!

**Comment by gcp** [comment]
Is it possible to make this a soft failure or make it only generate a warning or something? There don't appear to be binaries for libsixel for Windows, in any case pip install libsixel-python won't install them, and this makes existing scripts suddenly error out when updating fastai. I'm not even using any of the sixel features, so why should it fail in the first place?

**Comment by sgugger** [comment]
Lakes sense. Done in [this commit](https://github.com/fastai/fastai/commit/74ff274773ef20d7611cffd08c57b1143a07058d).
