### ISSUE TITLE
ImageDataBunch.load_empty() is broken

### ISSUE THREAD

**Issue by trackq** [fastai/fastai#2029]
### Running this code
```python
data = ImageDataBunch.load_empty('./models')
model = cnn_learner(data, models.resnet34)
model = load_learner("./models")
```

### Results in this
```
Traceback (most recent call last):
  File "app.py", line 19, in <module>
    data = ImageDataBunch.load_empty('./models', model_name)
  File ".local/share/virtualenvs/simple-fruits-PPb9oZHn/lib/python3.7/site-packages/fastai/data_block.py", line 739, in _databunch_load_empty
    sd = LabelLists.load_empty(path, fn=fname)
  File ".local/share/virtualenvs/simple-fruits-PPb9oZHn/lib/python3.7/site-packages/fastai/data_block.py", line 574, in load_empty
    return LabelLists.load_state(path, state)
  File ".local/share/virtualenvs/simple-fruits-PPb9oZHn/lib/python3.7/site-packages/fastai/data_block.py", line 565, in load_state
    train_ds = LabelList.load_state(path, state)
  File ".local/share/virtualenvs/simple-fruits-PPb9oZHn/lib/python3.7/site-packages/fastai/data_block.py", line 678, in load_state
    x = state['x_cls']([], path=path, processor=state['x_proc'], ignore_empty=True)
KeyError: 'x_cls'
```

# Solution
Pass the correct object (model.data) instead of the whole model.

**Comment by sgugger** [comment]
`ImageDataBunch.load_empty` takes the result of `ImageDataBunch.export`, not `Learner.export`.

**Comment by trackq** [comment]
My bad, thanks for the response!
