### ISSUE TITLE
error plotting in console in libsixel.sixel_dither_initialize

### ISSUE THREAD

**Issue by radekosmulski** [fastai/fastai#2177]
I compiled libsixel with Python interface (checked from Python that it works). I can also display pngs in mlterm okay using img2sixel.

When I run the following script:

```Python
from fastai.vision import *
from fastai.script import *
from torch import nn
from fastai.metrics import top_k_accuracy

path = untar_data(URLs.CIFAR)
data = ImageDataBunch.from_folder(path, valid='test')

class block(nn.Module):
    def __init__(self, n_in, n_out, two_d=True):
        super().__init__()
        self.op = nn.Conv2d(n_in, n_out, 3) if two_d else nn.Linear(n_in, n_out)
        self.bn = nn.BatchNorm2d(n_out) if two_d else nn.BatchNorm1d(n_out)
    def forward(self, x):
        x = self.op(x)
        x = F.relu(x)
        x = self.bn(x)
        return x

arch = SequentialEx(
    block(3,32),
    block(32,32),
    nn.MaxPool2d(2),
    block(32,32),
    block(32,32),
    nn.MaxPool2d(2),
    Flatten(),
    block(800, 800, False),
    block(800, 800, False),
    nn.Linear(800, 10)
)

def top_3_accuracy(preds, targs): return top_k_accuracy(preds, targs, 3)

learn = Learner(data, arch, metrics=[accuracy, top_3_accuracy])

@call_parse
def train(
        epochs: Param("Number of epochs to train", int)=1,
        max_lr: Param("Maximum lr for one cycle", float)=1e-3
        ):
    learn.lr_find()
    learn.recorder.plot()

    learn.fit_one_cycle(epochs, max_lr)

    learn.recorder.plot_losses()

    loss, top_1, top_3 = learn.validate()
    learn.save(f'{epochs}_{max_lr}_{loss:.2f}_{top_1:.2f}_{top_3:.2f}')
```
I get the following error:

```
epoch     train_loss  valid_loss  accuracy  top_3_accuracy  time
0         9.234042    #na#        00:01
LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.
Traceback (most recent call last):
  File "train_on_CIFAR10.py", line 40, in <module>
    max_lr: Param("Maximum lr for one cycle", float)=1e-3
  File "/home/radek/workspace/fastai/fastai/script.py", line 40, in call_parse
    func(**args.__dict__)
  File "train_on_CIFAR10.py", line 43, in train
    learn.recorder.plot()
  File "/home/radek/workspace/fastai/fastai/basic_train.py", line 556, in plot
    if not IN_NOTEBOOK: plot_sixel(fig)
  File "/home/radek/workspace/fastai/fastai/sixel.py", line 21, in plot_sixel
    res = _sixel_encode(fig.canvas.buffer_rgba(), fig.get_figwidth()* dpi, fig.get_figheight() * dpi)
  File "/home/radek/workspace/fastai/fastai/sixel.py", line 10, in _sixel_encode
    libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
  File "/home/radek/anaconda3/envs/fastai/lib/python3.7/site-packages/libsixel_python-0.5.0-py3.7.egg/libsixel/__init__.py", line 506, in sixel_dither_initialize
    quality_mode)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Comment by sgugger** [comment]
Ok, you're the second person to have that error now (see #2170)
I put a minimal example there that doesn't use fastai at all. Can you see if you manage to somehow make it work? I'm unsure if this is a bug in our code or libsixel.

**Comment by jph00** [comment]
Is this in ITerm2?

**Comment by radekosmulski** [comment]
I am using mlterm on Ubuntu 18.04 desktop (I tried both compiling it from source and installing a package using `sudo apt install mlterm`. I compiled libsixel from https://github.com/saitoha/libsixel master with the following command `./configure --enable-python --prefix=/usr/local` but I also had to install through `python setup.py install`. I am using Anaconda and Python 3.7.

When I try to run the minimal example from #2170 I get the following error:
```
Traceback (most recent call last):
  File "min_example.py", line 30, in <module>
    plot_sixel(fig)
  File "min_example.py", line 21, in plot_sixel
    res = _sixel_encode(fig.canvas.buffer_rgba(), fig.get_figwidth()* dpi, fig.get_figheight() * dpi)
  File "min_example.py", line 10, in _sixel_encode
    libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
  File "/home/radek/anaconda3/envs/fastai/lib/python3.7/site-packages/libsixel_python-0.5.0-py3.7.egg/libsixel/__init__.py", line 506, in sixel_dither_initialize
    quality_mode)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```
`img2sixel` from mlterm works though.

I came across [PySixel](https://github.com/saitoha/PySixel). I created a new conda env with python 3.6. I installed PySixel and ran `python setup.py install` in the libsixel repo IIRC. After this change, both the minimal example from #2170 passes and I can also plot from fastai.

**Comment by radekosmulski** [comment]
Steps to be able to plot to console using fastai on Ubuntu 18.04 desktop/

You need Python 3.6, this will not work with 3.7. To create a new conda env with Python 3.6 execute the following `conda create -n py36 python=3.6 anaconda`. You can activate it by running `source activate py36`. Make sure you have fastai installed in the new env. 

```
git clone git@github.com:saitoha/libsixel.git
cd libsixel/
./configure --enable-python --prefix=/usr/local
sudo make install
cd python
python setup.py install

cd ../..
git clone git@github.com:saitoha/PySixel.git
cd PySixel
python setup.py install

sudo apt install mlterm
```

Run `mlterm`. From under it you should now be able to run the following [script](https://gist.github.com/radekosmulski/54dc35136133cfceb67aded2004d18c2) and plots should appear in console.
```

**Comment by Ontheroad123** [comment]
is there any other ways to solve this problem?my computer system is centos,can't install mlterm
