### ISSUE TITLE
Error(s) in loading state_dict for SequentialRNN:

### ISSUE THREAD

**Issue by ahmed-shariff** [fastai/fastai#2246]
**Describe the bug**
Saving and loading the language model results in a error due to mismatch of keys. The stderr output:
```
Traceback (most recent call last):
  File "test.py", line 54, in <module>
    learn.load(path)
  File "/home/amsha/virtualenv/torch-1.0-20190604/lib/python3.7/site-packages/fastai/basic_train.py", line 279, in load
    get_model(self.model).load_state_dict(state, strict=strict)
  File "/home/amsha/virtualenv/torch-1.0-20190604/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SequentialRNN:
	Missing key(s) in state_dict: "0.encoder.weight", "0.encoder_dp.emb.weight", "0.rnns.0.weight_hh_l0_raw", "0.rnns.0.module.weight_ih_l0", "0.rnns.0.module.weight_hh_l0", "0.rnns.0.module.bias_ih_l0", "0.rnns.0.module.bias_hh_l0", "0.rnns.1.weight_hh_l0_raw", "0.rnns.1.module.weight_ih_l0", "0.rnns.1.module.weight_hh_l0", "0.rnns.1.module.bias_ih_l0", "0.rnns.1.module.bias_hh_l0", "0.rnns.2.weight_hh_l0_raw", "0.rnns.2.module.weight_ih_l0", "0.rnns.2.module.weight_hh_l0", "0.rnns.2.module.bias_ih_l0", "0.rnns.2.module.bias_hh_l0", "1.decoder.weight", "1.decoder.bias". 
	Unexpected key(s) in state_dict: "encoder.weight", "encoder_dp.emb.weight", "rnns.0.weight_hh_l0_raw", "rnns.0.module.weight_ih_l0", "rnns.0.module.weight_hh_l0", "rnns.0.module.bias_ih_l0", "rnns.0.module.bias_hh_l0", "rnns.1.weight_hh_l0_raw", "rnns.1.module.weight_ih_l0", "rnns.1.module.weight_hh_l0", "rnns.1.module.bias_ih_l0", "rnns.1.module.bias_hh_l0", "rnns.2.weight_hh_l0_raw", "rnns.2.module.weight_ih_l0", "rnns.2.module.weight_hh_l0", "rnns.2.module.bias_ih_l0", "rnns.2.module.bias_hh_l0". 
```

**Provide your installation details**
`python -m fastai.utils.show_install`
```text
=== Software === 
python        : 3.7.3
fastai        : 1.0.55
fastprogress  : 0.1.21
torch         : 1.1.0
nvidia driver : 418.56
torch cuda    : 10.0.130 / is available
torch cudnn   : 7501 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 2002MB | GeForce GTX 1050

=== Environment === 
platform      : Linux-5.0.5-arch1-1-ARCH-x86_64-with-arch
distro        : Arch Linux  
conda env     : Unknown
python        : /home/amsha/virtualenv/torch-1.0-20190604/bin/python
sys.path      : /media/Files/Research/experiments
/home/amsha/virtualenv/torch-1.0-20190604/lib/python37.zip
/home/amsha/virtualenv/torch-1.0-20190604/lib/python3.7
/home/amsha/virtualenv/torch-1.0-20190604/lib/python3.7/lib-dynload
/usr/lib64/python3.7
/usr/lib/python3.7
/home/amsha/virtualenv/torch-1.0-20190604/lib/python3.7/site-packages
/usr/lib/python3.7/site-packages
/usr/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg
/usr/lib/python3.7/site-packages
```

**To Reproduce**
https://gist.github.com/ahmed-shariff/5bc93da82f9dc541cc4981db20b45f5b

**Comment by ahmed-shariff** [comment]
This is embarrassing. I had used `load` instead of `load_encoder`. Closing issue.
