### ISSUE TITLE
Calling learn.get_preds and then learn.fit throws RuntimeError when using mixup

### ISSUE THREAD

**Issue by fhopfmueller** [fastai/fastai#2316]
**Describe the bug**
Minimal example:

```
from fastai import *
from fastai.vision import *

path = untar_data(URLs.MNIST_SAMPLE)
data = ImageDataBunch.from_folder(path)
learn = cnn_learner(data, models.resnet18, metrics=accuracy).mixup()

val_preds, val_y, val_losses = learn.get_preds(with_loss=True, ds_type = DatasetType.Valid)

learn.fit(1)
```

throws
```
Traceback (most recent call last):                                               
  File "bug.py", line 13, in <module>
    learn.fit(1)
  File "/home/florian/miniconda3/envs/mymlenv/lib/python3.7/site-packages/fastai/basic_train.py", line 202, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "/home/florian/miniconda3/envs/mymlenv/lib/python3.7/site-packages/fastai/basic_train.py", line 100, in fit
    xb, yb = cb_handler.on_batch_begin(xb, yb)
  File "/home/florian/miniconda3/envs/mymlenv/lib/python3.7/site-packages/fastai/callback.py", line 279, in on_batch_begin
    self('batch_begin', mets = not self.state_dict['train'])
  File "/home/florian/miniconda3/envs/mymlenv/lib/python3.7/site-packages/fastai/callback.py", line 251, in __call__
    for cb in self.callbacks: self._call_and_update(cb, cb_name, **kwargs)
  File "/home/florian/miniconda3/envs/mymlenv/lib/python3.7/site-packages/fastai/callback.py", line 241, in _call_and_update
    new = ifnone(getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs), dict())
  File "/home/florian/miniconda3/envs/mymlenv/lib/python3.7/site-packages/fastai/callbacks/mixup.py", line 29, in on_batch_begin
    new_target = torch.cat([last_target[:,None].float(), y1[:,None].float(), lambd[:,None].float()], 1)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 2 and 3 at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/generic/THCTensorMath.cu:62
```
Maybe related to https://github.com/fastai/fastai/issues/2233 .

**Installation**
```text
=== Software === 
python        : 3.7.3
fastai        : 1.0.57
fastprogress  : 0.1.21
torch         : 1.1.0
nvidia driver : 430.40
torch cuda    : 10.0.130 / is available
torch cudnn   : 7501 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 2002MB | GeForce MX150

=== Environment === 
platform      : Linux-5.0.0-25-generic-x86_64-with-debian-buster-sid
distro        : #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019
conda env     : mymlenv
python        : /home/florian/miniconda3/envs/mymlenv/bin/python
sys.path      : /home/florian/code/1909_fastai_bug
/home/florian/miniconda3/envs/mymlenv/lib/python37.zip
/home/florian/miniconda3/envs/mymlenv/lib/python3.7
/home/florian/miniconda3/envs/mymlenv/lib/python3.7/lib-dynload
/home/florian/miniconda3/envs/mymlenv/lib/python3.7/site-packages
```
The bug is also there on master, installed via `pip install git+https://github.com/fastai/fastai/` on a clean conda env.

**Comment by sgugger** [comment]
Thanks for flagging, should be fixed now.
