### ISSUE TITLE
AttributeError: 'TextList' object has no attribute 'sep'

### ISSUE THREAD

**Issue by lz-chen** [fastai/fastai#2367]
My installation
python        : 3.7.4
fastai        : 1.0.58
fastprogress  : 0.1.21
torch         : 1.2.0
nvidia driver : 410.79
torch cuda    : 10.0.130 / is available
torch cudnn   : 7602 / is enabled

An error occurred when I run 
```
classifier_data = load_data(data_folder, classifier_data_filename, bs=batch_size)
```
Error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/suite.py", line 163, in _handleClassSetUp
    setUpClass()
  File "/home/liah/Documents/lc-exabel/python/exabel/nlp/tests/sentiment_model/test_train_sentiment_model.py", line 118, in setUpClass
    self.sentiment_model = SentimentModel(sentiment_data)
  File "/home/liah/Documents/lc-exabel/python/exabel/nlp/sentiment_model/train_sentiment_model.py", line 161, in __init__
    bs=train_data.batch_size)
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/basic_data.py", line 281, in load_data
    collate_fn=collate_fn, no_check=no_check, **kwargs)
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/data_block.py", line 550, in databunch
    num_workers=num_workers, dl_tfms=dl_tfms, device=device, collate_fn=collate_fn, no_check=no_check, **kwargs)
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/text/data.py", line 272, in create
    return cls(*dataloaders, path=path, device=device, dl_tfms=dl_tfms, collate_fn=collate_fn, no_check=no_check)
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/basic_data.py", line 100, in __init__
    if not no_check: self.sanity_check()
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/basic_data.py", line 250, in sanity_check
    idx = next(iter(self.train_dl.batch_sampler))
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/text/data.py", line 119, in __iter__
    sort_idx = np.concatenate([sorted(s, key=self.key, reverse=True) for s in ck_idx])
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/text/data.py", line 119, in <listcomp>
    sort_idx = np.concatenate([sorted(s, key=self.key, reverse=True) for s in ck_idx])
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/text/data.py", line 265, in <lambda>
    train_sampler = SortishSampler(datasets[0].x, key=lambda t: len(datasets[0][t][0].data), bs=bs)
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/data_block.py", line 651, in __getitem__
    if self.item is None: x,y = self.x[idxs],self.y[idxs]
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/data_block.py", line 120, in __getitem__
    if isinstance(idxs, Integral): return self.get(idxs)
  File "/home/liah/.local/share/virtualenvs/python-RNKCJeUC/lib/python3.7/site-packages/fastai/text/data.py", line 330, in get
    return o if self.vocab is None else Text(o, self.vocab.textify(o, self.sep))
AttributeError: 'TextList' object has no attribute 'sep'
```

When I debug this, it seems that `TextList` class was not initialized through calling `__init__()` so `self.sep` was not set by `self.vocab,self.pad_idx,self.sep = vocab,pad_idx,sep`. 
At `return o if self.vocab is None else Text(o, self.vocab.textify(o, self.sep))`, I see that the `self.vocab` and `self.pad_idx` are set, but `self.sep` is not. I am not sure why is this.

**Comment by sgugger** [comment]
`TestList` has a sep attribute though it has been added in a recent version. I'm thinking you are trying to load some data that was saved with an older version since I can't reproduce the bug on my side.
Just reprocess your data with the same version and you shouldn't have any problem.

**Comment by lz-chen** [comment]
That was indeed the issue. Thanks @sgugger !
