### ISSUE TITLE
Unet distributed training

### ISSUE THREAD

**Issue by sbhonde1** [fastai/fastai#2395]
Hi I am new to fastai. I am trying to run UNet as described in lesson 3 part 1 for my custom dataset. I am successfully able to run and get the result on single GPU. However now I am trying to use distributed training approach for the same and I get following error.

> File "UNet_benchmark.py", line 98, in <module>
learn.fit_one_cycle(2, slice(lr), pct_start=0.9)
File “/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/train.py”, line 23, in fit_one_cycle
learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
File “/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/basic_train.py”, line 200, in fit
fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
File “/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/basic_train.py”, line 106, in fit
cb_handler=cb_handler, pbar=pbar)
File “/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/basic_train.py”, line 63, in validate
if cb_handler and cb_handler.on_batch_end(val_losses[-1]): break
File “/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/callback.py”, line 308, in on_batch_end
self(‘batch_end’, call_mets = not self.state_dict[‘train’])
File “/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/callback.py”, line 250, in call
for met in self.metrics: self._call_and_update(met, cb_name, **kwargs)
File “/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/callback.py”, line 241, in call_and_update
new = ifnone(getattr(cb, f’on{cb_name}’)(**self.state_dict, **kwargs), dict())
File “/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/callback.py”, line 347, in on_batch_end
dist.all_reduce(val, op=dist.ReduceOp.SUM)
File “/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py”, line 831, in all_reduce
work = _default_pg.allreduce([tensor], opts)
RuntimeError: Only CUDA dense tensor is supported for NCCL collective operations

Following is the accuracy function I am using

    def iou(y_pred, y_true):
        code = name2id['sidewalk'] + 1
        y_true = y_true.squeeze(1)
        y_true = y_true == code
        y_pred = y_pred.argmax(dim=1)
        y_pred = y_pred == code
        intersection = y_true & y_pred
        union = y_true | y_pred
        iou_score = (torch.sum(intersection).item() + smooth) / (torch.sum(union).item() + smooth)
        return tensor(iou_score)
I am using this reference : https://docs.fast.ai/distributed.html

        learn = unet_learner(data, models.resnet34, metrics=metrics, wd=wd)
        learn.callback_fns.append(partial(LearnerTensorboardWriter,
             base_dir=tboard_path,
             name='exp frozen encoder'))
         learn = learn.to_distributed(args.local_rank)

**Comment by yshvrdhn** [comment]
I am facing the exact issue. Probably @sgugger might be able to shed some insight ?

**Comment by sgugger** [comment]
Your metric should return a tensor (remove the `.item()`) because otherwise, it can't be accumulated over all the processes of your distributed training.

**Comment by yshvrdhn** [comment]
@sgugger I tried your suggestions I am not getting the following error 
```epoch     train_loss  valid_loss  accuracy  iou_curb  time
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/vision/models/unet.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if ssh != up_out.shape[-2:]:
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/vision/models/unet.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if ssh != up_out.shape[-2:]:
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/vision/models/unet.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if ssh != up_out.shape[-2:]:
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/vision/models/unet.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if ssh != up_out.shape[-2:]:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/callbacks/tensorboard.py", line 234, in _queue_processor
    request.write()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/callbacks/tensorboard.py", line 424, in write
    self.tbwriter.add_graph(model=self.model, input_to_model=self.input_to_model)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorboardX/writer.py", line 520, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 96, in graph
    torch.onnx._optimize_trace(trace, torch._C._onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/__init__.py", line 42, in _optimize_trace
    trace.set_graph(utils._optimize_graph(trace.graph(), operator_export_type))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/utils.py", line 155, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/__init__.py", line 52, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/utils.py", line 504, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 88, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 88, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 45, in _parse_arg
    raise RuntimeError("ONNX symbolic expected a constant value in the trace")
RuntimeError: ONNX symbolic expected a constant value in the trace

Traceback (most recent call last):
  File "UNet_benchmark.py", line 124, in <module>
    learn.fit_one_cycle(10, slice(lr), pct_start=0.9)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/train.py", line 23, in fit_one_cycle
    learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/basic_train.py", line 200, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/basic_train.py", line 99, in fit
    for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 75, in __iter__
    if self.auto_update: self.update(i+1)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 92, in update
    self.update_bar(val)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 104, in update_bar
    else: self.on_update(val, f'{100 * val/self.total:.2f}% [{val}/{self.total} {elapsed_t}<{remaining_t}{end}]')
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 274, in on_update
    if printing(): WRITER_FN(to_write, end = '\r')
UnicodeEncodeError: 'ascii' codec can't encode character '\u2588' in position 15: ordinal not in range(128)```

**Comment by yshvrdhn** [comment]
Update the ```UnicodeEncodeError: 'ascii' codec can't encode character '\u2588' in position 15: ordinal not in range(128)``` error was the same as the [unicode error of fast progress](https://github.com/fastai/fastprogress/issues/21) a simple fix was using ```export LC_ALL="en_US.UTF-8```

**Comment by sgugger** [comment]
SO if this fixes it, I'm going to close this issue. Please reopen if needed.
