### ISSUE TITLE
Inconsistent state_dict causes crash when multiple processes run LR Finder code concurrently

### ISSUE THREAD

**Issue by l2edzl3oy** [fastai/fastai#2420]
**Describe the bug**
When multiple training processes are spun up (based on the same Python script) and concurrently run the [Learning Rate Finder code](https://docs.fast.ai/train.html#lr_find), the `state_dict`s may be concurrently written to / read from by these multiple processes. This may result in an inconsistent `state_dict` which leads to the LR finder code crashing.

I believe the cause is that the same `tmp.pth` file is saved and loaded by multiple concurrent processes, per the `lr_finder` code [here](https://github.com/fastai/fastai/blob/master/fastai/callbacks/lr_finder.py#L9):
```
class LRFinder(LearnerCallback):
    ...    

    def on_train_begin(self, pbar, **kwargs:Any)->None:
        "Initialize optimizer and learner hyperparameters."
        setattr(pbar, 'clean_on_interrupt', True)
        self.learn.save('tmp') <-- Save tmp.pth
        self.opt = self.learn.opt
        self.opt.lr = self.sched.start
        self.stop,self.best_loss = False,0.
        return {'skip_validate': True}

    ...

    def on_train_end(self, **kwargs:Any)->None:
        "Cleanup learn model weights disturbed during LRFinder exploration."
        self.learn.load('tmp', purge=False) <-- Load tmp.pth
        if hasattr(self.learn.model, 'reset'): self.learn.model.reset()
        for cb in self.callbacks:
            if hasattr(cb, 'reset'): cb.reset()
        print('LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.')
```

**Provide your installation details**
```text
=== Software ===
python        : 3.6.9
fastai        : 1.0.53
fastprogress  : 0.1.21
torch         : 1.2.0
nvidia driver : 435.21
torch cuda    : 10.0.130 / is available
torch cudnn   : 7602 / is enabled

=== Hardware ===
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 16160MB | Tesla V100-SXM2-16GB

=== Environment ===
platform      : Linux-4.15.0-1054-aws-x86_64-with-debian-buster-sid
distro        : #56-Ubuntu SMP Thu Nov 7 16:15:59 UTC 2019
conda env     : venv-nlp
python        : /home/ubuntu/anaconda3/envs/venv-nlp/bin/python
sys.path      :
/home/ubuntu/anaconda3/envs/venv-nlp/lib/python36.zip
/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6
/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/lib-dynload
/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages

Mon Nov 25 14:19:15 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   31C    P0    36W / 300W |      0MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**To Reproduce**
Same script per the text tutorial [here](https://docs.fast.ai/text.html), with the addition of LR finder code:
```
...
learn = text_classifier_learner(data_clas, AWD_LSTM, drop_mult=0.5)
learn.load_encoder('ft_enc')
learn.lr_find(start_lr=0.001, end_lr=1, stop_div=False)
learn.recorder.plot(suggestion=True)
...
```

Run multiple concurrent processes in the background based on the script, e.g.
```
# Run 5 processes in the background
python train.py &
python train.py &
python train.py &
python train.py &
python train.py &
```

**Expected behavior**
```
...
Nov 21 18:57:59 ip-172-28-2-228 python[851]: epoch     train_loss  valid_loss  accuracy  time
Nov 21 18:58:21 ip-172-28-2-228 python[851]: 0         7.106967    #na#        00:21
Nov 21 18:58:21 ip-172-28-2-228 python[851]: LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.
Nov 21 18:58:21 ip-172-28-2-228 python[851]: Min numerical gradient: 2.75E-02
Nov 21 18:58:21 ip-172-28-2-228 python[851]: Min loss divided by 10: 7.76E-03
Nov 21 18:58:21 ip-172-28-2-228 python[851]: /home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/sixel.py:16: UserWarning: You could see this plot with `libsixel`. See https://github.com/saitoha/libsixel
Nov 21 18:58:21 ip-172-28-2-228 python[851]:   warn("You could see this plot with `libsixel`. See https://github.com/saitoha/libsixel")
...
```

**Screenshots**
Stack trace 1:
```
...
Nov 13 10:34:38 ip-172-27-3-68 python[1063]: 23        5.713100    #na#        00:16
Nov 13 10:34:57 ip-172-27-3-68 python[1063]: 24        7.369972    #na#        00:18
Nov 13 10:34:57 ip-172-27-3-68 python[1063]: Traceback (most recent call last):
...(some omitted logs)...
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/train.py", line 32, in lr_find
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:     learn.fit(epochs, start_lr, callbacks=[cb], wd=wd)
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/basic_train.py", line 200, in fit
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:     fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/basic_train.py", line 112, in fit
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:     finally: cb_handler.on_train_end(exception)
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/callback.py", line 323, in on_train_end
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:     self('train_end', exception=exception)
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/callback.py", line 251, in __call__
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:     for cb in self.callbacks: self._call_and_update(cb, cb_name, **kwargs)
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/callback.py", line 241, in _call_and_update
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:     new = ifnone(getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs), dict())
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/callbacks/lr_finder.py", line 35, in on_train_end
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:     self.learn.load('tmp', purge=False)
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/basic_train.py", line 271, in load
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:     get_model(self.model).load_state_dict(model_state, strict=strict)
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:     self.__class__.__name__, "\n\t".join(error_msgs)))
Nov 13 10:34:57 ip-172-27-3-68 python[1063]: RuntimeError: Error(s) in loading state_dict for SequentialRNN:
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:         size mismatch for 0.encoder.weight: copying a param with shape torch.Size([1989, 400]) from checkpoint, the shape in current model is torch.Size([1347, 400]).
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:         size mismatch for 0.encoder_dp.emb.weight: copying a param with shape torch.Size([1989, 400]) from checkpoint, the shape in current model is torch.Size([1347, 400]).
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:         size mismatch for 1.decoder.weight: copying a param with shape torch.Size([1989, 400]) from checkpoint, the shape in current model is torch.Size([1347, 400]).
Nov 13 10:34:57 ip-172-27-3-68 python[1063]:         size mismatch for 1.decoder.bias: copying a param with shape torch.Size([1989]) from checkpoint, the shape in current model is torch.Size([1347]).
...
```

Stack trace 2:
```
...
Nov 14 00:54:56 ip-172-27-3-68 python[1123]: 1         4.130458    3.280195    0.250227  02:47
Nov 14 00:55:00 ip-172-27-3-68 python[1123]: 21        5.615169    #na#        00:52
Nov 14 00:55:17 ip-172-27-3-68 python[1123]: 12        7.322824    #na#        00:52
Nov 14 00:55:20 ip-172-27-3-68 python[1123]: 10        7.402505    #na#        00:51
Nov 14 00:55:56 ip-172-27-3-68 python[1123]: 22        5.495742    #na#        00:55
Nov 14 00:56:09 ip-172-27-3-68 python[1123]: 11        7.383283    #na#        00:49
Nov 14 00:56:11 ip-172-27-3-68 python[1123]: 13        7.274573    #na#        00:53
Nov 14 00:56:51 ip-172-27-3-68 python[1123]: 23        5.650990    #na#        00:54
Nov 14 00:56:59 ip-172-27-3-68 python[1123]: 14        7.177493    #na#        00:48
Nov 14 00:57:04 ip-172-27-3-68 python[1123]: 12        7.358859    #na#        00:54
Nov 14 00:57:42 ip-172-27-3-68 python[1123]: 24        7.175264    #na#        00:51
Nov 14 00:57:42 ip-172-27-3-68 python[1123]: Traceback (most recent call last):
...(some omitted logs)...
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:     self.__lm_learner.lr_find()
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/train.py", line 32, in lr_find
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:     learn.fit(epochs, start_lr, callbacks=[cb], wd=wd)
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/basic_train.py", line 200, in fit
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:     fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/basic_train.py", line 112, in fit
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:     finally: cb_handler.on_train_end(exception)
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/callback.py", line 323, in on_train_end
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:     self('train_end', exception=exception)
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/callback.py", line 251, in __call__
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:     for cb in self.callbacks: self._call_and_update(cb, cb_name, **kwargs)
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/callback.py", line 241, in _call_and_update
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:     new = ifnone(getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs), dict())
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/callbacks/lr_finder.py", line 35, in on_train_end
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:     self.learn.load('tmp', purge=False)
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/fastai/basic_train.py", line 271, in load
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:     get_model(self.model).load_state_dict(model_state, strict=strict)
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:   File "/home/ubuntu/anaconda3/envs/venv-nlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:     self.__class__.__name__, "\n\t".join(error_msgs)))
Nov 14 00:57:42 ip-172-27-3-68 python[1123]: RuntimeError: Error(s) in loading state_dict for SequentialRNN:
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:         Missing key(s) in state_dict: "0.encoder.weight", "0.encoder_dp.emb.weight", "0.rnns.0.weight_hh_l0_raw", "0.rnns.0.module.weight_ih_l0", "0.rnns.0.module.weight_hh_l0", "0.rnns.0.module.bias_ih_l0", "0.rnns.0.module.bias_hh_l0", "0.rnns.1.weight_hh_l0_raw", "0.rnns.1.module.weight_ih_l0", "0.rnns.1.module.weight_hh_l0", "0.rnns.1.module.bias_ih_l0", "0.rnns.1.module.bias_hh_l0", "0.rnns.2.weight_hh_l0_raw", "0.rnns.2.module.weight_ih_l0", "0.rnns.2.module.weight_hh_l0", "0.rnns.2.module.bias_ih_l0", "0.rnns.2.module.bias_hh_l0", "1.decoder.weight", "1.decoder.bias".
Nov 14 00:57:42 ip-172-27-3-68 python[1123]:         Unexpected key(s) in state_dict: "0.module.encoder.weight", "0.module.encoder_dp.emb.weight", "0.module.rnns.0.weight_hh_l0_raw", "0.module.rnns.0.module.weight_ih_l0", "0.module.rnns.0.module.weight_hh_l0", "0.module.rnns.0.module.bias_ih_l0", "0.module.rnns.0.module.bias_hh_l0", "0.module.rnns.1.weight_hh_l0_raw", "0.module.rnns.1.module.weight_ih_l0", "0.module.rnns.1.module.weight_hh_l0", "0.module.rnns.1.module.bias_ih_l0", "0.module.rnns.1.module.bias_hh_l0", "0.module.rnns.2.weight_hh_l0_raw", "0.module.rnns.2.module.weight_ih_l0", "0.module.rnns.2.module.weight_hh_l0", "0.module.rnns.2.module.bias_ih_l0", "0.module.rnns.2.module.bias_hh_l0", "1.layers.0.weight", "1.layers.0.bias", "1.layers.0.running_mean", "1.layers.0.running_var", "1.layers.0.num_batches_tracked", "1.layers.2.weight", "1.layers.2.bias", "1.layers.4.weight", "1.layers.4.bias", "1.layers.4.running_mean", "1.layers.4.running_var", "1.layers.4.num_batches_tracked", "1.layers.6.weight", "1.layers.6.bias".
...
```

**Additional context**
As an ugly hacky workaround, I am currently appending a UUID to the `tmp.pth` file, which fixes the issue:
```
"Tools to help find the optimal learning rate for training"
from ..torch_core import *
from ..basic_data import DataBunch
from ..callback import *
from ..basic_train import Learner, LearnerCallback
import uuid

__all__ = ['LRFinder']

class LRFinder(LearnerCallback):
    "Causes `learn` to go on a mock training from `start_lr` to `end_lr` for `num_it` iterations."
    def __init__(self, learn:Learner, start_lr:float=1e-7, end_lr:float=10, num_it:int=100, stop_div:bool=True):
        super().__init__(learn)
        self.data,self.stop_div = learn.data,stop_div
        self.sched = Scheduler((start_lr, end_lr), num_it, annealing_exp)
        self.uuid_str = str(uuid.uuid1()) <-- Init UUID

    def on_train_begin(self, pbar, **kwargs:Any)->None:
        "Initialize optimizer and learner hyperparameters."
        setattr(pbar, 'clean_on_interrupt', True)
        self.learn.save('tmp-{}'.format(self.uuid_str)) <-- Append UUID
        self.opt = self.learn.opt
        self.opt.lr = self.sched.start
        self.stop,self.best_loss = False,0.
        return {'skip_validate': True}

    def on_batch_end(self, iteration:int, smooth_loss:TensorOrNumber, **kwargs:Any)->None:
        "Determine if loss has runaway and we should stop."
        if iteration==0 or smooth_loss < self.best_loss: self.best_loss = smooth_loss
        self.opt.lr = self.sched.step()
        if self.sched.is_done or (self.stop_div and (smooth_loss > 4*self.best_loss or torch.isnan(smooth_loss))):
            #We use the smoothed loss to decide on the stopping since it's less shaky.
            return {'stop_epoch': True, 'stop_training': True}

    def on_train_end(self, **kwargs:Any)->None:
        "Cleanup learn model weights disturbed during LRFinder exploration."
        self.learn.load('tmp-{}'.format(self.uuid_str), purge=False) <-- Append UUID
        if hasattr(self.learn.model, 'reset'): self.learn.model.reset()
        for cb in self.callbacks:
            if hasattr(cb, 'reset'): cb.reset()
        print('LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.')
```

**Comment by sgugger** [comment]
You have to run an LR finder on a single process. It is not compatible with distributed training (losses are not reduced for instance). I can add a hack to prevent the error but it won't fix the fact that the result is going to be misleading.

**Comment by sgugger** [comment]
I just looked and the safeguards for load/save are already there (only the master model is save and there is a `distrib_barrier` before the load). Form your stack trace, it appears you don't share the same vocabulary accross processes. You should do the preprocessing before anything distributed then load your data exactly the same way in all processes.

**Comment by l2edzl3oy** [comment]
Thanks for the quick reply @sgugger !

The use case this will be applied to is the scheduled training on an ever-changing dataset, e.g.:
- Every 5 minutes, the dataset will be downloaded (it may change compared to 5 minutes ago).
- A new process will be spun off to do the training, using the downloaded dataset.
- Hence, there may be multiple training processes running concurrently, but each with their own downloaded dataset.

Thus far, the only portion of the fastai code that does not work well with concurrent training processes is the LR finder (which is what this issue is about).

Hope this better explains the issue.

If this use case is not generally applicable then I'm ok to use a custom-made patch to the fastai code.

Otherwise, hope that it's something that the fastai developers can consider, especially if other fastai users face the same scenario / use case. I don't mind contributing to the fastai code as well if so :)

**Comment by sgugger** [comment]
Like I said, your stack trace has sizes mismatch, for a text model on the vocab size, which means you don;t have the same vocab across processes (could come from the splitting train/validation, not sure since there is not all your code here).

Your workaround can't work since only the master process actually saves things in `Learner.save` (not sure which version of fastai you're using, but this is the case in master), so most of your tmp-something files don't exist.
