### ISSUE TITLE
OptimWrapper does not work with pytorch Optimizers without momentum or betas

### ISSUE THREAD

**Issue by FangShancheng** [fastai/fastai#2526]
**Describe the bug**

Optimizers such as Adadelta, Adagrad.. which without the parameters momentum or betas.

**Provide your installation details**

```text
=== Software === 
python        : 3.7.6
fastai        : 1.0.60
fastprogress  : 0.2.2
torch         : 1.0.0
nvidia driver : 384.81
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 2
torch devices : 2
  - gpu0      : 11439MB | Tesla K80
  - gpu1      : 11439MB | Tesla K80

=== Environment === 
platform      : Linux-4.8.0-36-generic-x86_64-with-debian-stretch-sid
distro        : #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017
conda env     : py36
python        : /home/user/miniconda/envs/py36/bin/python
sys.path      : /app/tmp
/home/user/miniconda/envs/py36/lib/python37.zip
/home/user/miniconda/envs/py36/lib/python3.7
/home/user/miniconda/envs/py36/lib/python3.7/lib-dynload
/home/user/miniconda/envs/py36/lib/python3.7/site-packages
```

**To Reproduce**
```
from fastai.vision import *
path = untar_data(URLs.MNIST_SAMPLE)
data = ImageDataBunch.from_folder(path)
learner = cnn_learner(data, models.resnet18, metrics=[accuracy], opt_func=torch.optim.Adadelta). # or Adagrad...
learner.fit(1,1e-3)
```

**Expected behavior**

**Screenshots**
```
epoch     train_loss  valid_loss  accuracy  time    
Traceback (most recent call last):-------------------------------------------------------------------------------| 0.00% [0/193 00:00<00:00]
  File "test.py", line 7, in <module>
    learner.fit(1,1e-3)
  File "/home/user/miniconda/envs/py36/lib/python3.7/site-packages/fastai/basic_train.py", line 200, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "/home/user/miniconda/envs/py36/lib/python3.7/site-packages/fastai/basic_train.py", line 100, in fit
    xb, yb = cb_handler.on_batch_begin(xb, yb)
  File "/home/user/miniconda/envs/py36/lib/python3.7/site-packages/fastai/callback.py", line 279, in on_batch_begin
    self('batch_begin', call_mets = not self.state_dict['train'])
  File "/home/user/miniconda/envs/py36/lib/python3.7/site-packages/fastai/callback.py", line 251, in __call__
    for cb in self.callbacks: self._call_and_update(cb, cb_name, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.7/site-packages/fastai/callback.py", line 241, in _call_and_update
    new = ifnone(getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs), dict())
  File "/home/user/miniconda/envs/py36/lib/python3.7/site-packages/fastai/basic_train.py", line 482, in on_batch_begin
    self.moms.append(self.opt.mom)
  File "/home/user/miniconda/envs/py36/lib/python3.7/site-packages/fastai/callback.py", line 84, in mom
    def mom(self)->float:return self._mom[-1]
TypeError: 'NoneType' object is not subscriptable
```

**Additional context**

**Comment by sgugger** [comment]
Thanks for flagging! Should be fixed now.
