### ISSUE TITLE
ValueError: __len__() should return >= 0,while using nlp

### ISSUE THREAD

**Issue by swetha303112** [fastai/fastai#2605]
**Describe the bug**

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by swetha303112** [comment]
I get the following error while trainning the dataset using AWD -LSTM:

Training models\generator\piano_to_guitar_light.pth
Traceback (most recent call last):
  File "C:/Users/sweth/MusicMine/Training_LSTM.py", line 162, in <module>
    args.nh, args.nl, args.min_freq, args.dropout, args.epochs)
  File "C:/Users/sweth/MusicMine/Training_LSTM.py", line 104, in main
    train_and_save(learner, lrs[i], epochs, save_names[i])
  File "C:\Users\sweth\MusicMine\utils.py", line 42, in train_and_save
    learner.fit(lr, 1, wds=1e-6, cycle_len=epochs, use_clr=(32, 10), metrics=metrics)
  File "C:\Users\sweth\anaconda3\envs\musicminefinal\lib\site-packages\fastai\learner.py", line 302, in fit
    return self.fit_gen(self.model, self.data, layer_opt, n_cycle, **kwargs)
  File "C:\Users\sweth\anaconda3\envs\musicminefinal\lib\site-packages\fastai\learner.py", line 221, in fit_gen
    self.sched = CircularLR(layer_opt, len(data.trn_dl)*cycle_len, on_cycle_end=cycle_end, div=clr_div, cut_div=cut_div,
ValueError: __len__() should return >= 0



the specification of my model is 
bs = 32
 bptt = 200
 em_sz = 400
 nh = 600
 nl = 4
 min_freq = 1
 epochs = 3
 dropout = 1
  training="light"
 load_model = True
My total number of training files and test files are more than the bs value

**Comment by jph00** [comment]
Please use the forums for help.
