### ISSUE TITLE
LearnerTensorboardWriter logs wrong train_loss numbers

### ISSUE THREAD

**Issue by TomConstru** [fastai/fastai#2606]
Hi great Fastai team! first, great work on your amazing tool! it's a delight to use!

I've recently started using the callback for tensorboard with fastai as shown in the docs: https://docs.fast.ai/callbacks.tensorboard.html

I'm using cnn_learner with resnet 34 and learn.fit_one_cycle() (instead of learn.fit() which is in the doc), and I'm also using metrics accuracy_thresh in my learner. 
` 

    arch = models.resnet34
    learn = cnn_learner(data, arch, metrics=accuracy_thresh)
    learn.to_fp16()
    # Tensorboard init line:
    tboard_path = Path('/home/ubuntu/MultiClassLabeling/Tensorboard Data/' + projectName)
    learn.callback_fns.append(partial(LearnerTensorboardWriter, base_dir=tboard_path, name=taskName))
`

Tensorboard results of valid_loss and accuracy_thresh show correctly, however train_loss is completely wrong. 
valid_loss:
![image](https://user-images.githubusercontent.com/56670806/86767075-1fb59080-c054-11ea-901d-b9727cc3e48c.png)

train_loss:
![image](https://user-images.githubusercontent.com/56670806/86767113-2ba15280-c054-11ea-9dd7-7b398e21b757.png)

I haven't changed anything in the fastai tensorboard.py file, so it shouldn't be the issue. 
Here is the terminal view of train_loss, valid_loss, accuracy_thresh:
![image](https://user-images.githubusercontent.com/56670806/86767231-58ee0080-c054-11ea-98a5-79478b818673.png)

what could be causing this?

information about my installation:
```text
=== Software === 
python        : 3.6.9
fastai        : 1.0.61
fastprogress  : 0.2.3
torch         : 1.4.0
nvidia driver : 440.33
torch cuda    : 10.1 / is available
torch cudnn   : 7603 / is enabled

=== Hardware === 
nvidia gpus   : 4
torch devices : 4
  - gpu0      : 16160MB | Tesla V100-SXM2-16GB
  - gpu1      : 16160MB | Tesla V100-SXM2-16GB
  - gpu2      : 16160MB | Tesla V100-SXM2-16GB
  - gpu3      : 16160MB | Tesla V100-SXM2-16GB

=== Environment === 
platform      : Linux-5.3.0-1030-aws-x86_64-with-Ubuntu-18.04-bionic
distro        : #32~18.04.1-Ubuntu SMP Tue Jun 30 23:04:16 UTC 2020
conda env     : Unknown
python        : /home/ubuntu/MultiClassLabeling/myenv/bin/python
sys.path      : 
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages
```

**Comment by TomConstru** [comment]
I'm also getting the following error messages right at the moment the progress bar appears, after which the training takes place as if nothing happened:
```
Exception in thread Thread-1:-------------------------------------------------------------------------------------| 0.00% [0/190 00:00<00:00]
Traceback (most recent call last):
  File "/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/jit/__init__.py", line 639, in run_mod_and_filter_tensor_outputs
    outs = wrap_retval(mod(*_clone_inputs(inputs)))
RuntimeError: Input type (CUDAFloatType) and weight type (CUDAHalfType) should be the same
The above operation failed in interpreter.
Traceback (most recent call last):
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/conv.py(342): conv2d_forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/conv.py(345): forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torchvision/models/resnet.py(60): forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/container.py(100): forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/container.py(100): forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/container.py(100): forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/jit/__init__.py(1034): trace_module
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/jit/__init__.py(882): trace
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py(285): graph
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/tensorboardX/writer.py(794): add_graph
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/fastai/callbacks/tensorboard.py(424): write
/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/fastai/callbacks/tensorboard.py(234): _queue_processor
/usr/lib/python3.6/threading.py(864): run
/usr/lib/python3.6/threading.py(916): _bootstrap_inner
/usr/lib/python3.6/threading.py(884): _bootstrap


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/fastai/callbacks/tensorboard.py", line 234, in _queue_processor
    request.write()
  File "/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/fastai/callbacks/tensorboard.py", line 424, in write
    self.tbwriter.add_graph(model=self.model, input_to_model=self.input_to_model)
  File "/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/tensorboardX/writer.py", line 794, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 285, in graph
    trace = torch.jit.trace(model, args)
  File "/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/jit/__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1044, in trace_module
    check_tolerance, _force_outplace, True, _module_class)
  File "/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/jit/__init__.py", line 677, in _check_trace
    traced_outs = run_mod_and_filter_tensor_outputs(traced_func, inputs, 'trace')
  File "/home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/jit/__init__.py", line 645, in run_mod_and_filter_tensor_outputs
    ' with test inputs.\nException:\n' + indent(str(e)))
torch.jit.TracingCheckError: Tracing failed sanity checks!
Encountered an exception while running the trace with test inputs.
Exception:
        Input type (CUDAFloatType) and weight type (CUDAHalfType) should be the same
        The above operation failed in interpreter.
        Traceback (most recent call last):
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/conv.py(342): conv2d_forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/conv.py(345): forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torchvision/models/resnet.py(60): forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/container.py(100): forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/container.py(100): forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/container.py(100): forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(516): _slow_forward
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(530): __call__
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/jit/__init__.py(1034): trace_module
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/jit/__init__.py(882): trace
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py(285): graph
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/tensorboardX/writer.py(794): add_graph
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/fastai/callbacks/tensorboard.py(424): write
        /home/ubuntu/MultiClassLabeling/myenv/lib/python3.6/site-packages/fastai/callbacks/tensorboard.py(234): _queue_processor
        /usr/lib/python3.6/threading.py(864): run
        /usr/lib/python3.6/threading.py(916): _bootstrap_inner
        /usr/lib/python3.6/threading.py(884): _bootstrap
```

**Comment by jph00** [comment]
Please use the forums for help on this.
