### ISSUE TITLE
NameError: name 'get_ipython' is not defined``` by importing fastai2 command line

### ISSUE THREAD

**Issue by antorsae** [fastai/fastai#2631]
**To Reproduce**
1. `python -c 'import fastai2;import fastcore;print(fastai2.__version__);print(fastcore.__version__);from
fastai2.basics import *'`

**Expected behavior**
Not crash

**Error with full stack trace**

```
0.0.30
0.1.35
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/antor/fastai2/fastai2/basics.py", line 1, in <module>
    from .data.all import *
  File "/home/antor/fastai2/fastai2/data/all.py", line 1, in <module>
    from ..torch_basics import *
  File "/home/antor/fastai2/fastai2/torch_basics.py", line 2, in <module>
    from .imports import *
  File "/home/antor/fastai2/fastai2/imports.py", line 29, in <module>
    from fastcore.all import *
  File "/home/antor/fastcore/fastcore/all.py", line 3, in <module>
    from .dispatch import *
  File "/home/antor/fastcore/fastcore/dispatch.py", line 9, in <module>
    from .utils import *
  File "/home/antor/fastcore/fastcore/utils.py", line 782, in <module>
    IN_IPYTHON,IN_JUPYTER,IN_COLAB,IN_NOTEBOOK = in_ipython(),in_jupyter(),in_colab(),in_notebook()
  File "/home/antor/fastcore/fastcore/utils.py", line 774, in in_jupyter
    return get_ipython().__class__.__name__ == 'ZMQInteractiveShell'
NameError: name 'get_ipython' is not defined```

**Comment by hamelsmu** [comment]
Why did you close this issue?  How did you resolve it?

**Comment by jpe316** [comment]
same issue trying to run python train.py

```python
from fastai2.vision.allimport *
 
path = untar_data(URLs.PETS)
path.ls()
 
files = get_image_files(path/"images")
len(files)
 
def label_func(f): return f[0].isupper()
 
dls = ImageDataLoaders.from_name_func(path, files, label_func, item_tfms=Resize(224))
 
dls.show_batch()
 
learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fine_tune(1)
```

Traceback (most recent call last):
  File "train.py", line 2, in <module>
    from fastai2.vision.all import *
  File "/opt/conda/lib/python3.7/site-packages/fastai2/vision/all.py", line 1, in <module>
    from ..basics import *
  File "/opt/conda/lib/python3.7/site-packages/fastai2/basics.py", line 1, in <module>
    from .data.all import *
  File "/opt/conda/lib/python3.7/site-packages/fastai2/data/all.py", line 1, in <module>
    from ..torch_basics import *
  File "/opt/conda/lib/python3.7/site-packages/fastai2/torch_basics.py", line 2, in <module>
    from .imports import *
  File "/opt/conda/lib/python3.7/site-packages/fastai2/imports.py", line 29, in <module>
    from fastcore.all import *
  File "/opt/conda/lib/python3.7/site-packages/fastcore/all.py", line 3, in <module>
    from .dispatch import *
  File "/opt/conda/lib/python3.7/site-packages/fastcore/dispatch.py", line 9, in <module>
    from .utils import *
  File "/opt/conda/lib/python3.7/site-packages/fastcore/utils.py", line 782, in <module>
    IN_IPYTHON,IN_JUPYTER,IN_COLAB,IN_NOTEBOOK = in_ipython(),in_jupyter(),in_colab(),in_notebook()
  File "/opt/conda/lib/python3.7/site-packages/fastcore/utils.py", line 774, in in_jupyter
    return get_ipython().__class__.__name__ == 'ZMQInteractiveShell'
NameError: name 'get_ipython' is not defined

**Comment by jph00** [comment]
You just need to update fastcore and fastai to fix it.
