### ISSUE TITLE
Can't nbdev_build_lib

### ISSUE THREAD

**Issue by richarddwang** [fastai/fastai#2697]
Either with the latest pypi package or editable install version nbdev.
Trying on the latest fastai clone
```
 ~/fastai % nbdev_build_lib 
Traceback (most recent call last):
  File "/home/yisiang/miniconda3/envs/ml/bin/nbdev_build_lib", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_build_lib')())
  File "/home/yisiang/miniconda3/envs/ml/lib/python3.7/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "/home/yisiang/nbdev/nbdev/cli.py", line 140, in nbdev_build_lib
    write_tmpls()
  File "/home/yisiang/nbdev/nbdev/export2html.py", line 505, in write_tmpls
    write_tmpl(config_tmpl, 'user lib_name title copyright description', cfg, cfg.doc_path/'_config.yml')
  File "/home/yisiang/nbdev/nbdev/export2html.py", line 499, in write_tmpl
    dest.write_text(outp)
  File "/home/yisiang/miniconda3/envs/ml/lib/python3.7/pathlib.py", line 1235, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/home/yisiang/miniconda3/envs/ml/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
  File "/home/yisiang/miniconda3/envs/ml/lib/python3.7/pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/yisiang/fastai/docs/_config.yml'
```

**Comment by muellerzr** [comment]
Temporary fix: `mv docs_src docs` and then before committing: `mv docs docs_src`

**Comment by jph00** [comment]
Better fix is to first run `make docs`.

**Comment by jph00** [comment]
OK I think this should be fixed now, without needing to run `make docs`.
