### ISSUE TITLE
Windows issue since version 2.0.9

### ISSUE THREAD

**Issue by henry090** [fastai/fastai#2767]
Hi.

I see that there is no test for Windows (Github Actions *windows-latest*).

For tabular data prediction, I get the following since version 2.0.9. It was working for 2.0.8.

Code snippet is taken from here:
https://github.com/fastai/fastai/blob/master/dev_nbs/course/lesson4-tabular.ipynb

```
row = df.iloc[0]
learn.predict(row)
```

```
Fatal error: you must specify '--save', '--no-save' or '--vanilla'

-- 1. Failure: tabular ops predict  --------------------------------------------
`force(expr)` threw an error.
Message: AttributeError: Can't pickle local object 'make_python_function.<locals>.python_function'
```

Predictions in Mac OS, Ubuntu 16-20 systems __work fine__.

Do you have any suggestions?

**Comment by asvcode** [comment]
I was unable to reproduce your error but I did get another one which seems to be affected by this recent update [#2721](https://github.com/fastai/fastai/pull/2721).  This works fine on my windows machine with `fastai 2.0.8` but throws this error with version `2.0.9`

```
Empty                                     Traceback (most recent call last)
~\AppData\Roaming\Python\Python37\site-packages\torch\utils\data\dataloader.py in _try_get_data(self, timeout)
    778         try:
--> 779             data = self._data_queue.get(timeout=timeout)
    780             return (True, data)

~\Anaconda3\envs\fastai_2020_N\lib\multiprocessing\queues.py in get(self, block, timeout)
    104                     if not self._poll(timeout):
--> 105                         raise Empty
    106                 elif not self._poll():

Empty: 

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-12-a8e547ce62ec> in <module>
----> 1 learn.predict(row, n_workers=12)

~\AppData\Roaming\Python\Python37\site-packages\fastai\tabular\learner.py in predict(self, row, n_workers)
     16         dl = self.dls.test_dl(row.to_frame().T, num_workers=0)
     17         dl.dataset.conts = dl.dataset.conts.astype(np.float32)
---> 18         inp,preds,_,dec_preds = self.get_preds(dl=dl, with_input=True, with_decoded=True)
     19         b = (*tuplify(inp),*tuplify(dec_preds))
     20         full_dec = self.dls.decode(b)

~\AppData\Roaming\Python\Python37\site-packages\fastai\learner.py in get_preds(self, ds_idx, dl, with_input, with_decoded, with_loss, act, inner, reorder, cbs, n_workers, **kwargs)
    233         if with_loss: ctx_mgrs.append(self.loss_not_reduced())
    234         with ContextManagers(ctx_mgrs):
--> 235             self._do_epoch_validate(dl=dl)
    236             if act is None: act = getattr(self.loss_func, 'activation', noop)
    237             res = cb.all_tensors()

~\AppData\Roaming\Python\Python37\site-packages\fastai\learner.py in _do_epoch_validate(self, ds_idx, dl)
    186         if dl is None: dl = self.dls[ds_idx]
    187         self.dl = dl
--> 188         with torch.no_grad(): self._with_events(self.all_batches, 'validate', CancelValidException)
    189 
    190     def _do_epoch(self):

~\AppData\Roaming\Python\Python37\site-packages\fastai\learner.py in _with_events(self, f, event_type, ex, final)
    153 
    154     def _with_events(self, f, event_type, ex, final=noop):
--> 155         try:       self(f'before_{event_type}')       ;f()
    156         except ex: self(f'after_cancel_{event_type}')
    157         finally:   self(f'after_{event_type}')        ;final()

~\AppData\Roaming\Python\Python37\site-packages\fastai\learner.py in all_batches(self)
    159     def all_batches(self):
    160         self.n_iter = len(self.dl)
--> 161         for o in enumerate(self.dl): self.one_batch(*o)
    162 
    163     def _do_one_batch(self):

~\AppData\Roaming\Python\Python37\site-packages\fastai\data\load.py in __iter__(self)
    101         self.randomize()
    102         self.before_iter()
--> 103         for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
    104             if self.device is not None: b = to_device(b, self.device)
    105             yield self.after_batch(b)

~\AppData\Roaming\Python\Python37\site-packages\torch\utils\data\dataloader.py in __next__(self)
    361 
    362     def __next__(self):
--> 363         data = self._next_data()
    364         self._num_yielded += 1
    365         if self._dataset_kind == _DatasetKind.Iterable and \

~\AppData\Roaming\Python\Python37\site-packages\torch\utils\data\dataloader.py in _next_data(self)
    972 
    973             assert not self._shutdown and self._tasks_outstanding > 0
--> 974             idx, data = self._get_data()
    975             self._tasks_outstanding -= 1
    976 

~\AppData\Roaming\Python\Python37\site-packages\torch\utils\data\dataloader.py in _get_data(self)
    939         else:
    940             while True:
--> 941                 success, data = self._try_get_data()
    942                 if success:
    943                     return data

~\AppData\Roaming\Python\Python37\site-packages\torch\utils\data\dataloader.py in _try_get_data(self, timeout)
    790             if len(failed_workers) > 0:
    791                 pids_str = ', '.join(str(w.pid) for w in failed_workers)
--> 792                 raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
    793             if isinstance(e, queue.Empty):
    794                 return (False, None)

RuntimeError: DataLoader worker (pid(s) 20252, 19284, 8980, 11452, 6872, 20204, 19932, 3140, 27916, 4960, 18616, 4984) exited unexpectedly
```
Typically this error refers to `num_workers` being put to `0` but in this case I am not sure how to resolve this issue.

No change in the code, same as the notebook you referenced above and it works fine on `colab` and `windows with 2.0.8`

**Comment by henry090** [comment]
Thanks for your reply. Yes, everything fine with version ```2.0.8``` in Windows. However, recent update ```2.0.9``` throws:
```
2020-09-07T07:55:59.5903654Z -- 1. Failure: tabular ops predict  --------------------------------------------
2020-09-07T07:55:59.5903948Z `force(expr)` threw an error.
2020-09-07T07:55:59.5904364Z Message: AttributeError: Can't pickle local object 'make_python_function.<locals>.python_function'
2020-09-07T07:55:59.5904570Z 
2020-09-07T07:55:59.5904808Z Detailed traceback: 
2020-09-07T07:55:59.5905515Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\fastai\tabular\learner.py", line 18, in predict
2020-09-07T07:55:59.5906176Z     inp,preds,_,dec_preds = self.get_preds(dl=dl, with_input=True, with_decoded=True)
2020-09-07T07:55:59.5906676Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\fastai\learner.py", line 235, in get_preds
2020-09-07T07:55:59.5906989Z     self._do_epoch_validate(dl=dl)
2020-09-07T07:55:59.5907873Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\fastai\learner.py", line 188, in _do_epoch_validate
2020-09-07T07:55:59.7797723Z     with torch.no_grad(): self._with_events(self.all_batches, 'validate', CancelValidException)
2020-09-07T07:55:59.7798178Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\fastai\learner.py", line 155, in _with_events
2020-09-07T07:55:59.7798446Z     try:       self(f'before_{event_type}')       ;f()
2020-09-07T07:55:59.7798834Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\fastai\learner.py", line 161, in all_batches
2020-09-07T07:55:59.7799095Z     for o in enumerate(self.dl): self.one_batch(*o)
2020-09-07T07:55:59.7799473Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\fastai\data\load.py", line 103, in __iter__
2020-09-07T07:55:59.7799746Z     for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
2020-09-07T07:55:59.7800153Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
2020-09-07T07:55:59.7800331Z     w.start()
2020-09-07T07:55:59.7800844Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\multiprocessing\process.py", line 105, in start
2020-09-07T07:55:59.7801085Z     self._popen = self._Popen(self)
2020-09-07T07:55:59.7801449Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\multiprocessing\context.py", line 223, in _Popen
2020-09-07T07:55:59.7801728Z     return _default_context.get_context().Process._Popen(process_obj)
2020-09-07T07:55:59.7802198Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\multiprocessing\context.py", line 322, in _Popen
2020-09-07T07:55:59.7802396Z     return Popen(process_obj)
2020-09-07T07:55:59.7802771Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
2020-09-07T07:55:59.7802996Z     reduction.dump(process_obj, to_child)
2020-09-07T07:55:59.7803354Z   File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\multiprocessing\reduction.py", line 60, in dump
```

**Comment by henry090** [comment]
@muellerzr Hi, Could you tell how to fix the above-mentioned error (n_workers) for Windows, please? The last versions ```2.0.9,2.0.10``` of fastai keep failing in Windows when we want to make predictions on tabular data. https://github.com/fastai/fastai/pull/2721

**Comment by muellerzr** [comment]
FYI the workers issue will be solved in a PR soon, `predict` isn't passing in `workers` to `get_preds`, only to the `DL`. Sorry!

**Comment by henry090** [comment]
This https://github.com/fastai/fastai/pull/2804 fixed the issue related to ```n_workers```, Thanks, Zachary!
