### ISSUE TITLE
can't import fastai2 on clean virtual enviroment (centos8)

### ISSUE THREAD

**Issue by raphael2692** [fastai/fastai#2773]
Can't import fastai2.vision.all on clean virtual enviroment. 

System spec:

- Centos8
- Python3 3.6.8
- GCC 8.3.1

Code:

```python
pip install torch torchvision ipython fastai

from fastai2.vision.all import *
```

Traceback:

```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from fastai2.vision.all import *
  File "/home/segmentation-model/venv/lib64/python3.6/site-packages/fastai2/vision/all.py", line 1, in <module>
    from ..basics import *
  File "/home/segmentation-model/venv/lib64/python3.6/site-packages/fastai2/basics.py", line 1, in <module>
    from .data.all import *
  File "/home/segmentation-model/venv/lib64/python3.6/site-packages/fastai2/data/all.py", line 5, in <module>
    from .transforms import *
  File "/home/segmentation-model/venv/lib64/python3.6/site-packages/fastai2/data/transforms.py", line 230, in <module>
    class Categorize(DisplayedTransform):
  File "/home/segmentation-model/venv/lib64/python3.6/site-packages/fastai2/data/transforms.py", line 232, in Categorize
    loss_func,order,store_attrs=CrossEntropyLossFlat(),1,'vocab,add_na'
  File "/home/segmentation-model/venv/lib64/python3.6/site-packages/fastcore/utils.py", line 472, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/home/segmentation-model/venv/lib64/python3.6/site-packages/fastai2/layers.py", line 306, in __init__
    def __init__(self, *args, axis=-1, **kwargs): super().__init__(nn.CrossEntropyLoss, *args, axis=axis, **kwargs)
  File "/home/segmentation-model/venv/lib64/python3.6/site-packages/fastcore/utils.py", line 472, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/home/segmentation-model/venv/lib64/python3.6/site-packages/fastai2/layers.py", line 281, in __init__
    store_attr(self, "axis,flatten,floatify,is_2d")
  File "/home/segmentation-model/venv/lib64/python3.6/site-packages/fastcore/utils.py", line 97, in store_attr
    if not hasattr(self, '__stored_args__'): self.__stored_args__ = {}
AttributeError: 'str' object has no attribute '__stored_args__'
```

Virtualenv pip freeze:

```
backcall==0.2.0
blis==0.4.1
catalogue==1.0.0
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
cymem==2.0.3
dataclasses==0.7
decorator==4.4.2
fastai==2.0.9
fastcore==1.0.4
fastprogress==1.0.0
future==0.18.2
idna==2.10
importlib-metadata==1.7.0
ipython==7.16.1
ipython-genutils==0.2.0
jedi==0.17.2
joblib==0.16.0
kiwisolver==1.2.0
matplotlib==3.3.1
murmurhash==1.0.2
numpy==1.19.1
packaging==20.4
pandas==1.1.1
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
plac==1.1.3
preshed==3.0.2
prompt-toolkit==3.0.7
ptyprocess==0.6.0
Pygments==2.6.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
scikit-learn==0.23.2
scipy==1.5.2
six==1.15.0
spacy==2.3.2
srsly==1.0.2
thinc==7.4.1
threadpoolctl==2.1.0
torch==1.6.0
torchvision==0.7.0
tqdm==4.48.2
traitlets==4.3.3
urllib3==1.25.10
wasabi==0.8.0
wcwidth==0.2.5
zipp==3.1.0
```

**Comment by muellerzr** [comment]
It's fastai, no longer fastai2.
