### ISSUE TITLE
KeyError for IMDB tutorial

### ISSUE THREAD

**Issue by HeroadZ** [fastai/fastai#2789]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**
KeyError: 'pos' for the learn.fine_tune function in IMDB tutorial

**To Reproduce**
1. just run the example code
```python 
from fastai.text.all import *

path = untar_data(URLs.IMDB)
dls = TextDataLoaders.from_folder(path, valid='test')
learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5, metrics=accuracy)
learn.fine_tune(4, 1e-2)
```

**Expected behavior**
show time and accuracy after each epoch

**Error with full stack trace**
```
epoch     train_loss  valid_loss  accuracy  time    
0         0.138724    None        None      00:22                                                                     
Traceback (most recent call last):
  File "bert.py", line 10, in <module>
    learn.fine_tune(4, 1e-2)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastcore/utils.py", line 473, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/callback/schedule.py", line 161, in fine_tune
    self.fit_one_cycle(freeze_epochs, slice(base_lr), pct_start=0.99, **kwargs)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastcore/utils.py", line 473, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/callback/schedule.py", line 113, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastcore/utils.py", line 473, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/learner.py", line 207, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/learner.py", line 197, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/learner.py", line 192, in _do_epoch
    self._do_epoch_validate()
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/learner.py", line 188, in _do_epoch_validate
    with torch.no_grad(): self._with_events(self.all_batches, 'validate', CancelValidException)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/learner.py", line 161, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/data/load.py", line 103, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data = next(self.dataset_iter)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/data/load.py", line 112, in create_batches
    yield from map(self.do_batch, self.chunkify(res))
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastcore/utils.py", line 371, in chunked
    res = list(itertools.islice(it, chunk_sz))
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/data/load.py", line 125, in do_item
    try: return self.after_item(self.create_item(s))
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/data/load.py", line 131, in create_item
    def create_item(self, s):  return next(self.it) if s is None else self.dataset[s]
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/data/core.py", line 314, in __getitem__
    res = tuple([tl[it] for tl in self.tls])
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/data/core.py", line 314, in <listcomp>
    res = tuple([tl[it] for tl in self.tls])
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/data/core.py", line 280, in __getitem__
    return self._after_item(res) if is_indexer(idx) else res.map(self._after_item)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/data/core.py", line 242, in _after_item
    def _after_item(self, o): return self.tfms(o)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastcore/transform.py", line 197, in __call__
    def __call__(self, o): return compose_tfms(o, tfms=self.fs, split_idx=self.split_idx)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastcore/transform.py", line 149, in compose_tfms
    x = f(x, **kwargs)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastcore/transform.py", line 72, in __call__
    def __call__(self, x, **kwargs): return self._call('encodes', x, **kwargs)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastcore/transform.py", line 82, in _call
    return self._do_call(getattr(self, fn), x, **kwargs)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastcore/transform.py", line 88, in _do_call
    return retain_type(f(x, **kwargs), x, ret)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastcore/dispatch.py", line 110, in __call__
    return f(*args, **kwargs)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/fastai/data/transforms.py", line 240, in encodes
    def encodes(self, o): return TensorCategory(self.vocab.o2i[o])
KeyError: 'pos'
```

**Additional context**
Moreover, the jupyter notebook on colab also raises error.
```python 
from fastai.text.all import *
```
will raise error, no module named fastai.text.all.
The reason might be that the version on colab is old?

**Comment by TannerGilbert** [comment]
The default version of FastAI on Google Colab is 1.0.62. Therefore you need to update before running the code using:

```
!pip install fastai --upgrade -q
```

After that training worked for me without any issues (I only needed to decrease the batch size to not run out of memory):
![fastai_imdb](https://user-images.githubusercontent.com/36239763/93021414-bbc6bf80-f5e2-11ea-9c0c-46f2d9ec5bd5.png)

**Comment by HeroadZ** [comment]
@TannerGilbert That solved the problem on Colab. But the KeyError problem occurs at my local environment with the latest fastai installed by the conda command.

**Comment by TannerGilbert** [comment]
Hard to say. It seems like it tries to convert the text to integer in the [encodes method](https://github.com/fastai/fastai/blob/cdd9cf33aa74fdeb64717ac1d03662040c1b3d2d/fastai/data/transforms.py#L240) but the vocab doesn't have 'pos' as a key. Because it works in Google Colab it is most likely a error in your local installation. Maybe try creating a new conda environment and reinstall fastai there.

**Comment by HeroadZ** [comment]
I create a new environment and reinstall pytorch and fastai, but it still fails. The reason might be that I'm now using windows 10? or python 3.8? I have no idea.

**Comment by tyoc213** [comment]
Tried your example and instead got this

```

 Download of https://s3.amazonaws.com/fast-ai-modelzoo/wt103-fwd.tgz has failed after 5 retries
 Fix the download manually:
$ mkdir -p /home/tyoc213/.fastai/archive
$ cd /home/tyoc213/.fastai/archive
$ wget -c https://s3.amazonaws.com/fast-ai-modelzoo/wt103-fwd.tgz
$ tar xf wt103-fwd.tgz
 And re-run your code once the download is successful

---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-1-25bb0d73c882> in <module>
      3 path = untar_data(URLs.IMDB)
      4 dls = TextDataLoaders.from_folder(path, valid='test')
----> 5 learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5, metrics=accuracy)
      6 learn.fine_tune(4, 1e-2)

~/Documents/github/fastcore/fastcore/logargs.py in _f(*args, **kwargs)
     50         log_dict = {**func_args.arguments, **{f'{k} (not in signature)':v for k,v in xtra_kwargs.items()}}
     51         log = {f'{f.__qualname__}.{k}':v for k,v in log_dict.items() if k not in but}
---> 52         inst = f(*args, **kwargs) if to_return else args[0]
     53         init_args = getattr(inst, 'init_args', {})
     54         init_args.update(log)

~/Documents/github/fastai/fastai/text/learner.py in text_classifier_learner(dls, arch, seq_len, config, backwards, pretrained, drop_mult, n_out, lin_ftrs, ps, max_len, y_range, **kwargs)
    230             warn("There are no pretrained weights for that architecture yet!")
    231             return learn
--> 232         model_path = untar_data(meta[url], c_key='model')
    233         fnames = [list(model_path.glob(f'*.{ext}'))[0] for ext in ['pth', 'pkl']]
    234         learn = learn.load_pretrained(*fnames, model=learn.model[0])

~/Documents/github/fastai/fastai/data/external.py in untar_data(url, fname, dest, c_key, force_download, extract_func)
    257         if _get_check(url) and _check_file(fname) != _get_check(url):
    258             print(f"File downloaded is broken. Remove {fname} and try again.")
--> 259         extract_func(fname, dest.parent)
    260         rename_extracted(dest)
    261     return dest

~/Documents/github/fastai/fastai/data/external.py in file_extract(fname, dest)
    217     if dest is None: dest = Path(fname).parent
    218     fname = str(fname)
--> 219     if   fname.endswith('gz'):  tarfile.open(fname, 'r:gz').extractall(dest)
    220     elif fname.endswith('zip'): zipfile.ZipFile(fname     ).extractall(dest)
    221     else: raise Exception(f'Unrecognized archive: {fname}')

~/miniconda3/envs/fastai/lib/python3.8/tarfile.py in extractall(self, path, members, numeric_owner)
   2024                 tarinfo.mode = 0o700
   2025             # Do not set_attrs directories, as we will do that further down
-> 2026             self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
   2027                          numeric_owner=numeric_owner)
   2028 

~/miniconda3/envs/fastai/lib/python3.8/tarfile.py in extract(self, member, path, set_attrs, numeric_owner)
   2065 
   2066         try:
-> 2067             self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
   2068                                  set_attrs=set_attrs,
   2069                                  numeric_owner=numeric_owner)

~/miniconda3/envs/fastai/lib/python3.8/tarfile.py in _extract_member(self, tarinfo, targetpath, set_attrs, numeric_owner)
   2137 
   2138         if tarinfo.isreg():
-> 2139             self.makefile(tarinfo, targetpath)
   2140         elif tarinfo.isdir():
   2141             self.makedir(tarinfo, targetpath)

~/miniconda3/envs/fastai/lib/python3.8/tarfile.py in makefile(self, tarinfo, targetpath)
   2186                 target.truncate()
   2187             else:
-> 2188                 copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
   2189 
   2190     def makeunknown(self, tarinfo, targetpath):

~/miniconda3/envs/fastai/lib/python3.8/tarfile.py in copyfileobj(src, dst, length, exception, bufsize)
    245     blocks, remainder = divmod(length, bufsize)
    246     for b in range(blocks):
--> 247         buf = src.read(bufsize)
    248         if len(buf) < bufsize:
    249             raise exception("unexpected end of data")

~/miniconda3/envs/fastai/lib/python3.8/gzip.py in read(self, size)
    290             import errno
    291             raise OSError(errno.EBADF, "read() on write-only GzipFile object")
--> 292         return self._buffer.read(size)
    293 
    294     def read1(self, size=-1):

~/miniconda3/envs/fastai/lib/python3.8/_compression.py in readinto(self, b)
     66     def readinto(self, b):
     67         with memoryview(b) as view, view.cast("B") as byte_view:
---> 68             data = self.read(len(byte_view))
     69             byte_view[:len(data)] = data
     70         return len(data)

~/miniconda3/envs/fastai/lib/python3.8/gzip.py in read(self, size)
    496                 break
    497             if buf == b"":
--> 498                 raise EOFError("Compressed file ended before the "
    499                                "end-of-stream marker was reached")
    500 

EOFError: Compressed file ended before the end-of-stream marker was reached


```

And if I try to run again I get this

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-c993adf43077> in <module>
----> 1 learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5, metrics=accuracy)
      2 learn.fine_tune(4, 1e-2)

~/Documents/github/fastcore/fastcore/logargs.py in _f(*args, **kwargs)
     50         log_dict = {**func_args.arguments, **{f'{k} (not in signature)':v for k,v in xtra_kwargs.items()}}
     51         log = {f'{f.__qualname__}.{k}':v for k,v in log_dict.items() if k not in but}
---> 52         inst = f(*args, **kwargs) if to_return else args[0]
     53         init_args = getattr(inst, 'init_args', {})
     54         init_args.update(log)

~/Documents/github/fastai/fastai/text/learner.py in text_classifier_learner(dls, arch, seq_len, config, backwards, pretrained, drop_mult, n_out, lin_ftrs, ps, max_len, y_range, **kwargs)
    231             return learn
    232         model_path = untar_data(meta[url], c_key='model')
--> 233         fnames = [list(model_path.glob(f'*.{ext}'))[0] for ext in ['pth', 'pkl']]
    234         learn = learn.load_pretrained(*fnames, model=learn.model[0])
    235         learn.freeze()

~/Documents/github/fastai/fastai/text/learner.py in <listcomp>(.0)
    231             return learn
    232         model_path = untar_data(meta[url], c_key='model')
--> 233         fnames = [list(model_path.glob(f'*.{ext}'))[0] for ext in ['pth', 'pkl']]
    234         learn = learn.load_pretrained(*fnames, model=learn.model[0])
    235         learn.freeze()

IndexError: list index out of range
```

Will see if I can replicate original bug... and check the space on my HD just in case...

**Comment by HeroadZ** [comment]
Actually I can fine tune transformers but cannot run this demo code correctly. That's confusing. 
What can I do to help you?

**Comment by tyoc213** [comment]
Try installing from source... if you have time and can create a new env... you just clone fastcore and fastai repo then in your new env, just do `pip install -e .`

**Comment by tyoc213** [comment]
@HeroadZ I could run locally this with 

```
from fastai.text.all import *

path = untar_data(URLs.IMDB)
dls = TextDataLoaders.from_folder(path, valid='test', bs=16)
learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5, metrics=accuracy)
learn.fine_tune(4, 1e-2)
```

See I only reduced batch size to 16.... mmm.

On a new conda env installing from source fastcore and fastai. Havent tried with pip install.

**Comment by tyoc213** [comment]
I also link https://github.com/fastai/fastai/issues/2787 as related to this one

**Comment by HeroadZ** [comment]
Hi, I rerun the code and it can run correctly. Don't know the reason why it work now 😅

**Comment by tyoc213** [comment]
Actually did you updated your fastai or fastcore versions??? maybe got solved in the way, recently been some changes here and there and things are moving so maybe you get in the middle of something.

**Comment by HeroadZ** [comment]
I didn't update fastai. 
After the bug occurred, I left it alone.
Then I tried examples related to transformers. It worked correctly.
Now I rerun the former IMDB code, and it doesn't raise an error.

**Comment by tyoc213** [comment]
so is all OK now?

**Comment by HeroadZ** [comment]
yes, thank you very much!
