### ISSUE TITLE
RuntimeError: no valid convolution algorithms available in CuDNN

### ISSUE THREAD

**Issue by picEmily** [fastai/fastai#3031]
pytorch  1.7.0
python 3.7
cuda 10.2
 cudnn      7605
GeForce RTX 2080 Ti

what should I do?

**Comment by xzming1998** [comment]
I have met the same problem, have you solved it?

**Comment by tcapelle** [comment]
Would you mind posting the detailed error?

**Comment by xzming1998** [comment]
Sure, the details are as follows:
Traceback (most recent call last):
  File "/home/zm/anaconda3/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/inference/predict_simple.py", line 221, in main
    step_size=step_size, checkpoint_name=args.chk)
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/inference/predict.py", line 636, in predict_from_folder
    segmentation_export_kwargs=segmentation_export_kwargs)
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/inference/predict.py", line 220, in predict_cases
    mixed_precision=mixed_precision)[1][None])
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 219, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 521, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/network_architecture/neural_network.py", line 150, in predict_3D
    verbose=verbose)
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/network_architecture/neural_network.py", line 385, in _internal_predict_3D_3Dconv_tiled
    gaussian_importance_map)[0]
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/network_architecture/neural_network.py", line 522, in _internal_maybe_mirror_and_pred_3D
    pred = self.inference_apply_nonlin(self(x))
  File "/home/zm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/network_architecture/generic_UNet.py", line 391, in forward
    x = self.conv_blocks_context[d](x)
  File "/home/zm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)
  File "/home/zm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/zm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zm/nnUNetFrame/nnUNet/nnunet/network_architecture/generic_UNet.py", line 65, in forward
    x = self.conv(x)
  File "/home/zm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 573, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: no valid convolution algorithms available in CuDNN

pytorch 1.7.1 , python3.6, cuda10.2, cudnn8.05, GeForce RTX 3090 .
I am wondering if I have chosen the wrong version of cuDdnn or cuda?
Thanks in advance!

**Comment by tcapelle** [comment]
please run:
```
from fastai.test_utils import show_install
show_install()
```
and post the output

**Comment by xzming1998** [comment]
Thank you very much!  I have created a fresh environment and solved that problem.

**Comment by tcapelle** [comment]
@jph00  you can close this

**Comment by hchen404** [comment]
> Thank you very much! I have created a fresh environment and solved that problem.
Did you reinstall the virtual environment using pytorch1.7.1 , python3.6, cuda10.2, cudnn8.05, GeForce RTX 3090 environment?
