### ISSUE TITLE
AttributeError: '_FakeLoader' object has no attribute 'noops'

### ISSUE THREAD

**Issue by Ying-Kang** [fastai/fastai#3047]
****************************************Describe the bug****************************************
The env installed with torch1.7 and fastai 2.1.8
Keep raising an error "**AttributeError: '_FakeLoader' object has no attribute 'noops'**" when I running an opensource code locally which can be run with fastai in kaggle kernel
Upgrade  fastai can not work as it has been the newest
Downgrade fastai may encounter "NameError: name 'log_args' is not defined" which calls for upgrade
So frustrated with this bug and I have been struggling for it for whole day
I'd appreciate if you could offer help

****************************************To Reproduce****************************************
Recent kaggle competition: HuBMAP.
There's one open source solution using fastai: https://www.kaggle.com/iafoss/hubmap-pytorch-fast-ai-starter
I just complete running in kaggle kernel with the opensource code
But when I just copy the notebook to local scripts and install fastai using"conda install -c fastai fastai", keep raising above error.
local machine and configurations are as follow:
windows10+anaconda+"conda install -c fastai fastai"+code mentioned
finnaly env installed with : torch1.7 and fastai 2.1.8

****************************************Expected behavior****************************************
start training and return metrics

****************************************Error with full stack trace****************************************
Using cache found in C:\Users\lenovo/.cache\torch\hub\facebookresearch_semi-supervised-ImageNet1K-models_master
epoch     train_loss  valid_loss  dice_soft  dice_th   time    
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda3\envs\fastai\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\anaconda3\envs\fastai\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: '_FakeLoader' object has no attribute 'noops'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda3\envs\fastai\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\anaconda3\envs\fastai\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: '_FakeLoader' object has no attribute 'noops'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda3\envs\fastai\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\anaconda3\envs\fastai\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: '_FakeLoader' object has no attribute 'noops'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda3\envs\fastai\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\anaconda3\envs\fastai\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: '_FakeLoader' object has no attribute 'noops'
0         nan         00:16       
Traceback (most recent call last):
  File "D:\anaconda3\envs\fastai\lib\site-packages\torch\utils\data\dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "D:\anaconda3\envs\fastai\lib\queue.py", line 172, in get
    raise Empty
queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/competition/Kaggle/HuBMAP/main.py", line 38, in <module>
    learn.fit_one_cycle(6, lr_max=0.5e-2)
  File "D:\anaconda3\envs\fastai\lib\site-packages\fastai\callback\schedule.py", line 112, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "D:\anaconda3\envs\fastai\lib\site-packages\fastai\learner.py", line 205, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "D:\anaconda3\envs\fastai\lib\site-packages\fastai\learner.py", line 154, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "D:\anaconda3\envs\fastai\lib\site-packages\fastai\learner.py", line 196, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "D:\anaconda3\envs\fastai\lib\site-packages\fastai\learner.py", line 154, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "D:\anaconda3\envs\fastai\lib\site-packages\fastai\learner.py", line 190, in _do_epoch
    self._do_epoch_train()
  File "D:\anaconda3\envs\fastai\lib\site-packages\fastai\learner.py", line 182, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "D:\anaconda3\envs\fastai\lib\site-packages\fastai\learner.py", line 154, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "D:\anaconda3\envs\fastai\lib\site-packages\fastai\learner.py", line 160, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "D:\anaconda3\envs\fastai\lib\site-packages\fastai\data\load.py", line 101, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "D:\anaconda3\envs\fastai\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\fastai\lib\site-packages\torch\utils\data\dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "D:\anaconda3\envs\fastai\lib\site-packages\torch\utils\data\dataloader.py", line 1024, in _get_data
    success, data = self._try_get_data()
  File "D:\anaconda3\envs\fastai\lib\site-packages\torch\utils\data\dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 32476, 32212, 8828, 31844) exited unexpectedly

**Comment by iskorini** [comment]
Same exception with your env and a different model/dataloader.
Any solutions?

**Comment by Kouin** [comment]
> Same exception with your env and a different model/dataloader.
> Any solutions?
> EDIT: I temporarily solved adding `num_workers=0` to my dataloader.
> 
> ```python
>  dls = DataLoaders.from_dsets(ds_train, ds_val, bs=4, num_workers=0)
> ```

thx bro, it works!!!

**Comment by tmabraham** [comment]
The versions in the Kaggle Kernel are:
torch - 1.6.0
fastcore - 1.3.2
fastai - 2.0.19

Have you tried locally with these versions?

**Comment by Kouin** [comment]
> The versions in the Kaggle Kernel are:
> torch - 1.6.0
> fastcore - 1.3.2
> fastai - 2.0.19
> 
> Have you tried locally with these versions?

yes，i've tried torch 1.6 and 1.7 with corresponding fastai version

**Comment by tmabraham** [comment]
@Kouin what are the exact fastai and fastcore versions you used for torch 1.6.0?

**Comment by Kouin** [comment]
> @Kouin what are the exact fastai and fastcore versions you used for torch 1.6.0?
I could not exactly remmember the thorough information about my attempts

but I remember I used the instruction `conda install fastai -c fastai` to install fastai after installing torch by `conda install -c pytorch pytorch=1.6`

Now, I'm using torch1.7 with fastai2.1.8, fastcore 1.3.10. 
I temporarily solved by setting 'num_workers=0' to my dataloader

**Comment by tmabraham** [comment]
I think this was addressed by https://github.com/fastai/fastai/pull/3194
@jph00
