### ISSUE TITLE
NameError: name 'delegates' is not defined

### ISSUE THREAD

**Issue by NouamaneTazi** [fastai/fastai#3090]
Be sure you've searched [the forums](https://forums.fast.ai) for the error message you received. Also, unless you're an experienced fastai developer, first ask on the forums to see if someone else has seen a similar issue already and knows how to solve it. **Only file a bug report here when you're quite confident it's not an issue with your local setup.**

**Please see [this model example](https://github.com/fastai/fastai2/issues/487) of how to fill out an issue correctly.  Please try to emulate that example as appropriate when opening an issue.**

Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
After I just installed fastai and pytorch using `conda install -c fastai -c pytorch -c anaconda fastai anaconda`. I can't import fastai.torch_core

**Error with full stack trace**
```
Traceback (most recent call last):
  File "d:/Projets/JupyterCodes/Python/fastai/Practical Deep Learning for Coders/my_fastai/aa.py", line 5, in <module>
    from fastai.vision.all import *
  File "C:\Users\Nouamane\Anaconda3\lib\site-packages\fastai\vision\all.py", line 1, in <module>
    from . import models
  File "C:\Users\Nouamane\Anaconda3\lib\site-packages\fastai\vision\models\__init__.py", line 1, in <module>
    from . import xresnet
  File "C:\Users\Nouamane\Anaconda3\lib\site-packages\fastai\vision\models\xresnet.py", line 12, in <module>
    from ...torch_basics import *
  File "C:\Users\Nouamane\Anaconda3\lib\site-packages\fastai\torch_basics.py", line 11, in <module>
    from .torch_core import *
  File "C:\Users\Nouamane\Anaconda3\lib\site-packages\fastai\torch_core.py", line 31, in <module>
    @delegates(plt.subplots, keep=True)
NameError: name 'delegates' is not defined
```

I'm using:
```
fastai==2.1.9
fastcore==1.3.13
nbdev==1.0.18
```

**Comment by muellerzr** [comment]
Can you update and try again? I can't recreate this

**Comment by NouamaneTazi** [comment]
I tried updating and reinstalling all the packages. I still get the same error. Where is `delegates` supposed to be imported from?

**Comment by muellerzr** [comment]
How are you importing it?

It comes from `fastai.imports` when we do `from fastcore.all import *`

**Comment by NouamaneTazi** [comment]
When running `from fastcore.all import *`, the function `delegates` is imported correctly. But it seems the way it's imported in fastai/torch_core.py doesnt work for me.
When I added that import to fastai/torch_core.py:
``` 
# Cell
from .imports import *
from .torch_imports import *
from fastcore.all import *
```

I get a different error:
```
    from fastai.vision.all import *
  File "C:\Users\Nouamane\Anaconda3\lib\site-packages\fastai\vision\all.py", line 1, in <module>
    from . import models
  File "C:\Users\Nouamane\Anaconda3\lib\site-packages\fastai\vision\models\__init__.py", line 1, in <module>
    from . import xresnet
  File "C:\Users\Nouamane\Anaconda3\lib\site-packages\fastai\vision\models\xresnet.py", line 12, in <module>
    from ...torch_basics import *
  File "C:\Users\Nouamane\Anaconda3\lib\site-packages\fastai\torch_basics.py", line 11, in <module>
    from .torch_core import *
  File "C:\Users\Nouamane\Anaconda3\lib\site-packages\fastai\torch_core.py", line 82, in <module>
    class ArrayBase(ndarray):
NameError: name 'ndarray' is not defined
```

**Comment by tcapelle** [comment]
this is weird cause the `ndarray` is correctly imported on `imports.py`

**Comment by NouamaneTazi** [comment]
Problem solved!
The issue was that I had a folder in `C:\Users\Nouamane\Anaconda3\Lib\site-packages\fastai` called like this:
``` 
└───imports
        core.py
        torch.py
        __init__.py
``` 
I just deleted the folder and it resolved the problem. (Apparently uninstalling fastai and reinstalling it using pip or anaconda didn't delete it before)

**Comment by GuaiLiHaiDe** [comment]
I have the same problem. Why do you need to delete the `imports` folder?

**Comment by NouamaneTazi** [comment]
Because I think the `imports` folder comes from a previous version. The corch and torch modules are imported in another file
