### ISSUE TITLE
WandbCallback Error: "Tensors must be CUDA and dense" on distributed training

### ISSUE THREAD

**Issue by xanderdunn** [fastai/fastai#3291]
Python 3.7, fastai 2.2.7, fastcore 1.3.19, nbdev not install. I'm running .py scripts on a headless machine.

The `WandbCallback` works as expected when doing a regular, non-distributed run. However, when I do a distributed run as described [here](https://docs.fast.ai/distributed.html):
```python
rank = rank_distrib()
if rank == 0 or rank is None:
    wandb.init(project="plutus_self_supervised", entity="xanderdunn")
    wandb.config.update({"dataset": dataset_id}) # pylint: disable=no-member
    callbacks.append(WandbCallback()) # type: ignore
learn = Learner(cbs=callbacks...)
with learn.distrib_ctx():
    learn.fit_one_cycle(num_epochs, learning_rate)

```
it produces this crash:
```
Traceback (most recent call last):
  File "./pymydata/tsbert__data.py", line 216, in <module>
    run__dataset(distributed=distributed, resume=False)
  File "./pymydata/tsbert__data.py", line 205, in run__dataset
    learn.fit_one_cycle(num_epochs, learning_rate)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/callback/schedule.py", line 112, in fit_o
ne_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 211, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 202, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 196, in _do_epoch
    self._do_epoch_train()
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 188, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 166, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 184, in one_batch
    self._with_events(self._do_one_batch, 'batch', CancelBatchException)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 162, in _with_events
    self(f'after_{event_type}');  final()
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 141, in __call__
    def __call__(self, event_name): L(event_name).map(self._call_one)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastcore/foundation.py", line 154, in map
    def map(self, f, *args, gen=False, **kwargs): return self._new(map_ex(self, f, *args, gen=gen, **kwargs))
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastcore/basics.py", line 666, in map_ex
    return list(res)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastcore/basics.py", line 651, in __call__
    return self.func(*fargs, **kwargs)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/learner.py", line 145, in _call_one
    for cb in self.cbs.sorted('order'): cb(event_name)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/callback/core.py", line 44, in __call__
    if self.run and _run: res = getattr(self, event_name, noop)()
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/callback/wandb.py", line 92, in after_ba$
ch
    wandb.log({'epoch': self._wandb_epoch, 'train_loss': to_detach(self.smooth_loss.clone()), 'raw_loss': to_detach(self.los$
.clone()), **hypers}, step=self._wandb_step)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/torch_core.py", line 225, in to_detach
    return apply(_inner, b, cpu=cpu, gather=gather)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/torch_core.py", line 205, in apply
    res = func(x, *args, **kwargs)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/torch_core.py", line 223, in _inner
    if gather: x = maybe_gather(x)
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/fastai/torch_core.py", line 214, in maybe_gathe$
    torch.distributed.all_gather(res, x.contiguous() if ndim > 0 else x[None])
  File "/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 14$
2, in all_gather
    work = _default_pg.allgather([tensor_list], [tensor])
RuntimeError: Tensors must be CUDA and dense
```

Note that it's important that I add the `WandbCallback` only to one of the distributed learners, otherwise they will all attempt to log the results to wandb. Only one is needed.

It seems to be a device placement issue, but I'm unsure why it appears in distributed training but works fine in non-distributed training. Without the `WandbCallback`, distributed training works as expected. The losses are calculated and shown in the console. 

After just creating an account on forums.fast.ai I'm unable to create any new topics. Is there a new account cool off period? Hence, I'm posting here.

**Comment by xanderdunn** [comment]
For me this issue was resolved by removing the `to_detach()` calls in `WandbCallback`'s `after_batch`

**Comment by kartikeyab** [comment]
@hamelsmu any fix for this? I am still facing this problem while training in DDP environment.

**Comment by tcapelle** [comment]
can you trying passing: `parallel_ctx(bn_sync=False)`

**Comment by kartikeyab** [comment]
What's the exact usage of `parallel_ctx?` I am using `with learn.distrib_ctx(sync_bn=False): learn.fit_one_cycle(...)` in my scripts.

**Comment by hamelsmu** [comment]
Maybe @borisdayma knows

**Comment by borisdayma** [comment]
The error seems to be when extracting the loss with:
```python
{
'train_loss': to_detach(self.smooth_loss.clone()),
'raw_loss': to_detach(self.loss.clone())
}
```

What about [this solution](https://github.com/fastai/fastai/issues/3291#issuecomment-812953720) from above?
Does it work for you?

**Comment by kartikeyab** [comment]
Yes removing the `to_detach()` calls in WandbCallback's `after_batch` did the job. Should I make a PR for this?

**Comment by borisdayma** [comment]
I don't remember why it was added but maybe it's not needed anymore.
I would check everything works well in non distributed mode to be sure (the tests from the notebook should be sufficient). If all is fine a PR would be awesome!

**Comment by kartikeyab** [comment]
Awesome, sounds good!

**Comment by kartikeyab** [comment]
@borisdayma any update on this?
