### ISSUE TITLE
Latest Pillow v8.3.0 breaks conversion Image-->Tensor

### ISSUE THREAD

**Issue by MariusMez** [fastai/fastai#3416]
Since I've upgraded from Pillow v8.2.0 to the latest Pillow version 8.3.0, the predict method from Learner break with this error: 

`RuntimeError: Could not infer dtype of PILImage`

**Comment by MariusMez** [comment]
Seems related to this issue: https://github.com/python-pillow/Pillow/issues/5571

**Comment by nzw0301** [comment]
Pillow v8.3.1 is out, however, we have still an issue as follows.

### Source code

```python
# fastai_sample.py

import urllib

from fastai.vision.all import accuracy
from fastai.vision.all import aug_transforms
from fastai.vision.all import ImageDataLoaders
from fastai.vision.all import Learner
from fastai.vision.all import SimpleCNN
from fastai.vision.all import untar_data
from fastai.vision.all import URLs


opener = urllib.request.build_opener()
opener.addheaders = [("User-agent", "Mozilla/5.0")]
urllib.request.install_opener(opener)


BATCHSIZE = 128
EPOCHS = 10


path = untar_data(URLs.MNIST_SAMPLE)


data = ImageDataLoaders.from_folder(
    path, bs=BATCHSIZE, batch_tfms=None
)

n_channels = [3, 100, 2]

model = SimpleCNN(n_channels)

learn = Learner(
    data,
    model,
    metrics=[accuracy],
)

learn.fit(EPOCHS)
```


### Error

```
python fastai_sample.py
Could not do one pass in your dataloader, there is something wrong in it
epoch     train_loss  valid_loss  accuracy  time
Traceback (most recent call last):---------------------------------------------------------------| 0.00% [0/96 00:00<00:00]
  File "fastai_sample.py", line 38, in <module>
    learn.fit(EPOCHS)
  File "/Users/nzw/Documents/optuna/fastai/fastai/learner.py", line 221, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/Users/nzw/Documents/optuna/fastai/fastai/learner.py", line 163, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/Users/nzw/Documents/optuna/fastai/fastai/learner.py", line 212, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/Users/nzw/Documents/optuna/fastai/fastai/learner.py", line 163, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/Users/nzw/Documents/optuna/fastai/fastai/learner.py", line 206, in _do_epoch
    self._do_epoch_train()
  File "/Users/nzw/Documents/optuna/fastai/fastai/learner.py", line 198, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "/Users/nzw/Documents/optuna/fastai/fastai/learner.py", line 163, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/Users/nzw/Documents/optuna/fastai/fastai/learner.py", line 169, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/Users/nzw/Documents/optuna/fastai/fastai/data/load.py", line 109, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data = next(self.dataset_iter)
  File "/Users/nzw/Documents/optuna/fastai/fastai/data/load.py", line 118, in create_batches
    yield from map(self.do_batch, self.chunkify(res))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/fastcore/basics.py", line 216, in chunked
    res = list(itertools.islice(it, chunk_sz))
  File "/Users/nzw/Documents/optuna/fastai/fastai/data/load.py", line 133, in do_item
    try: return self.after_item(self.create_item(s))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/fastcore/transform.py", line 200, in __call__
    def __call__(self, o): return compose_tfms(o, tfms=self.fs, split_idx=self.split_idx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/fastcore/transform.py", line 150, in compose_tfms
    x = f(x, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/fastcore/transform.py", line 73, in __call__
    def __call__(self, x, **kwargs): return self._call('encodes', x, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/fastcore/transform.py", line 83, in _call
    return self._do_call(getattr(self, fn), x, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/fastcore/transform.py", line 90, in _do_call
    res = tuple(self._do_call(f, x_, **kwargs) for x_ in x)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/fastcore/transform.py", line 90, in <genexpr>
    res = tuple(self._do_call(f, x_, **kwargs) for x_ in x)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/fastcore/transform.py", line 89, in _do_call
    return retain_type(f(x, **kwargs), x, ret)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/fastcore/dispatch.py", line 118, in __call__
    return f(*args, **kwargs)
  File "/Users/nzw/Documents/optuna/fastai/fastai/vision/core.py", line 223, in encodes
    def encodes(self, o:PILBase): return o._tensor_cls(image2tensor(o))
  File "/Users/nzw/Documents/optuna/fastai/fastai/vision/core.py", line 93, in image2tensor
    res = tensor(img)
  File "/Users/nzw/Documents/optuna/fastai/fastai/torch_core.py", line 134, in tensor
    else as_tensor(x, **kwargs) if hasattr(x, '__array__') or is_iter(x)
RuntimeError: Could not infer dtype of PILImage
```

### Installation 

```bash
pip install -U pillow
git clone https://github.com/fastai/fastai
pip install -e "fastai[dev]"
```

## important dependencies: 

```
# on the latest M1 mac book air
pip list | grep -i torch
pytorch-ignite                0.4.5
pytorch-lightning             1.3.8
torch                         1.9.0
torchaudio                    0.9.0
torchmetrics                  0.4.1
torchvision                   0.10.0
```
