### ISSUE TITLE
pip3 install fails

### ISSUE THREAD

**Issue by mkaisercross** [fastai/fastai#3587]
When running pip3 install fastai I get 

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ctd4rias/spacy/

**To Reproduce**
1. Start docker container from ```nvcr.io/nvidia/l4t-ml:r32.6.1-py3``` image
2. pip3 install fastai

**Expected behavior**
Successful installation. No errors.

**Error with full stack trace**

```
Step 1/3 : FROM nvcr.io/nvidia/l4t-ml:r32.6.1-py3
 ---> 4818848f7fee
Step 2/3 : RUN pip3 install fastai
 ---> Running in 48b6edc4d532
Collecting fastai
  Downloading https://files.pythonhosted.org/packages/73/9a/661a804675d913535159d8de99e008d730382802dff12a3e990917aaebbb/fastai-2.5.3-py3-none-any.whl (189kB)
Collecting fastdownload<2,>=0.0.5 (from fastai)
  Downloading https://files.pythonhosted.org/packages/4a/7d/d352ae8f0aa2170f9e0ae4676148675a738cf9fd0c034bd024b82f7df8ed/fastdownload-0.0.5-py3-none-any.whl
Requirement already satisfied: pillow>6.0.0 in /usr/local/lib/python3.6/dist-packages/Pillow-8.3.1-py3.6-linux-aarch64.egg (from fastai)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from fastai)
Collecting fastcore<1.4,>=1.3.22 (from fastai)
  Downloading https://files.pythonhosted.org/packages/50/2b/832378cc02c608798fe13baec2709e70e3796459e6936c4bd3ee7edc4345/fastcore-1.3.27-py3-none-any.whl (56kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from fastai)
Requirement already satisfied: torchvision>=0.8.2 in /usr/local/lib/python3.6/dist-packages/torchvision-0.10.0a0+300a8a4-py3.6-linux-aarch64.egg (from fastai)
Requirement already satisfied: torch<1.11,>=1.7.0 in /usr/local/lib/python3.6/dist-packages (from fastai)
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (from fastai)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from fastai)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from fastai)
Collecting spacy<4 (from fastai)
  Downloading https://files.pythonhosted.org/packages/43/6e/d9fd992ac13c22fd06f5eb4b295320993e0c2baf7fd3042c2732f0daa44e/spacy-3.2.2.tar.gz (1.1MB)
    Complete output from command python setup.py egg_info:

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    """Knowledge-base for entity or concept linking."""
    from cymem.cymem cimport Pool
    ^
    ------------------------------------------------------------

    spacy/kb.pxd:2:0: 'cymem/cymem.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    """Knowledge-base for entity or concept linking."""
    from cymem.cymem cimport Pool
    ^
    ------------------------------------------------------------

    spacy/kb.pxd:2:0: 'cymem/cymem/Pool.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    """Knowledge-base for entity or concept linking."""
    from cymem.cymem cimport Pool
    from preshed.maps cimport PreshMap
    ^
    ------------------------------------------------------------

    spacy/kb.pxd:3:0: 'preshed/maps.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    """Knowledge-base for entity or concept linking."""
    from cymem.cymem cimport Pool
    from preshed.maps cimport PreshMap
    ^
    ------------------------------------------------------------

    spacy/kb.pxd:3:0: 'preshed/maps/PreshMap.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from libcpp.vector cimport vector
    from preshed.maps cimport PreshMap
    from cymem.cymem cimport Pool
    from murmurhash.mrmr cimport hash64
    ^
    ------------------------------------------------------------

    spacy/vocab.pxd:4:0: 'murmurhash/mrmr.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from libcpp.vector cimport vector
    from preshed.maps cimport PreshMap
    from cymem.cymem cimport Pool
    from murmurhash.mrmr cimport hash64
    ^
    ------------------------------------------------------------

    spacy/vocab.pxd:4:0: 'murmurhash/mrmr/hash64.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        unsigned char[8] s
        unsigned char* p


    cdef class StringStore:
        cdef Pool mem
            ^
    ------------------------------------------------------------

    spacy/strings.pxd:23:9: 'Pool' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

    cdef class StringStore:
        cdef Pool mem

        cdef vector[hash_t] keys
        cdef public PreshMap _map
                   ^
    ------------------------------------------------------------

    spacy/strings.pxd:26:16: 'PreshMap' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

    cdef class StringStore:
        cdef Pool mem

        cdef vector[hash_t] keys
        cdef public PreshMap _map
                            ^
    ------------------------------------------------------------

    spacy/strings.pxd:26:25: C attribute of type '<error>' cannot be accessed from Python

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from .strings cimport StringStore
    from .typedefs cimport attr_t, hash_t


    cdef class Morphology:
        cdef readonly Pool mem
                     ^
    ------------------------------------------------------------

    spacy/morphology.pxd:12:18: 'Pool' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from .strings cimport StringStore
    from .typedefs cimport attr_t, hash_t


    cdef class Morphology:
        cdef readonly Pool mem
                          ^
    ------------------------------------------------------------

    spacy/morphology.pxd:12:23: C attribute of type '<error>' cannot be accessed from Python

    Error compiling Cython file:
    ------------------------------------------------------------
    ...


    cdef class Morphology:
        cdef readonly Pool mem
        cdef readonly StringStore strings
        cdef PreshMap tags # Keyed by hash, value is pointer to tag
            ^
    ------------------------------------------------------------

    spacy/morphology.pxd:14:9: 'PreshMap' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        bint is_lex
        int length


    cdef class Vocab:
        cdef Pool mem
            ^
    ------------------------------------------------------------

    spacy/vocab.pxd:27:9: 'Pool' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef readonly int length
        cdef public object _unused_object # TODO remove in v4, see #9150
        cdef public object lex_attr_getters
        cdef public object cfg

        cdef const LexemeC* get(self, Pool mem, str string) except NULL
                                     ^
    ------------------------------------------------------------

    spacy/vocab.pxd:39:34: 'Pool' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef public object _unused_object # TODO remove in v4, see #9150
        cdef public object lex_attr_getters
        cdef public object cfg

        cdef const LexemeC* get(self, Pool mem, str string) except NULL
        cdef const LexemeC* get_by_orth(self, Pool mem, attr_t orth) except NULL
                                             ^
    ------------------------------------------------------------

    spacy/vocab.pxd:40:42: 'Pool' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        cdef const LexemeC* get(self, Pool mem, str string) except NULL
        cdef const LexemeC* get_by_orth(self, Pool mem, attr_t orth) except NULL
        cdef const TokenC* make_fused_token(self, substrings) except NULL

        cdef const LexemeC* _new_lexeme(self, Pool mem, str string) except NULL
                                             ^
    ------------------------------------------------------------

    spacy/vocab.pxd:43:42: 'Pool' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef const LexemeC* get_by_orth(self, Pool mem, attr_t orth) except NULL
        cdef const TokenC* make_fused_token(self, substrings) except NULL

        cdef const LexemeC* _new_lexeme(self, Pool mem, str string) except NULL
        cdef int _add_lex_to_vocab(self, hash_t key, const LexemeC* lex) except -1
        cdef const LexemeC* _new_lexeme(self, Pool mem, str string) except NULL
                                             ^
    ------------------------------------------------------------

    spacy/vocab.pxd:45:42: 'Pool' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        cdef const LexemeC* _new_lexeme(self, Pool mem, str string) except NULL
        cdef int _add_lex_to_vocab(self, hash_t key, const LexemeC* lex) except -1
        cdef const LexemeC* _new_lexeme(self, Pool mem, str string) except NULL

        cdef PreshMap _by_orth
            ^
    ------------------------------------------------------------

    spacy/vocab.pxd:47:9: 'PreshMap' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef hash_t alias_hash
        cdef float prior_prob


    cdef class KnowledgeBase:
        cdef Pool mem
            ^
    ------------------------------------------------------------

    spacy/kb.pxd:30:9: 'Pool' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        # This maps 64bit keys (hash of unique entity string)
        # to 64bit values (position of the _KBEntryC struct in the _entries vector).
        # The PreshMap is pretty space efficient, as it uses open addressing. So
        # the only overhead is the vacancy rate, which is approximately 30%.
        cdef PreshMap _entry_index
            ^
    ------------------------------------------------------------

    spacy/kb.pxd:38:9: 'PreshMap' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        # Storing 1m entries would take 41.6mb under this scheme.
        cdef entry_vec _entries

        # This maps 64bit keys (hash of unique alias string)
        # to 64bit values (position of the _AliasC struct in the _aliases_table vector).
        cdef PreshMap _alias_index
            ^
    ------------------------------------------------------------

    spacy/kb.pxd:48:9: 'PreshMap' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        DOCS: https://spacy.io/api/kb
        """

        def __init__(self, Vocab vocab, entity_vector_length):
            """Create a KnowledgeBase."""
            self.mem = Pool()
                      ^
    ------------------------------------------------------------

    spacy/kb.pyx:89:19: 'Pool' is not a constant, variable or function identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        def __init__(self, Vocab vocab, entity_vector_length):
            """Create a KnowledgeBase."""
            self.mem = Pool()
            self.entity_vector_length = entity_vector_length
            self._entry_index = PreshMap()
                               ^
    ------------------------------------------------------------

    spacy/kb.pyx:91:28: 'PreshMap' is not a constant, variable or function identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __init__(self, Vocab vocab, entity_vector_length):
            """Create a KnowledgeBase."""
            self.mem = Pool()
            self.entity_vector_length = entity_vector_length
            self._entry_index = PreshMap()
            self._alias_index = PreshMap()
                               ^
    ------------------------------------------------------------

    spacy/kb.pyx:92:28: 'PreshMap' is not a constant, variable or function identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            self._alias_index = PreshMap()
            self.vocab = vocab
            self._create_empty_vectors(dummy_hash=self.vocab.strings[""])

        def initialize_entities(self, int64_t nr_entities):
            self._entry_index = PreshMap(nr_entities + 1)
                               ^
    ------------------------------------------------------------

    spacy/kb.pyx:97:28: 'PreshMap' is not a constant, variable or function identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        def initialize_vectors(self, int64_t nr_entities):
            self._vectors_table = float_matrix(nr_entities + 1)

        def initialize_aliases(self, int64_t nr_aliases):
            self._alias_index = PreshMap(nr_aliases + 1)
                               ^
    ------------------------------------------------------------

    spacy/kb.pyx:104:28: 'PreshMap' is not a constant, variable or function identifier
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ctd4rias/spacy/setup.py", line 225, in <module>
        setup_package()
      File "/tmp/pip-build-ctd4rias/spacy/setup.py", line 212, in setup_package
        ext_modules = cythonize(ext_modules, compiler_directives=COMPILER_DIRECTIVES)
      File "/usr/local/lib/python3.6/dist-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
        cythonize_one(*args)
      File "/usr/local/lib/python3.6/dist-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: spacy/kb.pyx
    Copied /tmp/pip-build-ctd4rias/spacy/setup.cfg -> /tmp/pip-build-ctd4rias/spacy/spacy/tests/package
    Copied /tmp/pip-build-ctd4rias/spacy/pyproject.toml -> /tmp/pip-build-ctd4rias/spacy/spacy/tests/package
    Cythonizing sources
    Compiling spacy/training/example.pyx because it changed.
    Compiling spacy/parts_of_speech.pyx because it changed.
    Compiling spacy/strings.pyx because it changed.
    Compiling spacy/lexeme.pyx because it changed.
    Compiling spacy/vocab.pyx because it changed.
    Compiling spacy/attrs.pyx because it changed.
    Compiling spacy/kb.pyx because it changed.
    Compiling spacy/ml/parser_model.pyx because it changed.
    Compiling spacy/morphology.pyx because it changed.
    Compiling spacy/pipeline/dep_parser.pyx because it changed.
    Compiling spacy/pipeline/morphologizer.pyx because it changed.
    Compiling spacy/pipeline/multitask.pyx because it changed.
    Compiling spacy/pipeline/ner.pyx because it changed.
    Compiling spacy/pipeline/pipe.pyx because it changed.
    Compiling spacy/pipeline/trainable_pipe.pyx because it changed.
    Compiling spacy/pipeline/sentencizer.pyx because it changed.
    Compiling spacy/pipeline/senter.pyx because it changed.
    Compiling spacy/pipeline/tagger.pyx because it changed.
    Compiling spacy/pipeline/transition_parser.pyx because it changed.
    Compiling spacy/pipeline/_parser_internals/arc_eager.pyx because it changed.
    Compiling spacy/pipeline/_parser_internals/ner.pyx because it changed.
    Compiling spacy/pipeline/_parser_internals/nonproj.pyx because it changed.
    Compiling spacy/pipeline/_parser_internals/_state.pyx because it changed.
    Compiling spacy/pipeline/_parser_internals/stateclass.pyx because it changed.
    Compiling spacy/pipeline/_parser_internals/transition_system.pyx because it changed.
    Compiling spacy/pipeline/_parser_internals/_beam_utils.pyx because it changed.
    Compiling spacy/tokenizer.pyx because it changed.
    Compiling spacy/training/align.pyx because it changed.
    Compiling spacy/training/gold_io.pyx because it changed.
    Compiling spacy/tokens/doc.pyx because it changed.
    Compiling spacy/tokens/span.pyx because it changed.
    Compiling spacy/tokens/token.pyx because it changed.
    Compiling spacy/tokens/span_group.pyx because it changed.
    Compiling spacy/tokens/graph.pyx because it changed.
    Compiling spacy/tokens/morphanalysis.pyx because it changed.
    Compiling spacy/tokens/_retokenize.pyx because it changed.
    Compiling spacy/matcher/matcher.pyx because it changed.
    Compiling spacy/matcher/phrasematcher.pyx because it changed.
    Compiling spacy/matcher/dependencymatcher.pyx because it changed.
    Compiling spacy/symbols.pyx because it changed.
    Compiling spacy/vectors.pyx because it changed.
    [ 1/41] Cythonizing spacy/attrs.pyx
    [ 2/41] Cythonizing spacy/kb.pyx

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ctd4rias/spacy/
1 error occurred:
	* Status: The command '/bin/sh -c pip3 install fastai' returned a non-zero code: 1, Code: 1
```
**Additional context**

I am trying to install this on Nvidia Jetson Nano 4GB. The ```nvcr.io/nvidia/l4t-ml:r32.6.1-py3``` image is working fine and I am able to access the python cli and notebooks fine. Just can't get fastai installed for some reason.

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

$ uname -a
Linux jetson-nano-001 4.9.253-tegra #1 SMP PREEMPT Mon Jul 26 12:13:06 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by jph00** [comment]
That appears to be a spacy issue.
