### ISSUE TITLE
Accelerate notebook launcher fails with PyTorch dataloaders

### ISSUE THREAD

**Issue by DanteOz** [fastai/fastai#3665]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
The Accelerate notebook launcher fails when using PyTorch dataloaders. The equivalent script version of the notebook successfully runs using `accelerate launch`.

**To Reproduce**

1. Configure accelerate.
Using default configuration create with `write_basic_config()` from [notebook tutorial](https://docs.fast.ai/tutorial.distributed).

2. Run successful script to verify environment. 
https://gist.github.com/DanteOz/2713a7b993b696a29676051515a5873c

3. Run failing notebook launcher to reproduce bug.
https://gist.github.com/DanteOz/fc1fb96b917dd6bec19e71aca07339ca

**Expected behavior**
I would expect the notebook launcher to successfully launch `train()` function across multiple GPUs. 

**Error with full stack trace**

```
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
---------------------------------------------------------------------------
ProcessRaisedException                    Traceback (most recent call last)
/home/dev/projects/scratch/fastai_accel/nb_launch.ipynb Cell 7' in <cell line: 3>()
      <a href='vscode-notebook-cell://ssh-remote%2Beurus/home/dev/projects/scratch/fastai_accel/nb_launch.ipynb#ch0000009vscode-remote?line=0'>1</a> args = (path, )
      <a href='vscode-notebook-cell://ssh-remote%2Beurus/home/dev/projects/scratch/fastai_accel/nb_launch.ipynb#ch0000009vscode-remote?line=1'>2</a> # train(*args)
----> <a href='vscode-notebook-cell://ssh-remote%2Beurus/home/dev/projects/scratch/fastai_accel/nb_launch.ipynb#ch0000009vscode-remote?line=2'>3</a> notebook_launcher(train, args, num_processes=2)

File ~/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/launchers.py:129, in notebook_launcher(function, args, num_processes, use_fp16, mixed_precision, use_port)
    <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/launchers.py?line=125'>126</a>         launcher = PrepareForLaunch(function, distributed_type="MULTI_GPU")
    <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/launchers.py?line=127'>128</a>         print(f"Launching training on {num_processes} GPUs.")
--> <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/launchers.py?line=128'>129</a>         start_processes(launcher, args=args, nprocs=num_processes, start_method="fork")
    <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/launchers.py?line=130'>131</a> else:
    <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/launchers.py?line=131'>132</a>     # No need for a distributed launch otherwise as it's either CPU or one GPU.
    <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/launchers.py?line=132'>133</a>     if torch.cuda.is_available():

File ~/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/multiprocessing/spawn.py:198, in start_processes(fn, args, nprocs, join, daemon, start_method)
    <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/multiprocessing/spawn.py?line=194'>195</a>     return context
    <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/multiprocessing/spawn.py?line=196'>197</a> # Loop on join until it returns True or raises an exception.
--> <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/multiprocessing/spawn.py?line=197'>198</a> while not context.join():
    <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/multiprocessing/spawn.py?line=198'>199</a>     pass

File ~/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/multiprocessing/spawn.py:160, in ProcessContext.join(self, timeout)
    <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/multiprocessing/spawn.py?line=157'>158</a> msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
    <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/multiprocessing/spawn.py?line=158'>159</a> msg += original_trace
--> <a href='file:///home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/multiprocessing/spawn.py?line=159'>160</a> raise ProcessRaisedException(msg, error_index, failed_process.pid)

ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/utils/launch.py", line 55, in __call__
    self.launcher(*args)
  File "/tmp/ipykernel_281038/2110902693.py", line 26, in train
    with learner.distrib_ctx(in_notebook=True):
  File "/home/dev/miniconda3/envs/fastai/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/media/nvme1n1p1/projects/fastai/fastai/distributed.py", line 207, in distrib_ctx
    setup_distrib(cuda_id)
  File "/media/nvme1n1p1/projects/fastai/fastai/distributed.py", line 68, in setup_distrib
    torch.cuda.set_device(int(gpu))
  File "/home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/dev/miniconda3/envs/fastai/lib/python3.10/site-packages/torch/cuda/__init__.py", line 206, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

**Additional context**
Fastai installed using editable install from [my fork](https://github.com/DanteOz/fastai) of fastai. Repo was update to date at time of discovering bug (a0bde06).

**Comment by DanteOz** [comment]
@muellerzr

**Comment by muellerzr** [comment]
I've found a solution, but FYI @DanteOz, `df` needs to be on all processes so it's available to everyone all the time. You need to move that outside of the function and call it in a cell.
