### ISSUE TITLE
AttributeError: Custom classes or functions exported with your 'Learner' are not available in the namespace currently.

### ISSUE THREAD

**Issue by danielbellsa** [fastai/fastai#3709]
Version: **2.7.4**

```python
from fastai.vision.all import *
# from fastai.learner import load_learner

learn = load_learner('export_2.pkl', cpu=False)
```

Traceback:
```
(project) me@ubuntu-pcs:~/PycharmProjects/project$ python main.py 
Traceback (most recent call last):
  File "/home/me/PycharmProjects/project/main.py", line 3, in <module>
    from src.train.train_model import train
  File "/home/me/PycharmProjects/project/src/train/train_model.py", line 11, in <module>
    learn = load_learner('yasmine-sftp/export_2.pkl', cpu=False)  # to run on GPU
  File "/home/me/miniconda3/envs/project/lib/python3.9/site-packages/fastai/learner.py", line 413, in load_learner
    try: res = torch.load(fname, map_location=map_loc, pickle_module=pickle_module)
  File "/home/me/miniconda3/envs/project/lib/python3.9/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/me/miniconda3/envs/project/lib/python3.9/site-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/home/me/miniconda3/envs/project/lib/python3.9/site-packages/torch/serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
AttributeError: Custom classes or functions exported with your `Learner` are not available in the namespace currently.
Please re-declare or import them before calling `load_learner`:
        Can't get attribute 'Tf' on <module '__main__' from '/home/me/PycharmProjects/project/main.py'>
```

---

This solution, as suggest [here](https://stackoverflow.com/a/54058174/19313052), didn't work:
```
!pip install --upgrade git+https://github.com/fastai/fastai.git
```

**Comment by jph00** [comment]
Suggest asking for help on the forums.
