### ISSUE TITLE
Cannot install fastai on anaconda/windows

### ISSUE THREAD

**Issue by arame** [fastai/fastai#3862]
I tried to install fastai via anaconda on my windows terminal.
`conda install -c fastchan fastai anaconda`
When I attempt to run my code on my PC I get the error message;

ModuleNotFoundError: No module named 'fastai'

**Comment by deven367** [comment]
Can you make sure you are running the code in the correct environment?

**Comment by veronicanatividade** [comment]
Hi! Amazing project. I'm looking forward to using it. 

I'm new to Python and machine learning, so I apologise in advance if my question is naive. I have tried to install it with Conda and in jupyter notebook. I successfully installed Fastai. However, I can import Fastai, but I can't import fastsom. I changed the decoding, yet, it keeps raising the following error. So, I kindly ask you to show me my mistake, please. Thank you.

error: subprocess-exited-with-error
  
  Ã— python setup.py egg_info did not run successfully.
  â”‚ exit code: 1
  â•°â”€> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\veron\AppData\Local\Temp\pip-install-efpuwbrv\sklearn_a3f614e103384df7a4b26a825228d5c3\setup.py", line 10, in <module>
          LONG_DESCRIPTION = f.read()
        File "C:\Users\veron\anaconda3\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Ã— Encountered error while generating package metadata.
â•°â”€> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by 0xSushmanth** [comment]
> 
try this

```bash
conda install -c nvidia fastai anaconda
```

**Comment by arame** [comment]
> 

For that i get this error
`E:\Python>conda install -c nvidia fastai anaconda
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:       

  - fastai

Current channels:

  - https://conda.anaconda.org/nvidia/win-64
  - https://conda.anaconda.org/nvidia/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to`

**Comment by mystvearn** [comment]
> > 
> 
> For that i get this error `E:\Python>conda install -c nvidia fastai anaconda Retrieving notices: ...working... done Collecting package metadata (current_repodata.json): done Solving environment: failed with initial frozen solve. Retrying with flexible solve. Collecting package metadata (repodata.json): done Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
> * fastai
> 
> Current channels:
> 
> * https://conda.anaconda.org/nvidia/win-64
> * https://conda.anaconda.org/nvidia/noarch
> * https://repo.anaconda.com/pkgs/main/win-64
> * https://repo.anaconda.com/pkgs/main/noarch
> * https://repo.anaconda.com/pkgs/r/win-64
> * https://repo.anaconda.com/pkgs/r/noarch
> * https://repo.anaconda.com/pkgs/msys2/win-64
> * https://repo.anaconda.com/pkgs/msys2/noarch
> 
> To search for alternate channels that may provide the conda package you're looking for, navigate to`

I'm having the same error running "conda install -c nvidia fastai anaconda".
