### ISSUE TITLE
imdb_scripts/pretrain_lm.py fails

### ISSUE THREAD

**Issue by FrankWork** [fastai/fastai#590]
```
dir_path data/0625/lm; cuda_id 0; cl 8; bs 64; backwards False; lr 0.001; sampled True; pretrain_id
Traceback (most recent call last):
  File "ulmfit/pretrain_lm.py", line 55, in <module>
    if __name__ == '__main__': fire.Fire(train_lm)
  File "~/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "~/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "~/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "ulmfit/pretrain_lm.py", line 44, in train_lm
    learner,crit = get_learner(drops, 15000, sampled, md, em_sz, nh, nl, opt_fn, tprs)
  File "~/sentiment/ulmfit/sampled_sm.py", line 86, in get_learner
    m = to_gpu(get_language_model(md.n_tok, em_sz, nh, nl, md.pad_idx, decode_train=False, dropouts=drops))
  File "~/sentiment/ulmfit/sampled_sm.py", line 47, in get_language_model
    dropouti=dropouts[0], wdrop=dropouts[2], dropoute=dropouts[3], dropouth=dropouts[4])
TypeError: __init__() got an unexpected keyword argument 'nhid'
```

**Comment by FrankWork** [comment]
In `imdb_scripts/sampled_sm.py`, in function `get_language_model`, change the code as following

```
rnn_enc = RNN_Encoder(n_tok, em_sz, n_hid=nhid, n_layers=nlayers, pad_token=pad_token,
```

It will solve the 'nhid' problem.

**Comment by FrankWork** [comment]
But I got another problem

```
File "ulmfit/pretrain_lm.py", line 51, in train_lm
    learner.fit(lrs, 1, wds=wd, use_clr=(32,10), cycle_len=cl)
  File "/fastai-0.7.0-py3.6.egg/fastai/text.py", line 211, in fit 
    def fit(self, *args, **kwargs): return super().fit(*args, **kwargs, seq_first=True)
  File "/fastai-0.7.0-py3.6.egg/fastai/learner.py", line 287, in fit 
    return self.fit_gen(self.model, self.data, layer_opt, n_cycle, **kwargs)
  File "/fastai-0.7.0-py3.6.egg/fastai/learner.py", line 234, in fit_gen
    swa_eval_freq=swa_eval_freq, **kwargs)
  File "/fastai-0.7.0-py3.6.egg/fastai/model.py", line 140, in fit 
    loss = model_stepper.step(V(x),V(y), epoch)
  File "/fastai-0.7.0-py3.6.egg/fastai/model.py", line 50, in step
    output = self.m(*xs)
  File "/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/fastai-0.7.0-py3.6.egg/fastai/lm_rnn.py", line 98, in forward
    emb = self.encoder_with_dropout(input, dropout=self.dropoute if self.training else 0)
  File "/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/fastai-0.7.0-py3.6.egg/fastai/rnn_reg.py", line 188, in forward
    self.embed.norm_type, self.embed.scale_grad_by_freq, self.embed.sparse)
  File "/torch/nn/_functions/thnn/sparse.py", line 59, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, !torch.cuda.FloatTensor!), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)

```

**Comment by sgugger** [comment]
Not sure what you're referring to since what you propose is what is inside the sampled_sm.py. Can you suggest a PR?

**Comment by sgugger** [comment]
Oh, I didn't catch those underscores, thanks for making a PR, it's clearer now!

**Comment by cindyll00** [comment]
dir_path data/wiki/en/; cuda_id 0; cl 12; bs 64; backwards False; lr 0.001; sampled True; pretrain_id
Traceback (most recent call last):
  File "pretrain_lm.py", line 53, in <module>
    if __name__ == '__main__': fire.Fire(train_lm)
  File "/home/cindy.ll/.conda/envs/ulm_env/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/cindy.ll/.conda/envs/ulm_env/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/cindy.ll/.conda/envs/ulm_env/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "pretrain_lm.py", line 42, in train_lm
    learner,crit = get_learner(drops, 15000, sampled, md, em_sz, nh, nl, opt_fn, tprs)
  File "/home/cindy.ll/codes/fastai/courses/dl2/imdb_scripts/sampled_sm.py", line 86, in get_learner
    m = to_gpu(get_language_model(md.n_tok, em_sz, nh, nl, md.pad_idx, decode_train=False, dropouts=drops))
  File "/home/cindy.ll/codes/fastai/courses/dl2/imdb_scripts/sampled_sm.py", line 47, in get_language_model
    dropouti=dropouts[0], wdrop=dropouts[2], dropoute=dropouts[3], dropouth=dropouts[4])
TypeError: __init__() got an unexpected keyword argument 'n_hid'

**Comment by sgugger** [comment]
You need to use the last version of the fastai library, just git pull in the fastai directory to update it.

**Comment by cindyll00** [comment]
@sgugger Yes, i  used the last version, but i still have this bug.why?

**Comment by sgugger** [comment]
You should go on the [forum](http://forums.fast.ai) for more help, but your error comes from get_model refusing n_hid as an argument. In older versions it used to be nhid that's why I told you to double check you have the latest library.

**Comment by cindyll00** [comment]
Thanks for help. I solved the 'n_hid' problem.

**Comment by faysalhossain2007** [comment]
how did you solve that? @cindyll00

**Comment by iamsile** [comment]
> how did you solve that? @cindyll00

modify code like this:

rnn_enc = RNN_Encoder(n_tok, em_sz, nhid=nhid, nlayers=nlayers, pad_token=pad_token,
