### ISSUE TITLE
the error message after using pip install git+https://github.com/fastai/fastai.git

### ISSUE THREAD

**Issue by wenouyang** [fastai/fastai#686]
I tried to install fastai using `pip install git+https://github.com/fastai/fastai.git`, but I got the following error message.  These error messages still remains even I installed Pytorch successfully using `conda install -c soumith pytorch`
```

Collecting testpath (from fastai==0.7.0)
  Using cached https://files.pythonhosted.org/packages/15/19/d7bc380c479a184e4a5a9ce516e4e2a773165f89b445f7cdced83d94de25/testpath-0.3.1-py2.py3-none-any.whl
Collecting torch<0.4 (from fastai==0.7.0)
  Using cached https://files.pythonhosted.org/packages/5f/e9/bac4204fe9cb1a002ec6140b47f51affda1655379fe302a1caef421f9846/torch-0.1.2.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shuxi\AppData\Local\Temp\pip-install-lr2h08vx\torch\setup.py", line 11, in <module>
        raise RuntimeError(README)
    RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

    Please follow the instructions at http://pytorch.org/ to install with miniconda instead.


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\shuxi\AppData\Local\Temp\pip-install-lr2h08vx\torch\

```

**Comment by sgugger** [comment]
Please use the [forum](http://forums.fast.ai/) for this. There is also detailed explanation on how to install without pip.
