### ISSUE TITLE
Getting Error while Training and also finetune process is very slow

### ISSUE THREAD

**Issue by faysalhossain2007** [fastai/fastai#703]
I am getting the following error while trying to train the model. I am running the code in the GPU. Also I am facing another problem during fine tunning. It is taking a lot time for fine tuned the pre-trained model. Any suggestion to make the process more faster? P.S. I have loaded cuda before running the process. And check GPU by nvidia-smi.

 ```
   : /localtmp/fs5ve/fastai/courses/dl2/imdb_scripts ; python train_clas.py data/wiki/en 0 --lm-id pretrain_wt103 --clas-id pretrain_wt103 --cl 5
    dir_path data/wiki/en; cuda_id 0; lm_id pretrain_wt103; clas_id pretrain_wt103; bs 64; cl 5; backwards False; dropmult 1.0 unfreeze True startat 0; bpe False; use_clr True;use_regular_schedule False; use_discriminative True; last False;chain_thaw False; from_scratch False; train_file_id
    Traceback (most recent call last):
      File "train_clas.py", line 148, in <module>
        if __name__ == '__main__': fire.Fire(train_clas)
      File "/zf18/fs5ve/.conda/envs/fastai/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
        component_trace = _Fire(component, args, context, name)
      File "/zf18/fs5ve/.conda/envs/fastai/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
        component, remaining_args)
      File "/zf18/fs5ve/.conda/envs/fastai/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
        result = fn(*varargs, **kwargs)
      File "train_clas.py", line 51, in train_clas
        assert trn_lbls.shape[1] == 1 and val_lbls.shape[1] == 1, 'This classifier uses cross entropy loss and only support single label samples'
    IndexError: tuple index out of range
    (fastai)
```

**Comment by sgugger** [comment]
Please use the [forum](http://forums.fast.ai/) for this. You might also want to share more of your code so that people can help you more easily.
