### ISSUE TITLE
conda installation breaks with undefined symbol: zmq_curve_public

### ISSUE THREAD

**Issue by ponomarevsy** [fastai/fastai#772]
Dear fastai experts,

My conda (anaconda3/4.3.1) installation of fastai breaks with "undefined symbol: zmq_curve_public":
```
» conda env create -f environment.yml
Using Anaconda API: https://api.anaconda.org
Solving environment: done

Downloading and Extracting Packages
chardet-3.0.4        | 188 KB    | ########################################################### | 100%
gettext-0.19.8.1     | 3.5 MB    | ########################################################### | 100%
libxslt-1.1.32       | 511 KB    | ########################################################### | 100%
msgpack-numpy-0.4.3. | 8 KB      | ########################################################### | 100%
locket-0.2.0         | 6 KB      | ########################################################### | 100%
mkl-2019.0           | 204.4 MB  | ########################################################### | 100%
jupyter_latex_envs-1 | 753 KB    | ########################################################### | 100%
backcall-0.1.0       | 13 KB     | ########################################################### | 100%
libtiff-4.0.9        | 521 KB    | ########################################################### | 100%
cffi-1.11.5          | 404 KB    | ########################################################### | 100%
libsodium-1.0.16     | 536 KB    | ########################################################### | 100%
jupyter_highlight_se | 13 KB     | ########################################################### | 100%
wrapt-1.10.11        | 74 KB     | ########################################################### | 100%
patsy-0.5.0          | 184 KB    | ########################################################### | 100%
traitlets-4.3.2      | 131 KB    | ########################################################### | 100%
libffi-3.2.1         | 51 KB     | ########################################################### | 100%
sip-4.18.1           | 266 KB    | ########################################################### | 100%
pygments-2.2.0       | 622 KB    | ########################################################### | 100%
pandoc-1.19.2        | 17.8 MB   | ########################################################### | 100%
regex-2017.11.09     | 670 KB    | ########################################################### | 100%
entrypoints-0.2.3    | 9 KB      | ########################################################### | 100%
thinc-6.10.3         | 3.5 MB    | ########################################################### | 100%
libuuid-2.32.1       | 24 KB     | ########################################################### | 100%
zeromq-4.2.5         | 939 KB    | ########################################################### | 100%
python-3.6.6         | 20.9 MB   | ########################################################### | 100%
jupyter-1.0.0        | 6 KB      | ########################################################### | 100%
cryptography-vectors | 30.5 MB   | ########################################################### | 100%
pluggy-0.7.1         | 14 KB     | ########################################################### | 100%
jupyter_console-5.2. | 34 KB     | ########################################################### | 100%
six-1.11.0           | 21 KB     | ########################################################### | 100%
webencodings-0.5.1   | 12 KB     | ########################################################### | 100%
bokeh-0.13.0         | 5.0 MB    | ########################################################### | 100%
prompt_toolkit-1.0.1 | 154 KB    | ########################################################### | 100%
spacy-2.0.12         | 53.0 MB   | ########################################################### | 100%
intel-openmp-2019.0  | 721 KB    | ########################################################### | 100%
qt-5.6.2             | 44.3 MB   | ########################################################### | 100%
statsmodels-0.9.0    | 15.9 MB   | ########################################################### | 100%
testpath-0.3.1       | 89 KB     | ########################################################### | 100%
libxml2-2.9.8        | 1.8 MB    | ########################################################### | 100%
mistune-0.8.3        | 873 KB    | ########################################################### | 100%
cymem-1.31.2         | 67 KB     | ########################################################### | 100%
sortedcontainers-2.0 | 24 KB     | ########################################################### | 100%
cryptography-2.3.1   | 960 KB    | ########################################################### | 100%
yaml-0.1.7           | 77 KB     | ########################################################### | 100%
pycparser-2.18       | 84 KB     | ########################################################### | 100%
jedi-0.12.1          | 224 KB    | ########################################################### | 100%
msgpack-python-0.5.6 | 306 KB    | ########################################################### | 100%
terminado-0.8.1      | 22 KB     | ########################################################### | 100%
libiconv-1.15        | 2.0 MB    | ########################################################### | 100%
asn1crypto-0.24.0    | 154 KB    | ########################################################### | 100%
cudnn-7.2.1          | 322.8 MB  | ########################################################### | 100%
pcre-8.41            | 243 KB    | ########################################################### | 100%
pickleshare-0.7.4    | 11 KB     | ########################################################### | 100%
plac-0.9.6           | 18 KB     | ########################################################### | 100%
more-itertools-4.3.0 | 82 KB     | ########################################################### | 100%
matplotlib-2.2.3     | 9.2 MB    | ########################################################### | 100%
urllib3-1.23         | 153 KB    | ########################################################### | 100%
cytoolz-0.9.0.1      | 1.3 MB    | ########################################################### | 100%
pexpect-4.6.0        | 74 KB     | ########################################################### | 100%
requests-2.19.1      | 94 KB     | ########################################################### | 100%
jupyter_contrib_core | 15 KB     | ########################################################### | 100%
jupyter_nbextensions | 470 KB    | ########################################################### | 100%
cuda90-1.0           | 3 KB      | ########################################################### | 100%
wheel-0.31.1         | 61 KB     | ########################################################### | 100%
idna-2.7             | 131 KB    | ########################################################### | 100%
partd-0.3.8          | 14 KB     | ########################################################### | 100%
seaborn-0.9.0        | 159 KB    | ########################################################### | 100%
pyyaml-3.13          | 460 KB    | ########################################################### | 100%
dill-0.2.8.2         | 109 KB    | ########################################################### | 100%
ipython-6.5.0        | 1.0 MB    | ########################################################### | 100%
cudatoolkit-9.2      | 351.0 MB  | ########################################################### | 100%
pytest-3.8.0         | 315 KB    | ########################################################### | 100%
toolz-0.9.0          | 45 KB     | ########################################################### | 100%
packaging-17.1       | 20 KB     | ########################################################### | 100%
parso-0.3.1          | 59 KB     | ########################################################### | 100%
jpeg-9c              | 229 KB    | ########################################################### | 100%
pytorch-0.3.1        | 486.5 MB  | ########################################################### | 100%
nbconvert-5.4.0      | 324 KB    | ########################################################### | 100%
path.py-11.0.1       | 27 KB     | ########################################################### | 100%
ujson-1.35           | 66 KB     | ########################################################### | 100%
dask-core-0.19.1     | 491 KB    | ########################################################### | 100%
py-1.6.0             | 63 KB     | ########################################################### | 100%
sqlite-3.24.0        | 1.5 MB    | ########################################################### | 100%
distributed-1.23.1   | 828 KB    | ########################################################### | 100%
pillow-5.2.0         | 1006 KB   | ########################################################### | 100%
defusedxml-0.5.0     | 40 KB     | ########################################################### | 100%
ptyprocess-0.6.0     | 22 KB     | ########################################################### | 100%
pandocfilters-1.4.2  | 9 KB      | ########################################################### | 100%
jinja2-2.10          | 89 KB     | ########################################################### | 100%
widgetsnbextension-3 | 1.7 MB    | ########################################################### | 100%
pyopenssl-18.0.0     | 80 KB     | ########################################################### | 100%
prometheus_client-0. | 27 KB     | ########################################################### | 100%
pip-18.0             | 1.8 MB    | ########################################################### | 100%
dask-0.19.1          | 3 KB      | ########################################################### | 100%
notebook-5.6.0       | 7.3 MB    | ########################################################### | 100%
ipykernel-4.9.0      | 145 KB    | ########################################################### | 100%
nbformat-4.4.0       | 91 KB     | ########################################################### | 100%
pysocks-1.6.8        | 22 KB     | ########################################################### | 100%
heapdict-1.0.0       | 5 KB      | ########################################################### | 100%
freetype-2.9.1       | 800 KB    | ########################################################### | 100%
olefile-0.46         | 31 KB     | ########################################################### | 100%
testfixtures-6.3.0   | 55 KB     | ########################################################### | 100%
murmurhash-0.28.0    | 39 KB     | ########################################################### | 100%
python-dateutil-2.7. | 202 KB    | ########################################################### | 100%
tornado-4.5.3        | 628 KB    | ########################################################### | 100%
atomicwrites-1.1.5   | 9 KB      | ########################################################### | 100%
pyzmq-17.1.2         | 1.0 MB    | ########################################################### | 100%
dbus-1.13.0          | 560 KB    | ########################################################### | 100%
hdf5-1.10.2          | 4.8 MB    | ########################################################### | 100%
zict-0.1.3           | 10 KB     | ########################################################### | 100%
libpng-1.6.35        | 305 KB    | ########################################################### | 100%
cloudpickle-0.5.5    | 15 KB     | ########################################################### | 100%
jsonschema-2.6.0     | 62 KB     | ########################################################### | 100%
ipywidgets-7.4.1     | 89 KB     | ########################################################### | 100%
attrs-18.2.0         | 30 KB     | ########################################################### | 100%
markupsafe-1.0       | 33 KB     | ########################################################### | 100%
pytz-2018.5          | 193 KB    | ########################################################### | 100%
fontconfig-2.13.1    | 320 KB    | ########################################################### | 100%
cycler-0.10.0        | 8 KB      | ########################################################### | 100%
bleach-2.1.4         | 21 KB     | ########################################################### | 100%
tblib-1.3.2          | 11 KB     | ########################################################### | 100%
lxml-4.2.5           | 6.0 MB    | ########################################################### | 100%
wcwidth-0.1.7        | 17 KB     | ########################################################### | 100%
pandas-0.23.4        | 27.8 MB   | ########################################################### | 100%
jupyter_contrib_nbex | 19.4 MB   | ########################################################### | 100%
numpy-1.15.1         | 9.3 MB    | ########################################################### | 100%
jupyter_client-5.2.3 | 59 KB     | ########################################################### | 100%
preshed-1.0.1        | 268 KB    | ########################################################### | 100%
qtconsole-4.4.1      | 156 KB    | ########################################################### | 100%
bcolz-1.2.1          | 2.8 MB    | ########################################################### | 100%
send2trash-1.5.0     | 12 KB     | ########################################################### | 100%
psutil-5.4.7         | 333 KB    | ########################################################### | 100%
expat-2.2.5          | 144 KB    | ########################################################### | 100%
ipython_genutils-0.2 | 21 KB     | ########################################################### | 100%
pyqt-5.6.0           | 5.4 MB    | ########################################################### | 100%
termcolor-1.1.0      | 6 KB      | ########################################################### | 100%
pyparsing-2.2.0      | 51 KB     | ########################################################### | 100%
tqdm-4.26.0          | 36 KB     | ########################################################### | 100%
simplegeneric-0.8.1  | 7 KB      | ########################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

\ + /path/Anaconda3/4.3.1/envs/fastai/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''jupyter_highlight_selected_word'\'', sys_prefix=True, logger=logging.getLogger())'

| + /path/Anaconda3/4.3.1/envs/fastai/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''latex_envs'\'', sys_prefix=True, logger=logging.getLogger())'

\ + /path/Anaconda3/4.3.1/envs/fastai/bin/jupyter-nbextensions_configurator enable --sys-prefix
Enabling: jupyter_nbextensions_configurator
- Writing config: /path/Anaconda3/4.3.1/envs/fastai/etc/jupyter
    - Validating...
      jupyter_nbextensions_configurator 0.4.0 OK
Enabling notebook nbextension nbextensions_configurator/config_menu/main...
Enabling tree nbextension nbextensions_configurator/tree_tab/main...

| + /path/Anaconda3/4.3.1/envs/fastai/bin/jupyter-contrib-nbextension install --sys-prefix
Traceback (most recent call last):
  File "/path/Anaconda3/4.3.1/envs/fastai/bin/jupyter-contrib-nbextension", line 4, in <module>
    import jupyter_contrib_nbextensions.application
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/jupyter_contrib_nbextensions/application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/jupyter_contrib_nbextensions/install.py", line 17, in <module>
    from notebook.notebookapp import list_running_servers
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/notebook/notebookapp.py", line 46, in <module>
    from zmq.eventloop import ioloop
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/cython/utils.cpython-36m-x86_64-linux-gnu.so: undefined symbol: zmq_curve_public

failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::jupyter_contrib_nbextensions-0.5.0-py36_0'.
LinkError: post-link script failed for package conda-forge::jupyter_contrib_nbextensions-0.5.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: /path/Anaconda3/4.3.1/envs/fastai/bin/.jupyter_contrib_nbextensions-post-link.sh
==> script messages <==
+ /path/Anaconda3/4.3.1/envs/fastai/bin/jupyter-contrib-nbextension install --sys-prefix
Traceback (most recent call last):
  File "/path/Anaconda3/4.3.1/envs/fastai/bin/jupyter-contrib-nbextension", line 4, in <module>
    import jupyter_contrib_nbextensions.application
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/jupyter_contrib_nbextensions/application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/jupyter_contrib_nbextensions/install.py", line 17, in <module>
    from notebook.notebookapp import list_running_servers
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/notebook/notebookapp.py", line 46, in <module>
    from zmq.eventloop import ioloop
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/cython/utils.cpython-36m-x86_64-linux-gnu.so: undefined symbol: zmq_curve_public


Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::jupyter_contrib_nbextensions-0.5.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: /path/Anaconda3/4.3.1/envs/fastai/bin/.jupyter_contrib_nbextensions-post-link.sh
==> script messages <==
+ /path/Anaconda3/4.3.1/envs/fastai/bin/jupyter-contrib-nbextension install --sys-prefix
Traceback (most recent call last):
  File "/path/Anaconda3/4.3.1/envs/fastai/bin/jupyter-contrib-nbextension", line 4, in <module>
    import jupyter_contrib_nbextensions.application
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/jupyter_contrib_nbextensions/application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/jupyter_contrib_nbextensions/install.py", line 17, in <module>
    from notebook.notebookapp import list_running_servers
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/notebook/notebookapp.py", line 46, in <module>
    from zmq.eventloop import ioloop
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /path/Anaconda3/4.3.1/envs/fastai/lib/python3.6/site-packages/zmq/backend/cython/utils.cpython-36m-x86_64-linux-gnu.so: undefined symbol: zmq_curve_public
```
Any ideas why this is happening? Thank you in advance!

**Comment by sgugger** [comment]
Not sure, you should use the [forum](http://forums.fast.ai/) to get more people to see your problem and help.

**Comment by nmvega** [comment]
FYI, I have the same issue. I'll look around, but here is my information:
```
[ ... Snip ... ]
    from . import (constants, error, message, context,
ImportError: /home/nmvega/ANACONDA3.d/lib/python3.6/site-packages/zmq/backend/cython/utils.cpython-36m-x86_64-linux-gnu.so: undefined symbol: zmq_curve_public
```
My environment ...
```
     active environment : None
       user config file : /home/nmvega/.condarc
 populated config files : /home/nmvega/.condarc
          conda version : 4.5.11
    conda-build version : 3.16.3
         python version : 3.6.7.final.0
       base environment : /home/nmvega/ANACONDA3.d  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/nmvega/ANACONDA3.d/pkgs
                          /home/nmvega/.conda/pkgs
       envs directories : /home/nmvega/ANACONDA3.d/envs
                          /home/nmvega/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.20.1 CPython/3.6.7 Linux/4.19.2-200.fc28.x86_64 fedora/28 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
