### ISSUE TITLE
testpath error when building a Dockerfile

### ISSUE THREAD

**Issue by iamimago** [fastai/fastai#845]
To begin with: I am aware it were a thread [here](https://github.com/fastai/fastai/issues/799) describing basically the same issue as i have, and that the solution were to comment a line out, but I'm trying to set it all up in a docker project so commenting the line out wont work (correct me if I'm wrong though, I'm not really sure how to comment the line out while using only "docker commands")

So anyway: I'm trying to set up the project using this Dockerfile:
```
FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

RUN apt-get update --fix-missing && apt-get install -y \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    wget \
    vim \
    git \
    unzip \
    python3-pip

RUN pip3 install --upgrade pip

# add conda to path
ARG CONDA_DIR=/opt/conda
ENV PATH $CONDA_DIR/bin:$PATH

# Install miniconda
ENV PYTHON_VERSION=3.6
RUN wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
    /opt/conda/bin/conda install conda-build

# Add the following channels to the bottom of the channel queue (lowest priority)
# conda-forge... for pymc3,dipy,textblob,imageio,ipyvolume
RUN conda config --append channels conda-forge/label/rc
RUN conda config --append channels conda-forge

RUN git clone https://github.com/fastai/fastai.git /usr/local/fastai

# install fastai environment
RUN cd /usr/local/fastai && \
    conda create -n fastai python=3.6 anaconda && \
    conda env update && \
    source activate fastai

RUN apt-get autoremove -y && apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    conda clean -i -l -t -y

# Add a notebook profile.
RUN mkdir -p -m 700 /root/.jupyter/ && \
    echo "c.NotebookApp.ip = '*'" >> /root/.jupyter/jupyter_notebook_config.py

RUN /bin/bash -c "source activate fastai && jupyter nbextension enable --py widgetsnbextension --sys-prefix"
RUN /bin/bash -c "source activate fastai && jupyter contrib nbextension install"

EXPOSE 8888

VOLUME /home
WORKDIR /home

ENTRYPOINT [ "/tini", "--" ]

# start jupyter server specifying password: fastai
# in jupyter notebook run the following to generate custom password key and update --NotebookApp.password=
# from notebook.auth import passwd; passwd()

#CMD /bin/bash -c "source activate fastai && CUDA_VISIBLE_DEVICES=0 jupyter notebook --allow-root --no-browser --NotebookApp.password='sha1:a60ff295d0b9:506732d050d4f50bfac9b6d6f37ea6b86348f4ed'"
CMD /bin/bash -c "source activate fastai && jupyter notebook --allow-root --no-browser --NotebookApp.password='sha1:a60ff295d0b9:506732d050d4f50bfac9b6d6f37ea6b86348f4ed'"
```

and this in turn produces this error message after building with: 
```docker build -t "imago/fastai:latest" .``` 

```
Requirement already satisfied: testpath in /opt/conda/envs/fastai/lib/python3.6/site-packages (from
nbconvert->-r /usr/local/fastai/condaenv.0z3n08fm.requirements.txt (line 12)) (0.4.1)

Traceback (most recent call last):
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2942, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; extra '"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_internal/resolve.py", line 307, in _resolve_one
    set(req_to_install.extras) - set(dist.extras)
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2819, in extras
    return [dep for dep in self._dep_map if dep]
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2864, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2874, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2935, in parse_requirements
    yield Requirement(line)
  File "/opt/conda/envs/fastai/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2944, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; extra '"


CondaValueError: pip returned an error
```

 
To reproduce, try building the image with the docker file listed above using the docker command mentioned above.

**Additional context**

The odd thing is that this used to work just a few weeks ago when i tried this: https://nji-syd.github.io/2018/03/26/up-and-running-with-fast-ai-and-docker/ Dockerfile out (which i'm basing my own on), but now both my own and the one provided by nji-syd has stopped working for some reason.

Any help is much appreciated!

**Comment by sswt** [comment]
I have the same issue when I am trying to build Dockerfile provided by nji-syd
[https://github.com/nji-syd/fastai-docker/blob/master/fastai.latest.cuda9](url)
The error is on line `RUN cd /usr/local/fastai && conda env update -f environment.yml `

**Comment by sgugger** [comment]
I'm closing this here as it should be discussed on the [forum](http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111/10), thanks!
