### ISSUE TITLE
.dcm file extension support

### ISSUE THREAD

**Issue by snmateen** [fastai/fastai#933]
i'm getting the following error when reading .dcm file using `ImageDataBunch`

```python
OSError: Traceback (most recent call last):
  File "/opt/local/miniconda/envs/dl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/local/miniconda/envs/dl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/local/miniconda/envs/dl/lib/python3.7/site-packages/fastai/vision/data.py", line 73, in __getitem__
    def __getitem__(self,i): return open_image(self.x[i]),self.y[i]
  File "/opt/local/miniconda/envs/dl/lib/python3.7/site-packages/fastai/vision/image.py", line 355, in open_image
    x = PIL.Image.open(fn).convert('RGB')
  File "/opt/local/miniconda/envs/dl/lib/python3.7/site-packages/PIL/Image.py", line 2657, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/opt/local/external/rsna/data/train/e59728f7-a4ac-47d3-9962-429bcdb579ef.dcm'
```

i'm i missing any libraries here?

**Comment by sgugger** [comment]
fastai v1 doesn't support .dcm images yet.

**Comment by snmateen** [comment]
Thanks Sylvain, can you please suggest me a workaround, i really like the way v1 is organized compare to the previous version. Or should i fall back to the previous version until .dcm support is added?

**Comment by sgugger** [comment]
I'd suggest writing your own dataset, copying the `ImageDataset`. Instead of `open_image` at the end, use `open_dcm_image` (that you would have to write). You can inspire yourself with the code of `open_image`, but will need to figure out how to transform you .dcm file in an array of pixels before passing it to the `Image` class.

Closing this here as it should be discussed on the [forum](https://forums.fast.ai).

**Comment by snmateen** [comment]
@sgugger , Thanks much!
